#!/bin/sh

# Make sure there are some keys...
if [ ! -f /etc/dropbear/dropbear_rsa_host_key ]; then
  mkdir -p /etc/dropbear
  /usr/bin/dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
  /usr/bin/dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
fi

exec /usr/bin/dropbear $@
