/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class NSMutableArray, NSMutableDictionary, NSString;

@interface BRAccountManager : BRSingleton
{
    NSString *_accountPath;
    NSString *_dataPath;
    NSString *_systemAccountDataPath;
    NSMutableArray *_accounts;
    NSMutableDictionary *_accountTypes;
    NSMutableDictionary *_preferredAccounts;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
+ (void)initialize;
- (id)init;
- (void)dealloc;
- (id)preferredAccountForType:(id)arg1;
- (void)clearPreferredAccountForType:(id)arg1;
- (void)markAsPreferredAccount:(id)arg1;
- (id)accountWithName:(id)arg1 ofType:(id)arg2;
- (id)accountWithName:(id)arg1 ofType:(id)arg2 create:(BOOL)arg3;
- (id)allAccounts;
- (id)accountsOfType:(id)arg1;
- (BOOL)isAccountManaged:(id)arg1;
- (void)manageAccount:(id)arg1;
- (void)removeAccount:(id)arg1;
- (void)registerClass:(Class)arg1 forType:(id)arg2;

@end

