/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRTextFieldDelegate-Protocol.h"

@class BRAccount, BRAccountSelector;

@interface BRAccountSelectorPasswordCollector : NSObject <BRTextFieldDelegate>
{
    BRAccount *_account;
    BRAccountSelector *_accountSelector;
}

- (id)initWithAccount:(id)arg1 accountSelector:(id)arg2;
- (void)textDidChange:(id)arg1;
- (void)textDidEndEditing:(id)arg1;
- (void)dealloc;

@end

