/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRAccountManager.h>

@interface BRAccountManager (Persistence)
- (void)_load;
- (void)_save;
- (void)_saveAccount:(id)arg1;
- (void)_saveAccount:(id)arg1 flushDiskImmediately:(BOOL)arg2;
- (void)_savePrefs;
- (id)_loadAccountFromFilePath:(id)arg1;
- (void)_deleteAccount:(id)arg1;
- (id)_encryptData:(id)arg1;
- (id)_decryptData:(id)arg1;
- (void)_accountDirty:(id)arg1;
@end

