/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRAC3ConfigurationManager : NSObject
{
    struct MovieType **_movie;
    unsigned int _playbackMode;
    struct TrackType **_playthroughTrack;
    struct TrackType **_softwareDecodeTrack;
}

+ (void)setupAC3AudioForMovie:(struct MovieType **)arg1 forAC3Track:(struct TrackType **)arg2;
+ (void)setupPCMAudioForMovie:(struct MovieType **)arg1;
+ (void)freeUpAC3ResourcesForMovie:(struct MovieType **)arg1;
+ (BOOL)trackIsAC3:(struct TrackType **)arg1;

@end

