/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaShelfControl.h>

@interface BRActionShelfControl : BRMediaShelfControl
{
    int _style;
    long _previousIndex;
}

- (id)focusedControlForEvent:(id)arg1 focusPoint:(struct CGPoint *)arg2;
- (void)setActionControlStyle:(int)arg1;
- (int)actionControlStyle;

@end

