/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMenuController.h>

#import "BRMenuListItemProvider-Protocol.h"

@class BRAccountType, NSArray;

@interface BRAccountSelectionController : BRMenuController <BRMenuListItemProvider>
{
    NSArray *_accounts;
    BRAccountType *_accountType;
}

- (id)initWithAccountType:(id)arg1;
- (void)dealloc;
- (void)itemSelected:(long)arg1;
- (id)itemForRow:(long)arg1;
- (long)itemCount;
- (id)titleForRow:(long)arg1;
- (float)heightForRow:(long)arg1;
- (BOOL)rowSelectable:(long)arg1;

@end

