/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRController.h>

@class BRHeaderControl, BRImageControl, BRTextControl;

@interface BRAlertController : BRController
{
    id _eventDelegate;
    SEL _eventSelector;
    BRHeaderControl *_header;
    int _type;
    BRTextControl *_primary;
    BRTextControl *_secondary;
    BRImageControl *_image;
}

+ (id)alertForError:(id)arg1;
+ (id)alertOfType:(int)arg1 titled:(id)arg2 primaryText:(id)arg3 secondaryText:(id)arg4;
- (id)initWithType:(int)arg1 titled:(id)arg2 primaryText:(id)arg3 secondaryText:(id)arg4;
- (void)dealloc;
- (void)layoutSubcontrols;
- (BOOL)recreateOnReselect;
- (BOOL)brEventAction:(id)arg1;
- (void)controlWasActivated;
- (void)wasPushed;
- (void)setTitle:(id)arg1;
- (void)setPrimaryText:(id)arg1;
- (void)setPrimaryText:(id)arg1 withAttributes:(id)arg2;
- (id)primaryText;
- (id)primaryTextControl;
- (void)setSecondaryText:(id)arg1;
- (id)secondaryText;
- (id)secondaryTextControl;
- (void)setSecondaryText:(id)arg1 withAttributes:(id)arg2;
- (void)setEventDelegate:(id)arg1 selector:(SEL)arg2;

@end

