/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRAlertControl.h>

@interface BRAlertControl (Private)
- (void)_layoutSubcontrolsForInfo;
- (void)_layoutSubcontrolsForAlert;
- (id)_controlsForType:(int)arg1;
- (id)_primaryTextAttibutesForType:(int)arg1;
@end

