/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface BRApplianceCategory : NSObject
{
    NSMutableDictionary *_info;
}

+ (id)categoryWithName:(id)arg1 identifier:(id)arg2 preferredOrder:(float)arg3;
- (id)init;
- (void)dealloc;
- (void)setName:(id)arg1;
- (id)name;
- (void)setPreferredOrder:(float)arg1;
- (float)preferredOrder;
- (void)setIsDefaultCategory:(BOOL)arg1;
- (BOOL)isDefaultCategory;
- (void)setIdentifier:(id)arg1;
- (id)identifier;
- (void)setAction:(id)arg1;
- (id)action;
- (void)setIsStoreCategory:(BOOL)arg1;
- (BOOL)isStoreCategory;
- (void)setIsStoreDependent:(BOOL)arg1;
- (BOOL)isStoreDependent;
- (void)setShouldDisplayOnStartup:(BOOL)arg1;
- (BOOL)shouldDisplayOnStartup;

@end

