/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRApplianceManager.h>

@interface BRApplianceManager (Private)
- (id)_controllerForApplianceKey:(id)arg1 identifier:(id)arg2 args:(id)arg3;
- (BOOL)_handlePlay:(id)arg1 userInfo:(id)arg2;
@end

