/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRAppManager : NSObject
{
    struct __CFRunLoop *_mainRunLoop;
    BOOL _isTerminating;
}

+ (id)sharedApplication;
- (void)terminate;
- (BOOL)isTerminating;
- (void)run;
- (void)postNotificationOnMainThread:(id)arg1;
- (void)postNotificationOnMainThreadNamed:(id)arg1;
- (void)postNotificationOnMainThreadNamed:(id)arg1 object:(id)arg2;
- (void)_postNotification:(id)arg1;

@end

