/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRAsyncImageControl.h>

@interface BRAsyncImageControl (Private)
- (void)_enableFadeInAnimation;
- (void)_enableSpinner;
- (void)_fetchCachedThumbnailImage;
- (void)_fetchPreferredSizeImage;
- (void)_startImageProcessingTaskForImage:(id)arg1;
- (id)_imageOfSize:(int)arg1;
- (void)_cropImage:(id)arg1;
- (void)_scaleImage:(id)arg1;
- (void)_imageTaskComplete:(id)arg1;
- (id)_getImageFromImageManagerNamed:(id)arg1 withSize:(struct CGSize)arg2;
- (void)_imageUpdated:(id)arg1;
- (void)_imageUnavailable:(id)arg1;
- (void)_setImage:(id)arg1;
- (void)_setImageID:(id)arg1;
- (void)_updateContents;
@end

