/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBackgroundTask.h>

@interface BRBackgroundTask (Notifications)
+ (void)_suspendBackgroundProcessing:(id)arg1;
+ (void)_resumeBackgroundProcessing:(id)arg1;
+ (void)_suspendHeavyBackgroundProcessing:(id)arg1;
+ (void)_resumeHeavyBackgroundProcessing:(id)arg1;
@end

