/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBaseAppliance.h>

@interface BRBaseAppliance (Private)
- (id)_applianceCategories;
- (BOOL)_isCategoryWithIdentifier:(id)arg1 memberOfMusicStoreCollection:(id)arg2;
- (BOOL)_anySharesAvailable;
- (BOOL)_anyStoreCategoryExistsInMusicStoreCollection:(id)arg1;
@end

