/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary;

@interface BRBackgroundTask : NSObject
{
    double _interval;
    double _delay;
    BOOL _enabled;
    int _taskType;
    NSDictionary *_userInfo;
}

+ (void)initialize;
+ (void)enableBackgroundTasksOfType:(int)arg1;
+ (id)taskForContext:(id)arg1 ofType:(int)arg2;
+ (void)disableBackgroundTasks:(id)arg1 ofType:(int)arg2;
+ (void)registerBackgroundTask:(id)arg1;
+ (void)unregisterBackgroundTask:(id)arg1;
+ (void)performFinishedForTask:(id)arg1;
- (id)initWithInterval:(double)arg1 delay:(double)arg2 userInfo:(id)arg3 taskType:(int)arg4;
- (void)dealloc;
- (int)type;
- (double)interval;
- (void)enable;
- (void)disable:(id)arg1;
- (BOOL)perform:(id)arg1;
- (void)stop;
- (BOOL)enabled;

@end

