/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBoxLayoutManager.h>

@class NSString;

@interface BRBoxFlowLayoutManager : BRBoxLayoutManager
{
    float _nonAxisAlignment;
    float _spacingScale;
    NSString *_backgroundControlName;
}

- (id)initWithDirection:(int)arg1;
- (void)dealloc;
- (void)setNonAxisAlignment:(float)arg1;
- (void)setBackgroundControlName:(id)arg1;
- (void)setSpacingScale:(float)arg1;
- (void)invalidateLayoutOfLayer:(id)arg1;
- (struct CGSize)preferredSizeOfLayer:(id)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;

@end

