/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRButtonControl.h>

@interface BRButtonControl (Private)
- (id)_nonFocusedOpacityForControlNamed:(id)arg1;
- (void)_setNonAttributedTitle:(id)arg1;
- (void)_setNonAttributedSubtitle:(id)arg1;
- (id)_addFadeAnimationToLayer:(id)arg1 forKey:(id)arg2;
- (void)_addOpacityFadeAnimationIfNeededToControl:(id)arg1;
- (void)_updateFocusOpacityOfControl:(id)arg1;
- (void)_updateAllFocusOpacities;
- (void)_addSortedControl:(id)arg1;
- (void)_setBackgroundHighlightImage:(id)arg1;
- (void)_setBottomBackgroundHighlightImage:(id)arg1;
- (void)_updateBackgroundDialogImages;
- (void)_updateImageLayer;
- (void)_focusWasChanged;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (void)_layoutDialogSublayers;
- (void)_layoutActionSublayers;
- (void)_layoutDashedSublayers;
- (void)_layoutGlossySublayers;
- (void)_setControlOrderArray:(id)arg1;
@end

