/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImage, BRImageControl, BRTextControl, NSArray;

@interface BRButtonControl : BRControl
{
    int _style;
    BRImageControl *_imageControl;
    BRImageControl *_badgeControl;
    BRTextControl *_titleControl;
    BRTextControl *_subtitleControl;
    BRImageControl *_overlayImageControl;
    BRImageControl *_backgroundImageControl;
    BRImageControl *_bottomBackgroundImageControl;
    BRImage *_image;
    BRImage *_highlightedImage;
    NSArray *_subcontrolOrder;
    BOOL _subcontrolsNeedSorting;
    BOOL _buttonEnabled;
}

+ (id)actionButtonWithImage:(id)arg1 subtitle:(id)arg2 badge:(id)arg3;
+ (id)actionButtonWithTitle:(id)arg1 subtitle:(id)arg2 badge:(id)arg3;
+ (id)dialogButtonWithTitle:(id)arg1;
+ (id)dashedActionButtonWithTitle:(id)arg1 subtitle:(id)arg2 selectable:(BOOL)arg3;
+ (id)glossyButtonWithTitle:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)setButtonStyle:(int)arg1;
- (void)setTitle:(id)arg1;
- (id)title;
- (void)setSubtitle:(id)arg1;
- (id)subtitle;
- (void)setImage:(id)arg1;
- (id)image;
- (void)setBadgeImage:(id)arg1;
- (id)badgeImage;
- (void)setOverlayImage:(id)arg1;
- (id)overayImage;
- (void)setHighlightedImage:(id)arg1;
- (id)highlightedImage;
- (void)setButtonEnabled:(BOOL)arg1;
- (void)controlWasActivated;
- (void)layoutSubcontrols;

@end

