/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class NSAttributedString;

@interface BRCCTextLayer : BRControl
{
    NSAttributedString *_wholeAttributedString;
    struct CGPoint _locationInCCUnits;
    BOOL _shouldRenderBackground;
    float _italicFactor;
    float _indentSpacing;
    char *_characterPopulationArray;
    BOOL _isCompletelyErased;
}

- (id)init;
- (void)_createSublayers;
- (id)initWithAttributedString:(id)arg1 atLocation:(struct CGPoint)arg2 renderBackground:(BOOL)arg3;
- (void)dealloc;
- (void)layoutSubcontrols;
- (id)attributedString;
- (struct CGPoint)stringLocation;
- (void)setIndentSpacing:(float)arg1;
- (struct CGSize)renderedSizeWithMaxSize:(struct CGSize)arg1;
- (struct CGRect)frameInCCUnits;
- (float)italicFactor;
- (void)eraseCharactersAtLocation:(struct CGPoint)arg1 length:(int)arg2;
- (BOOL)isCompletelyErased;

@end

