/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

#import "BRTabControlDelegate-Protocol.h"

@class BRImage, BRImageControl, BRMediaPlayer, BRReflectionControl, BRTabControl, BRTextControl, BRVideoChapterProvider, NSString, NSValue;

@interface BRChapterSubtitleAudioPickerControl : BRControl <BRTabControlDelegate>
{
    BRImage *_currentVideoFrame;
    BRControl *_screenShotPreviewAndReflectionComboControl;
    BRImageControl *_screenShotPreviewControl;
    struct CGPoint _screenShotPreviewControlFullScreenPosition;
    BRReflectionControl *_reflectionToPreviewControl;
    NSValue *_previewTransform;
    NSValue *_reflectionTransform;
    BRVideoChapterProvider *_chapterProvider;
    BRControl *_csaPicker;
    BRTabControl *_tabControl;
    BRTextControl *_titleControl;
    BRMediaPlayer *_player;
    BRControl *_currentContentControl;
    BRControl *_chapterPicker;
    NSString *_selectedChapter;
    NSString *_selectedSubtitle;
    NSString *_selectedAudioTrack;
    BOOL _inScreenShotMode;
    BOOL _controlWasActivated;
    BOOL _controlWasDeactivated;
}

+ (id)controlWithPlayer:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)setPlayer:(id)arg1;
- (void)orderOut;
- (void)controlWasActivated;
- (void)layoutSubcontrols;
- (void)tabControl:(id)arg1 didSelectTabItem:(id)arg2;
- (void)tabControl:(id)arg1 willSelectTabItem:(id)arg2;
- (void)tabControlDidChangeNumberOfTabItems:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;

@end

