/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRAsyncImageControl, BRMarqueeTextControl, NSDictionary;

@interface BRChapterGridItem : BRControl
{
    BRAsyncImageControl *_imageControl;
    BRMarqueeTextControl *_chapterTitleControl;
    NSDictionary *_chapterInfo;
}

- (id)init;
- (void)dealloc;
- (void)setChapterInfo:(id)arg1;
- (id)chapterInfo;
- (void)controlWasFocused;
- (void)controlWasUnfocused;

@end

