/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRChapterSubtitleAudioPickerControl.h>

@interface BRChapterSubtitleAudioPickerControl (Private)
- (void)_setChapter:(id)arg1;
- (void)_setSubtitle:(id)arg1;
- (void)_setAudioTrack:(id)arg1;
- (BOOL)_chapterPreviewsAvailable;
- (void)_loadChapters;
- (void)_loadTextualChapterList;
- (void)_loadGraphicalChapterList;
- (void)_loadSubtitleList;
- (void)_loadAudioList;
- (void)_loadList:(id)arg1 withCurrentSelection:(id)arg2 withSelectionHandler:(id)arg3;
@end

