/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

#import "BRClosedCaptionHandler-Protocol.h"

@class NSMutableArray;

@interface BRClosedCaptionControl : BRControl <BRClosedCaptionHandler>
{
    struct CGRect _enclosingCCFrame;
    int _CCRenderMode;
    NSMutableArray *_currentlyVisibleLayers;
    NSMutableArray *_CCTextLayers;
}

- (id)init;
- (void)dealloc;
- (void)setRenderMode:(int)arg1;
- (void)closedCaptionBeginUpdate;
- (void)closedCaptionEndUpdate;
- (void)closedCaptionEraseRowWithParameters:(id)arg1;
- (void)closedCaptionDisplayRowWithParameters:(id)arg1;
- (void)clearCaptions;
- (void)layoutSubcontrols;

@end

