/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBaseMenuItemLayerPopulator.h>

@interface BRCollectionMenuItemPopulator : BRBaseMenuItemLayerPopulator
{
}

+ (BOOL)canHandleObject:(id)arg1;
- (id)menuItemLayer;
- (id)textImageMenuItemLayer;
- (float)menuItemHeightForObject:(id)arg1 delegate:(id)arg2;
- (id)numItemsString;
- (id)allowedTypesPredicate;
- (unsigned int)numItemsInCollection:(id)arg1 hasOnlySongs:(char *)arg2;

@end

