/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControllerStack.h>

@interface BRControllerStack (TransactionEngine)
- (void)_addTransaction:(id)arg1;
- (void)_processTransactions;
- (void)_setContent:(id)arg1;
- (void)_processPushTransaction:(id)arg1;
- (void)_processPopTransaction:(id)arg1;
- (void)_processSwapTransaction:(id)arg1;
- (void)_processPopToTransaction:(id)arg1;
- (void)_processPopToClassTransaction:(id)arg1;
- (void)_processPopToLabelTransaction:(id)arg1;
- (void)_processRemoveTransaction:(id)arg1;
- (void)_processReplaceAllTransaction:(id)arg1;
- (void)_processReplaceControllersAboveLabelTransaction:(id)arg1;
- (void)_performDepthLimitedCullingForController:(id)arg1;
@end

