/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRCoverArtPreviewControl.h>

@interface BRCoverArtPreviewControl (Private)
- (void)_loadImage:(id)arg1;
- (void)_crossFadeToNextImage:(id)arg1;
- (void)_cleanupTimer;
- (void)_scheduleTimerOnMainThread;
- (void)_updateCoverArt:(id)arg1;
@end

