/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRMediaType, NSArray, NSMutableArray, NSTimer;

@interface BRCoverArtPreviewControl : BRControl
{
    NSArray *_imageProxies;
    NSMutableArray *_availableImages;
    BRMediaType *_mediaType;
    NSTimer *_crossfadeTimer;
    long _imageIndex;
    float _rotation;
    BOOL _artworkNeedsDeletterboxing;
    BOOL _actionAdded;
}

- (id)init;
- (void)dealloc;
- (void)layoutSubcontrols;
- (void)setImageProxy:(id)arg1;
- (void)setImageProxies:(id)arg1;
- (void)setMissingAssetType:(id)arg1;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)setDeletterboxAssetArtwork:(BOOL)arg1;
- (void)setRotation:(float)arg1;

@end

