/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRImageControl.h>

@interface BRCoverArtImageLayer : BRImageControl
{
    id _imageProxy;
    BOOL _deletterboxImage;
    BOOL _showsDefaultCoverArt;
}

- (id)init;
- (void)dealloc;
- (void)setImageProxy:(id)arg1;
- (void)setDeletterboxImage:(BOOL)arg1;
- (BOOL)deletterboxImage;
- (void)setShowsDefaultCoverArt:(BOOL)arg1;
- (BOOL)showsDefaultCoverArt;

@end

