/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@interface BRControl (PrivateScrollHelpers)
- (id)_parentScrollControl;
- (struct CGRect)_visibleRectOfControl:(id)arg1;
- (void)_scrollPoint:(struct CGPoint)arg1 fromControl:(id)arg2;
- (void)_scrollRect:(struct CGRect)arg1 fromControl:(id)arg2;
@end

