/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRNinePartWidgetLayer.h>

@interface BRCursorLayer : BRNinePartWidgetLayer
{
    float _radius;
    float _haloPercentage;
}

- (id)init;
- (float)haloPercentage;
- (void)setHaloPercentage:(float)arg1;
- (float)cornerRadius;
- (void)setCornerRadius:(float)arg1;
- (id)imageMapForCornerRadius:(float)arg1;

@end

