/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRDataStoreProvider.h>

@interface BRDataStoreProvider (NotificationHandlers)
- (void)_databaseMessagesSuppressed:(id)arg1;
- (void)_databaseObjectWasAdded:(id)arg1;
- (void)_databaseObjectWasModified:(id)arg1;
- (void)_databaseObjectWillBeDeleted:(id)arg1;
- (void)_hostAvailabilityChanged:(id)arg1;
- (void)_updateDataIfNeeded:(id)arg1;
@end

