/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRDividerControl, BRMetadataDetailControl, BRMetadataTitleControl, BRTextControl;

@interface BRDetailedMetadataControl : BRControl
{
    int _displayOption;
    BRMetadataDetailControl *_detailControl;
    BRMetadataTitleControl *_titleControl;
    BRDividerControl *_topDivider;
    BRDividerControl *_middleDivider;
    BRTextControl *_summaryControl;
}

- (id)init;
- (void)dealloc;
- (void)setTitle:(id)arg1;
- (void)setTitleSubtext:(id)arg1;
- (void)setRating:(id)arg1;
- (void)setSummary:(id)arg1;
- (void)setTopRightImage:(id)arg1;
- (void)toggleSummaryMetadataView;
- (void)addDetailStrings:(id)arg1 withLabel:(id)arg2;
- (void)addDetailControls:(id)arg1 withLabel:(id)arg2;
- (void)layoutSubcontrols;
- (float)renderedHeightForWidth:(float)arg1;

@end

