/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRProvider-Protocol.h"

@class BRControl;

@interface BRDividerProvider : NSObject <BRProvider>
{
    id _provider;
    BRControl *_topDivider;
    BOOL _dividerHidden;
    BOOL _showDivider;
}

+ (id)providerWithProvider:(id)arg1;
- (id)initWithProvider:(id)arg1;
- (void)dealloc;
- (id)provider;
- (void)addDividerWithLabel:(id)arg1;
- (void)addDividerWithLabel:(id)arg1 andOrientation:(int)arg2;
- (void)removeDivider;
- (void)setDividerHidden:(BOOL)arg1;
- (BOOL)dividerHidden;
- (BOOL)dividerVisible;
- (id)controlFactory;
- (long)dataCount;
- (id)dataAtIndex:(long)arg1;
- (id)hashForDataAtIndex:(long)arg1;

@end

