/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRDisplayManager.h>

@interface BRDisplayManager (ModeStringMappingPrivate)
- (id)_fetchModeForString:(id)arg1;
- (const struct BRDisplayStringMappingEntry *)_mappingEntryForString:(id)arg1;
- (const struct BRDisplayStringMappingEntry *)_mappingEntryForMode:(id)arg1;
- (BOOL)_mappingEntry:(const struct BRDisplayStringMappingEntry *)arg1 matchesMode:(id)arg2;
- (struct BRDisplayStringMappingEntry *)_mappingTable;
@end

