/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class NSTimer;

@interface BRDisplayManager : BRSingleton
{
    struct _CGDirectDisplayID *_display;
    struct CGSize _renderingSize;
    struct CGSize _upscaleSize;
    NSTimer *_delayedRefresh;
    BOOL _listenForEvents;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
+ (id)currentDisplayModeUIString;
+ (id)uiStringForDisplayMode:(id)arg1;
- (id)init;
- (void)dealloc;
- (struct _CGDirectDisplayID *)display;
- (BOOL)displayOnline;
- (struct CGSize)renderingSize;
- (struct CGSize)outputSize;
- (BOOL)interlaced;
- (double)refreshRate;
- (BOOL)displayConfigured;
- (id)displayMode;
- (BOOL)setDisplayMode:(id)arg1;
- (int)connectionType;
- (id)connectionTypeDescriptionForDisplay:(struct _CGDirectDisplayID *)arg1;
- (id)stringForDisplayMode:(id)arg1;
- (id)displayModeMostLikelySafeForCurrentDisplay;
- (id)displayModeForString:(id)arg1 modeSafe:(char *)arg2;
- (id)displayModeNearString:(id)arg1 mustBeSafe:(BOOL)arg2;
- (BOOL)displayModeSupported:(id)arg1;
- (id)listOfSafeSupportedModes;
- (id)listOfAllSupportedModes;
- (void)checkDisplayConfiguration:(char *)arg1;
- (BOOL)setColorSpace:(int)arg1;
- (int)colorSpace;
- (id)availableColorSpaces;
- (BOOL)rangeLimitedHDMI;
- (void)setShouldLimitHDMIRange:(BOOL)arg1;

@end

