/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class NSAttributedString;

@interface BRDividerControl : BRControl
{
    NSAttributedString *_label;
    float _brightness;
    float _alignmentFactor;
    float _lineThickness;
    float _startOffset;
    float _endOffset;
    BOOL _drawsLine;
    float _startOffsetText;
    int _dividerOrientation;
    int _dividerHeightStyle;
}

- (id)init;
- (void)dealloc;
- (void)setLabel:(id)arg1;
- (void)setLabel:(id)arg1 withAttributes:(id)arg2;
- (void)setAlignmentFactor:(float)arg1;
- (void)setStartOffset:(float)arg1;
- (void)setEndOffset:(float)arg1;
- (void)setLineThickness:(float)arg1;
- (struct CGSize)preferredFrameSize;
- (float)recommendedHeight;
- (float)recommendedWidth;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)setBrightness:(float)arg1;
- (float)brightness;
- (void)setDrawsLine:(BOOL)arg1;
- (BOOL)drawsLine;
- (void)setStartOffsetText:(float)arg1;
- (void)setDividerOrientation:(int)arg1;
- (int)dividerOrientation;
- (void)setDividerHeightStyle:(int)arg1;
- (int)dividerHeightStyle;

@end

