/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSSortDescriptor.h"

@interface BRDisplayModeRefreshRateSortDescriptor : NSSortDescriptor
{
    double _targetRefreshRate;
}

+ (id)sortDescriptorWithKey:(id)arg1 ascending:(BOOL)arg2 targetRefreshRate:(double)arg3;
- (id)initWithKey:(id)arg1 ascending:(BOOL)arg2 targetRefreshRate:(double)arg3;
- (int)compareObject:(id)arg1 toObject:(id)arg2;

@end

