/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRReflectedImageControl, BRTextControl, BRZoomingDialogControl;

@interface BRDownloadPlayableAlertControl : BRControl
{
    BRZoomingDialogControl *_panel;
    BRControl *_dialogBox;
    BRReflectedImageControl *_imageControl;
    BRTextControl *_titleControl;
    BRTextControl *_clockStartWarningControl;
    BRTextControl *_directionsControl;
    id _asset;
    double _activationTime;
}

+ (void)postPlayableAlertForAsset:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)controlWasActivated;
- (struct CGSize)preferredFrameSize;
- (BOOL)brEventAction:(id)arg1;

@end

