/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class NSAttributedString, NSString;

@interface BRErrorLayer : BRControl
{
    NSString *_title;
    NSAttributedString *_alertRef;
    NSAttributedString *_messageRef;
}

- (void)dealloc;
- (void)setFrame:(struct CGRect)arg1;
- (void)setTitle:(id)arg1;
- (void)setFailureReason:(id)arg1;
- (void)setRecoverySuggestion:(id)arg1;

@end

