/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BREvent, NSMutableArray, NSTimer;

@interface BREventManager : NSObject
{
    NSObject *_firstResponder;
    BREvent *_currentEvent;
    NSTimer *_retriggerTimer;
    NSTimer *_blockingTimer;
    NSMutableArray *_eventQueue;
    struct __CFRunLoopSource *_source;
    struct __CFRunLoop *_runLoop;
    double _flushBeforeTimeStamp;
    long _retriggerCount;
    BOOL _dumpWhenUnblocked;
    BOOL _eventsBlocked;
    BOOL _handlingEvent;
    BOOL _isInModalLoop;
}

+ (id)sharedManager;
- (id)initWithRunLoop:(struct __CFRunLoop *)arg1 mode:(struct __CFString *)arg2;
- (id)init;
- (void)dealloc;
- (void)setFirstResponder:(id)arg1;
- (id)firstResponder;
- (void)blockEventsForTime:(double)arg1 dumpWhenFinished:(BOOL)arg2;
- (id)currentEvent;
- (void)postEvent:(id)arg1;
- (void)dispatchEventOnEventThread:(id)arg1;
- (void)emptyQueue;
- (void)setIsInModalLoop:(BOOL)arg1;
- (BOOL)isInModalLoop;
- (void)retriggerCurrentEvent;
- (void)retriggerCurrentEventWithDecreasingDelay;
- (void)retriggerCurrentEventAfterDelay:(double)arg1;
- (void)cancelRetriggerCurrentEvent;

@end

