/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRFadeThroughBlackTransitionControl.h>

@interface BRFadeThroughBlackTransitionControl (Private)
- (void)_addShroud;
- (void)_removeShroud;
- (void)_updateContentForTransitionState;
- (void)_transitionInCompleted:(id)arg1;
- (void)_transitionOutCompleted:(id)arg1;
@end

