/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@interface BRFileManager : BRSingleton
{
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (BOOL)createDirectoryAtPath:(id)arg1 attributes:(id)arg2 error:(id *)arg3;
- (BOOL)removeItemAtPath:(id)arg1 error:(id *)arg2;
- (id)contentsOfDirectoryAtPath:(id)arg1 error:(id *)arg2;
- (void)removeContentsOfDirectoryAtPath:(id)arg1 error:(id *)arg2;
- (id)mostRecentModDateInDirectoryAtPath:(id)arg1 error:(id *)arg2;
- (id)attributesOfItemAtPath:(id)arg1 error:(id *)arg2;
- (BOOL)fileExistsAtPath:(id)arg1;
- (BOOL)fileExistsAtPath:(id)arg1 isDirectory:(char *)arg2;
- (BOOL)copyItemAtPath:(id)arg1 toPath:(id)arg2 error:(id *)arg3;
- (BOOL)moveItemAtPath:(id)arg1 toPath:(id)arg2 error:(id *)arg3;
- (id)modDateOfFileAtPath:(id)arg1;

@end

