/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRFullScreenPhotoController.h>

@interface BRFullScreenPhotoController (Private)
- (void)_setImageLayerTargetBounds;
- (void)_nextSlide;
- (void)_previousSlide;
- (void)_nextSlideWithTransition;
- (void)_previousSlideWithTransition;
- (void)_startSlideshow;
- (long)_switchToImageControlForIndex:(long)arg1 usingSwipeTransition:(BOOL)arg2;
- (void)_prefetchNextImage;
- (void)_stopImagePrefetching;
@end

