/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRGridControl.h>

@interface BRGridControl (FocusUtilities)
- (BOOL)controlAcceptsFocusAtIndex:(long)arg1;
- (void)focusControlAtIndex:(long)arg1;
- (struct CGRect)controlFrameAtIndex:(long)arg1;
- (struct CGRect)controlFocusFrameAtIndex:(long)arg1;
- (void)setAcceptsFocus:(BOOL)arg1;
@end

