/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRTextEntryLayoutManager.h>

@interface BRHexTextEntryLayoutManager : BRTextEntryLayoutManager
{
}

- (struct CGSize)preferredSizeOfLayer:(id)arg1;
- (struct CGRect)_mainKeysContainerFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)_textFieldLabelFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)_textFieldBackgroundFrame:(id)arg1 resolutionScale:(float)arg2;

@end

