/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class NSArray;

@interface BRHiddenSelectionControl : BRControl
{
    NSArray *_events;
    int _eventCount;
    BRControl *_content;
}

- (id)init;
- (void)dealloc;
- (id)content;
- (void)setContent:(id)arg1;
- (BOOL)brEventAction:(id)arg1;
- (id)events;
- (void)setEvents:(id)arg1;
- (void)layoutSubcontrols;

@end

