/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BREvent.h>

@interface BRHIDEvent : BREvent
{
    unsigned short _page;
    unsigned short _usage;
    unsigned long long _extendedSignature;
}

+ (id)eventWithPage:(unsigned short)arg1 usage:(unsigned short)arg2 value:(int)arg3 extendedSignature:(unsigned long long)arg4 atTime:(double)arg5;
+ (id)eventWithPage:(unsigned short)arg1 usage:(unsigned short)arg2 value:(int)arg3 extendedSignature:(unsigned long long)arg4;
+ (id)eventWithPage:(unsigned short)arg1 usage:(unsigned short)arg2 value:(int)arg3 atTime:(double)arg4;
+ (id)eventWithPage:(unsigned short)arg1 usage:(unsigned short)arg2 value:(int)arg3;
- (id)initWithPage:(unsigned short)arg1 usage:(unsigned short)arg2 value:(int)arg3;
- (id)initWithPage:(unsigned short)arg1 usage:(unsigned short)arg2 value:(int)arg3 extendedSignature:(unsigned long long)arg4;
- (id)initWithPage:(unsigned short)arg1 usage:(unsigned short)arg2 value:(int)arg3 atTime:(double)arg4;
- (id)initWithPage:(unsigned short)arg1 usage:(unsigned short)arg2 value:(int)arg3 extendedSignature:(unsigned long long)arg4 atTime:(double)arg5;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (unsigned short)page;
- (unsigned short)usage;
- (unsigned long long)extendedSignature;

@end

