/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRImage : NSObject
{
    struct CGImage *_image;
}

+ (id)imageWithURL:(id)arg1;
+ (id)imageWithPath:(id)arg1;
+ (id)imageWithData:(id)arg1;
+ (id)imageWithCIImage:(id)arg1;
+ (id)imageWithPDFURL:(id)arg1;
+ (id)imageWithCGImageRef:(struct CGImage *)arg1;
- (id)initWithCGImageRef:(struct CGImage *)arg1;
- (void)dealloc;
- (id)downsampledImageForMaxSize:(struct CGSize)arg1;
- (id)deletterboxedImage;
- (id)highlightedImage;
- (id)mapImageWithSourceRect:(struct CGRect)arg1 toSize:(struct CGSize)arg2;
- (id)croppedImageForSize:(struct CGSize)arg1;
- (struct CGRect)largestSquareRect;
- (id)squareImageFromNearSquareImage;
- (id)squareImageFromNearSquareImageWithAspectRatioLimit:(float)arg1;
- (struct CGImage *)image;
- (struct CGSize)pixelBounds;
- (BOOL)isPowerOfTwo;
- (float)aspectRatio;
- (void)drawImageInContext:(struct CGContext *)arg1 rect:(struct CGRect)arg2;

@end

