/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRTextMenuItemLayer.h>

@class BRImageControl;

@interface BRImageItemMenuLayer : BRTextMenuItemLayer
{
    BRImageControl *_imageItem;
}

+ (id)imageMenuItemWithImage:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)layoutSubcontrols;

@end

