/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRImageControl.h>

@interface BRImageControl (Deprecated)
- (void)setImage:(id)arg1 downsampleTo:(struct CGSize)arg2;
@end

