/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, NSDictionary, NSString, NSURL, NSURLConnection;

@interface BRImageLoadJob : NSObject
{
    NSString *_imageName;
    NSURL *_url;
    BOOL _encrypted;
    NSDictionary *_headerFields;
    NSURLConnection *_connection;
    NSDate *_requestDate;
    BOOL _writeImage;
}

- (id)initWithName:(id)arg1 url:(id)arg2 headerFields:(id)arg3 encrypted:(BOOL)arg4 writeImage:(BOOL)arg5;
- (void)dealloc;
- (id)name;
- (id)url;
- (BOOL)encrypted;
- (id)headerFields;
- (id)connection;
- (void)setConnection:(id)arg1;
- (id)requestDate;
- (BOOL)writeImage;

@end

