/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRImage.h>

@class NSData;

@interface BRInitialImage : BRImage
{
    NSData *_data;
}

+ (id)initialImageWithData:(id)arg1;
- (void)dealloc;
- (id)rawData;
- (void)purgeRawData;

@end

