/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRKeyboard, BRKeyboardCandidates, NSMutableArray, NSMutableString, NSString;

@interface BRInputMethod : NSObject
{
    int _textEntryStyle;
    NSString *_mostRecentCandidateCharacter;
    NSMutableString *_candidatesBuffer;
    NSMutableArray *_keyboards;
    BRKeyboard *_activeKeyboard;
    BRKeyboardCandidates *_candidatesKeyboard;
}

- (id)init;
- (void)dealloc;
- (id)name;
- (id)isoLanguageCode;
- (BOOL)setTextEntryStyle:(int)arg1;
- (int)textEntryStyle;
- (id)keyboards;
- (void)setActiveKeyboard:(id)arg1;
- (BOOL)usesCandidateDisplayForKeyboard:(id)arg1;
- (id)candidatesKeyboard;
- (void)removeCandidatesKeyboard;
- (BOOL)inputText:(id)arg1;
- (id)mostRecentCharacter;
- (BOOL)deleteText;
- (void)flushText;
- (id)candidates;

@end

