/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSString;

@interface BRIPConfiguration : NSObject
{
    NSString *_wirelessNetwork;
    NSString *_wirelessMACAddress;
    NSString *_wirelessIPAddress;
    NSString *_wirelessSubnetMask;
    NSString *_wirelessRouter;
    NSArray *_wirelessDNSAddresses;
    long _wirelessSignalQuality;
    unsigned int _wirelessUseDHCP:1;
    unsigned int _wirelessActive:1;
    NSString *_wiredMACAddress;
    NSString *_wiredIPAddress;
    NSString *_wiredSubnetMask;
    NSString *_wiredRouter;
    NSArray *_wiredDNSAddresses;
    unsigned int _wiredUseDHCP:1;
    unsigned int _wiredActive:1;
}

+ (void)startMonitoringNetworkChanges:(BOOL)arg1;
- (id)initFromCurrentConfiguration;
- (void)dealloc;
- (id)description;
- (void)setUseDHCPForInterface:(int)arg1;
- (void)setAddress:(id)arg1 subnetMask:(id)arg2 router:(id)arg3 forInterface:(int)arg4;
- (void)setDNSAddresses:(id)arg1 forInterface:(int)arg2;
- (BOOL)isActiveForInterface:(int)arg1;
- (BOOL)useDHCPForInterface:(int)arg1;
- (id)MACaddressForInterface:(int)arg1;
- (id)IPaddressForInterface:(int)arg1;
- (id)subnetMaskForInterface:(int)arg1;
- (id)routerForInterface:(int)arg1;
- (id)dnsAddressesForInterface:(int)arg1;
- (id)wirelessNetwork;
- (long)wirelessSignalQuality;

@end

