/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRIPConfiguration.h>

@interface BRIPConfiguration (Private)
+ (struct __SCDynamicStore *)_dynamicStoreSingleton;
- (void)_examineService:(struct __SCNetworkService *)arg1 usingStore:(struct __SCDynamicStore *)arg2;
- (void)_getStateForServiceID:(id)arg1 usingStore:(struct __SCDynamicStore *)arg2 ipAddress:(id *)arg3 mask:(id *)arg4 router:(id *)arg5;
- (id)_dnsAddressesForServiceID:(id)arg1 usingStore:(struct __SCDynamicStore *)arg2;
- (BOOL)_isActiveForInterface:(id)arg1 usingStore:(struct __SCDynamicStore *)arg2;
- (void)_getWirelessNetworkStateUsingStore:(struct __SCDynamicStore *)arg1;
- (BOOL)_setDHCPForService:(struct __SCNetworkService *)arg1;
- (BOOL)_setIPAddress:(id)arg1 subnetMask:(id)arg2 router:(id)arg3 forService:(struct __SCNetworkService *)arg4;
- (BOOL)_setDNSAddress:(id)arg1 forService:(struct __SCNetworkService *)arg2;
@end

