/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRIPv4AddressSelectionLayer.h>

@interface BRIPv4AddressSelectionLayer (SelectionAndModification)
- (void)_setSelection:(int)arg1;
- (void)_setDigitHighlighted:(BOOL)arg1 atIndex:(int)arg2;
- (void)_setDigitValue:(int)arg1 atIndex:(int)arg2;
- (id)_textEntryGlyphAttributes;
- (id)_textEntryGlyphGrayAttributes;
@end

