/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRInputMethod.h>

@class NSString;

@interface BRJapaneseInputMethod : BRInputMethod
{
    NSString *_mostRecentCandidateBaseCharacter;
}

- (void)dealloc;
- (id)name;
- (id)isoLanguageCode;
- (BOOL)usesCandidateDisplayForKeyboard:(id)arg1;
- (BOOL)inputText:(id)arg1;
- (id)candidates;
- (void)_createKeyboardsForTextEntryStyle:(int)arg1;

@end

