/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRKeyboard.h>

@interface BRKeyboard (BRKeyboardLayout)
- (struct CGSize)keyboardSize:(id)arg1;
- (struct CGRect)backgroundFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)actionKeysContainerFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)mainKeysContainerFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)candidatesBackgroundFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)candidatesContainerFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)textFieldLabelFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)textFieldBackgroundFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)textFieldFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)tabControlFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)magnifyingGlassFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)spinnerFrame:(id)arg1 resolutionScale:(float)arg2;
@end

