/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRKeyboard.h>

@interface BRKeyboard (BRKeyboardLayoutProtected)
- (struct CGSize)_minTextEntryControlSize:(id)arg1 resolutionScale:(float)arg2;
- (float)_topMostUIElementGap:(id)arg1 resolutionScale:(float)arg2;
- (struct CGSize)_textFieldBackgroundSize:(id)arg1 resolutionScale:(float)arg2;
- (float)_textFieldBackgroundBaseGap:(id)arg1 resolutionScale:(float)arg2;
- (struct CGSize)_candidatesContainerInset:(id)arg1 resolutionScale:(float)arg2;
- (struct CGSize)_candidatesBackgroundSize:(id)arg1 resolutionScale:(float)arg2;
- (float)_candidatesBackgroundBaseGap:(id)arg1 resolutionScale:(float)arg2;
- (struct CGSize)_tabControlSize:(id)arg1 resolutionScale:(float)arg2;
- (float)_tabControlBaseGap:(id)arg1 resolutionScale:(float)arg2;
- (struct CGSize)_mainKeysContainerSize:(id)arg1 resolutionScale:(float)arg2;
- (float)_mainKeysContainerBaseGap:(id)arg1 resolutionScale:(float)arg2;
- (struct CGSize)_actionKeysContainerSize:(id)arg1 resolutionScale:(float)arg2;
- (float)_actionKeysContainerBaseGap:(id)arg1 resolutionScale:(float)arg2;
@end

