/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRKeyboardJapaneseRomanSquare.h>

@interface BRKeyboardJapaneseFullRoman : BRKeyboardJapaneseRomanSquare
{
}

- (id)name;
- (void)setFocusToDefaultSwitchKeyboardGlyph:(id)arg1;
- (id)actionDictionaryForKeyControl:(id)arg1;
- (id)_keyboardDataFileName;

@end

