/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRKeyboardRomanWeb.h>

@interface BRKeyboardRomanWeb (BRKeyboardRomanWebPrivate)
- (void)_generateKeyEventWithCharacters:(id)arg1;
- (void)_prevousButtonClick:(id)arg1;
- (void)_nextButtonClick:(id)arg1;
- (void)_autoFillButtonClick:(id)arg1;
@end

