/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRKeyboard.h>

@interface BRKeyboard (BRKeyboardProtected)
- (id)_keyRows;
- (void)_tagBottomKeyRow:(id)arg1;
- (int)_numberOfMainKeyRows;
- (int)_numberOfColumnsForMainKeyRowIndex:(int)arg1;
- (id)_preferredLayoutManagerForMainKeyRow:(id)arg1 index:(int)arg2;
- (id)_preferredMainKeysContainerLayoutManager;
- (float)_mainKeysContainerSpacingScale;
- (int)_scrollDirectionForMainKeys;
@end

