/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRLegacyProvider.h>

@interface BRLegacyProvider (DividerSupport)
- (void)_updateDividers;
- (long)_providerRowForListRow:(long)arg1 divider:(id *)arg2;
- (long)_listRowForProviderRow:(long)arg1;
@end

