/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRProvider-Protocol.h"

@class NSMutableArray;

@interface BRLegacyProvider : NSObject <BRProvider>
{
    id _source;
    NSMutableArray *_dividers;
    long _firstDividerIndex;
    long _lastDividerIndex;
}

- (void)dealloc;
- (void)setDatasource:(id)arg1;
- (id)datasource;
- (void)addDividerAtIndex:(long)arg1 withLabel:(id)arg2;
- (void)removeDividerAtIndex:(long)arg1;
- (void)removeDividers;
- (id)controlFactory;
- (long)dataCount;
- (id)dataAtIndex:(long)arg1;
- (id)hashForDataAtIndex:(long)arg1;
- (long)providerIndexForDatasourceIndex:(long)arg1;
- (long)datasourceIndexForProviderIndex:(long)arg1;

@end

