/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRListControl.h>

@interface BRListControl (RepeatTimer)
- (void)_startRepeatTimerMovingDown:(BOOL)arg1;
- (void)_startDownwardAutoScroll:(id)arg1;
- (void)_startUpwardAutoScroll:(id)arg1;
- (void)_slowToStopRepeatTimerMovingDown:(BOOL)arg1;
- (void)_stopRepeatTimer;
- (void)_repeatDownTimerFired:(id)arg1;
- (void)_repeatUpTimerFired:(id)arg1;
- (void)_pokeTimerFired:(id)arg1;
- (double)_calculateRepeatRate;
@end

