/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRListControl.h>

@interface BRListControl (DividerSupport)
- (void)setShowsDividers:(BOOL)arg1;
- (BOOL)showsDividers;
- (void)setFirstDividerVisible:(BOOL)arg1;
- (BOOL)firstDividerVisible;
- (void)setName:(id)arg1 forProvider:(id)arg2;
@end

