/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMainMenuControl.h>

@interface BRMainMenuControl (Internal)
- (void)_reload;
- (void)_unload;
- (void)_updateAppliance;
- (id)_currentApplianceKey;
- (id)_currentCategoryIdentifier;
- (BOOL)_categorySelected:(id)arg1;
- (void)_windowBoundsChanged:(id)arg1;
@end

