/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMarqueeTextControl.h>

@interface BRMarqueeTextControl (AutoScrolling)
- (void)_beginScroll:(id)arg1;
- (void)_removeFadeMask:(id)arg1;
- (void)_resetScrollTimer;
- (void)_clearScrollTimer;
- (void)_clearFadeMaskTimer;
- (void)_scrollDidStart:(id)arg1;
- (void)_scrollDidStop:(id)arg1;
- (BOOL)_autoscrollInProgress;
@end

