/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRFadeMaskLayer, BRScrollingTextPlane, NSTimer;

@interface BRMarqueeTextControl : BRControl
{
    BRScrollingTextPlane *_plane;
    BRFadeMaskLayer *_mask;
    NSTimer *_scrollTimer;
    NSTimer *_fadeMaskTimer;
    float _maskRemovalTime;
    float _scrollPosition;
    BOOL _autoScrolls;
    BOOL _crossfadeEnabled;
    BOOL _crossfading;
}

- (id)init;
- (void)dealloc;
- (void)setText:(id)arg1 withAttributes:(id)arg2;
- (void)setAttributedString:(id)arg1;
- (float)maxScrollPosition;
- (id)attributedString;
- (struct CGSize)pixelBounds;
- (struct CGSize)renderedSize;
- (void)setAutoScrolls:(BOOL)arg1;
- (BOOL)autoScrolls;
- (void)setCrossfadeEnabled:(BOOL)arg1;
- (BOOL)crossfadeEnabled;
- (BOOL)needsScrollingInBounds:(struct CGRect)arg1;
- (void)setScrollPosition:(float)arg1;
- (float)scrollPosition;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)preferredActionForKey:(id)arg1;
- (void)layoutSubcontrols;
- (void)controlWasDeactivated;
- (void)controlWasActivated;

@end

