/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaHostConnectionDialog.h>

@interface BRMediaHostConnectionDialog (Private)
- (void)_checkMountStatus:(id)arg1;
- (void)_waitForHostReset:(id)arg1;
- (void)_authRequired:(id)arg1;
- (void)_hostsChanged:(id)arg1;
@end

