/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRMediaHostEvent, BRMediaHostState, NSDictionary, NSMutableArray, NSSet, NSTimer;

@interface BRMediaHost : NSObject
{
    NSDictionary *_hostInfo;
    NSMutableArray *_providers;
    int _hostType;
    NSMutableArray *_eventQueue;
    NSSet *_eventFilter;
    BRMediaHostEvent *_filterEvent;
    BRMediaHostState *_state;
    NSTimer *_eventTimer;
    BOOL _supportsPhotos;
    BOOL _supportsPhotoThumbnails;
    id _unresolvedProviderHandler;
}

+ (void)initialize;
+ (void)unmountAllHosts;
+ (void)unmountInactiveStreamingHosts;
+ (id)mediaHost;
+ (id)syncingMediaHostWithHostInfo:(id)arg1;
+ (id)streamingMediaHostWithHostInfo:(id)arg1;
+ (id)daapMediaHostWithHostInfo:(id)arg1;
+ (id)currentHost;
+ (id)localHost;
+ (void)setCurrentHost:(id)arg1;
+ (id)mediaHostMatchingHostInfo:(id)arg1;
+ (id)mediaHostForMediaProvider:(id)arg1;
+ (id)mediaHosts;
+ (id)pairedHost;
+ (id)syncingHost;
+ (id)streamingHosts;
+ (id)daapHosts;
+ (void)addMediaHost:(id)arg1;
+ (void)removeMediaHost:(id)arg1;
+ (void)removeMediaHost:(id)arg1 supressingRemoveNotification:(BOOL)arg2;
+ (BOOL)isPairedForSyncing:(char *)arg1;
+ (id)mountedMediaHosts;
+ (id)mediaProviderAdvertisingMediaTypes:(id)arg1;
+ (id)mediaProvidersAdvertisingMediaTypes:(id)arg1;
+ (id)localMediaProviderAdvertisingMediaTypes:(id)arg1;
+ (id)allRentalAssets;
- (id)init;
- (void)dealloc;
- (id)hostID;
- (void)setUnresolvedMediaProviderHandler:(id)arg1;
- (void)setHostname:(id)arg1;
- (void)waitForEvent:(id)arg1 toProcessEvent:(id)arg2;
- (void)postEvent:(id)arg1;
- (void)abandonEvent:(id)arg1;
- (id)hostInfo;
- (id)hostname;
- (void)_mount;
- (void)_unmount;
- (id)mediaProviders;
- (void)addMediaProvider:(id)arg1;
- (void)addMediaProvider:(id)arg1 checkForDuplicates:(BOOL)arg2;
- (void)removeMediaProvider:(id)arg1;
- (void)removeMediaProviderWithID:(id)arg1 andMachineID:(id)arg2;
- (id)mediaProviderWithID:(id)arg1 andMachineID:(id)arg2;
- (id)mediaProvidersAdvertisingMediaTypes:(id)arg1;
- (id)mediaProviderAdvertisingMediaTypes:(id)arg1;
- (id)registeredMediaProviderForMediaTypes:(id)arg1;
- (void)setState:(id)arg1;
- (id)state;
- (int)hostType;
- (BOOL)isLocal;
- (BOOL)supportsPhotos;
- (void)setSupportsPhotos:(BOOL)arg1;
- (void)setSupportsPhotoThumbnails:(BOOL)arg1;
- (BOOL)supportsPhotoThumbnails;
- (BOOL)containsPasswordedProvider;
- (id)lastAccessedDate;

@end

