/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface BRMediaPlayer : NSObject
{
    NSMutableArray *_stateStack;
}

+ (id)contentTypes;
+ (BOOL)allowMultiplePlayers;
+ (BOOL)handlesVideoForType:(id)arg1;
- (id)init;
- (void)dealloc;
- (BOOL)stopsActiveAudioPlayer;
- (BOOL)reverseTouchSwipeBehavior;
- (BOOL)setMediaAtIndex:(long)arg1 inTrackList:(id)arg2 error:(id *)arg3;
- (BOOL)setMediaAtIndex:(long)arg1 inCollection:(id)arg2 error:(id *)arg3;
- (id)collection;
- (id)media;
- (long)mediaIndex;
- (BOOL)cueMediaWithError:(id *)arg1;
- (BOOL)setState:(int)arg1 error:(id *)arg2;
- (int)playerState;
- (BOOL)supportsMultipleTrickSpeeds;
- (double)duration;
- (void)setElapsedTime:(double)arg1;
- (double)elapsedTime;
- (void)setStopTime:(double)arg1;
- (double)stopTime;
- (void)setStartTime:(double)arg1;
- (double)startTime;
- (void)resetToBeginning;
- (BOOL)hasChapters;
- (id)chapterTimes;
- (void)setVirtualChapterMark:(double)arg1;
- (double)virtualChapterMark;
- (void)nextChapter;
- (void)previousChapter;
- (void)setCurrentChapterIndex:(long)arg1;
- (long)chapterCount;
- (long)currentChapterIndex;
- (id)currentChapterTitle;
- (id)chapterTitleForIndex:(long)arg1;
- (BOOL)hasRealChapters;
- (BOOL)hasChapterPictures;
- (BOOL)chapterIsPlayable:(long)arg1;
- (id)chapterImageProxyForIndex:(long)arg1;
- (double)startTimeForChapter:(long)arg1;
- (double)endTimeForChapter:(long)arg1;
- (struct BRTimeRange)bufferedRange;
- (float)bufferingProgress;
- (void)setDisablePlatformFilters:(BOOL)arg1;
- (BOOL)disablePlatformFilters;
- (BOOL)attemptAuthorizationWithError:(id *)arg1;

@end

