/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRMediaObject-Protocol.h"

@protocol BRMediaCollection <BRMediaObject>
- (id)provider;
- (id)collectionID;
- (id)title;
- (id)titleForSorting;
- (id)titleNoDefault;
- (id)titleForSortingNoDefault;
- (id)artist;
- (id)artistForSorting;
- (int)count;
- (id)mediaType;
- (id)mediaTypes;
- (id)mediaAssets;
- (id)assetEnumerator;
- (BOOL)isCompilation;
- (BOOL)isSingleArtistCompilation;
- (id)imageProxy;
- (id)collectionType;
- (id)parentCollection;
- (id)childCollections;
- (long)duration;
- (BOOL)isLocal;
- (BOOL)isAvailable;
- (BOOL)isHidden;
- (void)willBeDeleted;
- (id)date;
@end

