/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerController.h>

@interface BRMediaPlayerController (ResumeMenu)
- (void)_transitionAnimationFinished;
- (double)_resumeTimeNearKeyframe;
- (double)_keyFrameAdjustedResumeTime:(double)arg1;
- (void)_dismissResumeMenuWithElapsedTime:(double)arg1;
- (void)_resumeItemSelected:(id)arg1;
- (void)_startFromBeginningItemSelected:(id)arg1;
- (void)_playExtraItemSelected:(id)arg1;
@end

