/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRCoverArtImageLayer, BRMetadataControl, BRReflectionControl, NSTimer;

@interface BRMetadataPreviewControl : BRControl
{
    id _asset;
    id _metadataProvider;
    BRControl *_coverArtWrapper;
    BRCoverArtImageLayer *_coverArtLayer;
    BRReflectionControl *_reflectionLayer;
    BRMetadataControl *_metadataLayer;
    NSTimer *_timer;
    BOOL _showsMetadataImmediately;
}

- (id)init;
- (void)dealloc;
- (void)layoutSubcontrols;
- (void)setImageProxy:(id)arg1;
- (void)setMetadataProvider:(id)arg1;
- (void)setAsset:(id)arg1;
- (id)asset;
- (void)setShowsMetadataImmediately:(BOOL)arg1;
- (BOOL)showsMetadataImmediately;
- (void)setDeletterboxAssetArtwork:(BOOL)arg1;
- (BOOL)deletterboxAssetArtwork;
- (void)setShowsDefaultCoverArt:(BOOL)arg1;
- (BOOL)showsDefaultCoverArt;
- (void)controlWasActivated;
- (void)controlWasDeactivated;

@end

