/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRProviderGroup, NSDictionary, NSMutableArray, NSTimer;

@interface BRMediaShelfControl : BRControl
{
    BRProviderGroup *_group;
    long _minNumberShelfItems;
    NSDictionary *_controlActions;
    NSDictionary *_titleActions;
    NSDictionary *_titleAttributes;
    float _coverflowMargin;
    long _columnCount;
    long _latestSelection;
    long _savedSelection;
    BOOL _centered;
    BOOL _scrollable;
    BOOL _showsDividers;
    BOOL _showsProviderNames;
    float _horizontalGap;
    struct _NSRange _flatRange;
    struct CATransform3D _leftTransform;
    struct CATransform3D _rightTransform;
    NSMutableArray *_cells;
    NSMutableArray *_titles;
    BOOL _handlingProviderChange;
    NSTimer *_scrollTimer;
    BOOL _scrolling;
    int _collapsedState;
    BOOL _featured;
    BOOL _ordered;
    BOOL _showAllTitles;
    BOOL _showTitleAndSubtitle;
    BOOL _needToReloadDataOnActivate;
}

- (id)init;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)reloadData;
- (void)setMinNumberOfShelfItems:(long)arg1;
- (long)minNumberOfShelfItems;
- (void)setProvider:(id)arg1;
- (void)setProviders:(id)arg1;
- (id)providers;
- (long)providerDataCount;
- (void)setColumnCount:(long)arg1;
- (long)columnCount;
- (void)setScrollable:(BOOL)arg1;
- (BOOL)scrollable;
- (void)setCentered:(BOOL)arg1;
- (BOOL)centered;
- (void)setFeatured:(BOOL)arg1;
- (BOOL)featured;
- (void)setOrdered:(BOOL)arg1;
- (BOOL)ordered;
- (void)setShowAllTitles:(BOOL)arg1;
- (BOOL)showAllTitles;
- (void)setShowTitleAndSubtitle:(BOOL)arg1;
- (BOOL)showTitleAndSubtitle;
- (void)setHorizontalGap:(float)arg1;
- (float)horizontalGap;
- (BOOL)brEventAction:(id)arg1;
- (void)setCoverflowMargin:(float)arg1;
- (float)coverflowMargin;
- (void)setFocusedIndex:(long)arg1;
- (long)focusedIndex;
- (id)selectedControl;
- (void)setCollapsedState:(int)arg1;
- (int)collapsedState;
- (void)layoutSubcontrols;
- (id)focusedControlForEvent:(id)arg1 focusPoint:(struct CGPoint *)arg2;

@end

