/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaHost.h>

@interface BRMediaHost (Notifications)
- (void)_mediaProviderLoaded:(id)arg1;
- (void)_mediaProviderLoadFailed:(id)arg1;
- (void)_mediaProviderUnloading:(id)arg1;
- (void)_mediaProviderUnloaded:(id)arg1;
@end

