/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaHost.h>

@interface BRMediaHost (Protected)
+ (id)_mediaProviderAdvertisingMediaTypes:(id)arg1 forceLocalResolution:(BOOL)arg2;
+ (id)_mediaProvidersAdvertisingMediaTypes:(id)arg1 forceLocalResolution:(BOOL)arg2;
+ (void)_removeHostFromMounts:(id)arg1;
+ (void)_addHostToMounts:(id)arg1;
+ (void)_hostsChanged;
- (int)_codingVersion;
- (void)_processNextEvent;
- (void)_processEvent:(id)arg1;
@end

