/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRTextMenuItemLayer;

@interface BRMenuItemMediator : NSObject
{
    BRTextMenuItemLayer *_menuItem;
    SEL _mediaParadeSelector;
    SEL _menuSelector;
    id _object;
}

+ (id)mediatorWithMenuItem:(id)arg1;
- (id)initWithMenuItem:(id)arg1;
- (void)dealloc;
- (id)menuItem;
- (void)setMediaPreviewSelector:(SEL)arg1;
- (SEL)mediaPreviewSelector;
- (void)setMenuActionSelector:(SEL)arg1;
- (SEL)menuActionSelector;
- (void)setMenuActionSelector:(SEL)arg1 withObject:(id)arg2;
- (id)object;

@end

