/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerEventHandler.h>

@interface BRMediaPlayerEventHandler (Handlers)
- (BOOL)_defaultEventHandler:(id)arg1;
- (BOOL)_handleForwardEvent:(id)arg1;
- (BOOL)_handleRewindEvent:(id)arg1;
- (BOOL)_handleRightEvent:(id)arg1;
- (BOOL)_handleLeftEvent:(id)arg1;
- (BOOL)_handleRightEventWhileChapterSkipping:(id)arg1;
- (BOOL)_handleLeftEventWhileChapterSkipping:(id)arg1;
- (BOOL)_handleEventWhilePaused:(id)arg1;
- (BOOL)_handleEventWhileLoading:(id)arg1;
- (BOOL)_handleEventWhileChapterSelecting:(id)arg1;
- (BOOL)_handleEventWhilePlaying:(id)arg1;
- (BOOL)_handleEventWhileFF1:(id)arg1;
- (BOOL)_handleEventWhileFF2:(id)arg1;
- (BOOL)_handleEventWhileFF3:(id)arg1;
- (BOOL)_handleEventWhileREW1:(id)arg1;
- (BOOL)_handleEventWhileREW2:(id)arg1;
- (BOOL)_handleEventWhileREW3:(id)arg1;
- (BOOL)_handleEventWhileSlowForward1:(id)arg1;
- (BOOL)_handleEventWhileSlowForward2:(id)arg1;
- (BOOL)_handleEventWhileSlowForward3:(id)arg1;
- (BOOL)_handleEventWhileSlowRewind1:(id)arg1;
- (BOOL)_handleEventWhileSlowRewind2:(id)arg1;
- (BOOL)_handleEventWhileSlowRewind3:(id)arg1;
- (void)_endChapterSelectionMode:(id)arg1;
@end

