/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaMenuController.h>

@class BRController, NSArray, NSDictionary;

@interface BRMediaShareListController : BRMediaMenuController
{
    Class _mediaControllerClass;
    BRController *_noMediaErrorController;
    BRController *_mountingController;
    NSDictionary *_selectedHostInfo;
    BOOL _isMounting;
    BOOL _isUnmounting;
    BOOL _hostDisconnected;
    NSArray *_hostInfos;
}

- (id)init;
- (void)dealloc;
- (id)previewControlForItem:(long)arg1;
- (void)itemSelected:(long)arg1;
- (void)controlWasActivated;
- (void)wasPushed;
- (void)wasExhumed;
- (void)wasPopped;
- (void)controlWasDeactivated;
- (void)setMediaControllerClass:(Class)arg1 errorController:(id)arg2;

@end

