/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMenuController.h>

@class BRControl, BRFocusableImageControl, BRTextControl, BRWaitSpinnerControl, NSString, NSTimer;

@interface BRMediaMenuController : BRMenuController
{
    BRControl *_previewControl;
    BRControl *_previewContainer;
    NSString *_previewControlItemHash;
    BRFocusableImageControl *_actionControl;
    BRWaitSpinnerControl *_spinner;
    BRControl *_observedControl;
    float _controlDelay;
    NSTimer *_controlDelayTimer;
    BRTextControl *_noContentMessageControl;
}

- (id)init;
- (void)dealloc;
- (void)setShowSpinner:(BOOL)arg1;
- (BOOL)showSpinner;
- (void)layoutSubcontrols;
- (id)focusedControlForEvent:(id)arg1 focusPoint:(struct CGPoint *)arg2;
- (BOOL)brEventAction:(id)arg1;
- (void)updatePreviewController;
- (void)resetPreviewController;
- (void)clearPreviewController;
- (BOOL)allowUnplayedMark;
- (id)actionSelectionHandlerForItemAtIndex:(long)arg1;
- (id)actionItemAtIndex:(long)arg1;
- (void)setNoContentMessage:(id)arg1;
- (id)noContentMessage;
- (void)refreshControllerForModelUpdate;
- (void)refreshControllerForModelUpdateToObject:(id)arg1;
- (void)controlWasActivated;
- (void)controlWasDeactivated;

@end

