/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRTextControl;

@interface BRMetadataLineLayer : BRControl
{
    BRTextControl *_labelLayer;
    BRControl *_valueLayer;
    float _maxLabelWidth;
}

- (id)initWithLabel:(id)arg1 value:(id)arg2;
- (void)dealloc;
- (id)label;
- (id)value;
- (void)setMaxLabelWidth:(float)arg1;
- (void)layoutSubcontrols;

@end

