/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageControl, BRTextControl;

@interface BRMetadataTitleControl : BRControl
{
    BRTextControl *_title;
    BRTextControl *_titleSubtext;
    BRImageControl *_rating;
    BRImageControl *_rightImage;
}

- (id)init;
- (void)dealloc;
- (void)setTitle:(id)arg1;
- (void)setTitleSubtext:(id)arg1;
- (void)setRating:(id)arg1;
- (void)setRightImage:(id)arg1;
- (struct CGSize)renderedSize;
- (void)layoutSubcontrols;

@end

