/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BREventResponder-Protocol.h"

@class BRMediaPlayer, NSTimer;

@interface BRMediaPlayerEventHandler : NSObject <BREventResponder>
{
    BRMediaPlayer *_player;
    BOOL _waitingForUp;
    BOOL _inChapterSkipMode;
    double _virtualChapterMark;
    NSTimer *_chapterSelectionModeTimer;
    int _preShuttleState;
    int _shuttleSpeed;
    int _shuttleDirection;
    BOOL _inShuttleMode;
    BOOL _readyToInitiateShuttle;
    NSTimer *_shuttleChapterSkipTimer;
    struct CGPoint _initialTouchPosition;
    struct CGPoint _lastTouchPosition;
    struct CGPoint _lastTouchDelta;
    double _shuttleFinishedTime;
}

+ (id)handlerWithPlayer:(id)arg1;
- (id)initWithPlayer:(id)arg1;
- (void)dealloc;
- (BOOL)brEventAction:(id)arg1;
- (BOOL)brKeyEvent:(id)arg1;
- (BOOL)showingChapterMarks;
- (void)_playerAssetChanged:(id)arg1;
- (void)_playerStateChanged:(id)arg1;

@end

