/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMenuController.h>

@interface BRMenuController (HeaderConvienceMethods)
- (void)setListTitle:(id)arg1 withAttributes:(id)arg2;
- (void)setListTitle:(id)arg1;
- (id)listTitle;
- (void)setListIcon:(id)arg1 horizontalOffset:(float)arg2 kerningFactor:(float)arg3;
- (void)setListIcon:(id)arg1;
- (id)listIcon;
- (void)setListIconHorizontalOffset:(float)arg1;
- (float)listIconHorizontalOffset;
- (void)setListIconKerningFactor:(float)arg1;
- (float)listIconKerningFactor;
- (id)controlForContextMenuPositioning;
- (id)controlForContextMenuStart;
- (id)controlToDim;
- (int)contextMenuDimOption;
@end

