/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerEventHandler.h>

@interface BRMediaPlayerEventHandler (TouchSpecific)
- (BOOL)_handleTouchEvent:(id)arg1;
- (BOOL)_handleTouchSwipeEvent:(id)arg1;
- (BOOL)_handleTouchSwipeRightEvent:(id)arg1;
- (BOOL)_handleTouchSwipeLeftEvent:(id)arg1;
- (BOOL)_handleTouchMultiSwipeRightEvent:(id)arg1;
- (BOOL)_handleTouchMultiSwipeLeftEvent:(id)arg1;
- (void)_setShuttleSpeed:(int)arg1;
- (void)_initiateShuttleAction;
- (void)_touchRepeatCancel;
- (void)_touchRepeatEvent;
@end

