/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRController.h>

@class BRClosedCaptionControl, BRControl, BRDescriptionOverlayControl, BRMediaPlayer, BRMediaPlayerEventHandler, BRResumeMenuControl, BRSubtitleControl, BRTextControl, BRTransportControl, NSTimer;

@interface BRMediaPlayerController : BRController
{
    long _state;
    BRControl *_content;
    BRControl *_audioVisualizer;
    BRMediaPlayer *_player;
    BRMediaPlayerEventHandler *_eventHandler;
    BRClosedCaptionControl *_closedCaption;
    BRSubtitleControl *_subtitleControl;
    BRResumeMenuControl *_resumeMenu;
    BRTransportControl *_transport;
    BRDescriptionOverlayControl *_descriptionOverlay;
    BRTextControl *_explanatoryTextControl;
    BRControl *_defaultVisual;
    id _delegate;
    id _transitionAnimationDelegate;
    NSTimer *_suppressBackgroundProcessTimer;
    NSTimer *_explanatoryTextFadeTimer;
    float _lastBufferingProgress;
    unsigned int _startChapterIndex;
    BOOL _drmAttempted;
    BOOL _playbackInitiated;
    BOOL _alwaysStopOnPop;
    BOOL _transportDisabled;
    BOOL _resumeMenuDisabled;
    BOOL _waitingForTransition;
    BOOL _visualsHidden;
    BOOL _inChapterMode;
    BOOL _digitalExtrasMenuItemDisabled;
}

+ (id)controllerForPlayer:(id)arg1;
- (id)initWithPlayer:(id)arg1;
- (void)dealloc;
- (id)player;
- (void)clearPlayer;
- (void)setPlayerDelegate:(id)arg1;
- (id)playerDelegate;
- (void)setResumeMenuDisabled:(BOOL)arg1;
- (BOOL)resumeMenuDisabled;
- (void)setTransportControlDisabled:(BOOL)arg1;
- (BOOL)transportControlDisabled;
- (void)setDefaultVisualControl:(id)arg1;
- (id)defaultVisualControl;
- (void)setDigitalExtrasMenuItemDisabled:(BOOL)arg1;
- (BOOL)digitalExtrasMenuItemDisabled;
- (void)setStartChapterIndex:(unsigned int)arg1;
- (unsigned int)startChapterIndex;
- (void)setAlwaysStopPlaybackWhenPopped:(BOOL)arg1;
- (BOOL)alwaysStopPlaybackWhenPopped;
- (void)setVisualsHidden:(BOOL)arg1;
- (BOOL)visualsHidden;
- (BOOL)canBeScreenSaver;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)wasPopped;
- (BOOL)brEventAction:(id)arg1;
- (void)layoutSubcontrols;
- (BOOL)shouldShowTrackPopup;
- (BOOL)shouldTransitionIn;
- (id)providersForContextMenu;

@end

