/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRImageLoader.h>

@interface BRMediaParadeProvider : BRImageLoader
{
    unsigned int _artworkNeedsDeletterboxing:1;
}

- (id)finalFormForImage:(id)arg1;
- (void)setDeletterboxAssetArtwork:(BOOL)arg1;
- (BOOL)isImageFinalForm:(id)arg1;

@end

