/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerController.h>

@interface BRMediaPlayerController (StateManagement)
- (void)_enterPINEntryState;
- (void)_enterVolumeWarningState;
- (void)_enterResumeMenuState;
- (void)_enterChaptersSubtitlesAndAlternateAudioPickingState;
- (void)_exitChaptersSubtitlesAndAlternateAudioPickingState;
- (void)_enterPlaybackStatePlaying:(BOOL)arg1;
- (void)_enterDRMSyncState;
- (void)_enterErrorStateWithError:(id)arg1;
- (void)_initiatePlayback;
@end

