/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRProvider-Protocol.h"

@class NSMutableArray;

@interface BRMediatorProvider : NSObject <BRProvider>
{
    NSMutableArray *_activeMediators;
    NSMutableArray *_mediators;
}

+ (id)provider;
+ (id)providerWithMediator:(id)arg1;
+ (id)providerWithMediators:(id)arg1;
+ (id)providerWithMediatorArray:(id)arg1;
+ (id)providerWithControl:(id)arg1 identifier:(id)arg2;
+ (id)providerWithControlsAndIdentifiers:(id)arg1;
+ (id)providerWithControls:(id)arg1;
+ (id)providerWithControlArray:(id)arg1;
- (id)initWithMediators:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)mediators;
- (void)addMediator:(id)arg1;
- (void)removeMediator:(id)arg1;
- (void)insertMediator:(id)arg1 after:(id)arg2;
- (void)insertMediator:(id)arg1 before:(id)arg2;
- (id)mediatorWithIdentifier:(id)arg1;
- (id)controlFactory;
- (long)dataCount;
- (id)dataAtIndex:(long)arg1;
- (id)hashForDataAtIndex:(long)arg1;

@end

