/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMetadataLinesLayer.h>

@interface BRMetadataLinesLayer (Private)
- (void)_setLineHeightUsingValues:(id)arg1 andLabels:(id)arg2;
- (id)_visibleMetadataIndexesForHeight:(float)arg1 andValues:(id)arg2;
- (void)_buildLineLayersForValues:(id)arg1 andLabels:(id)arg2 usingIndexes:(id)arg3;
- (void)_layoutLines;
- (float)_widthOfWidestLabel;
@end

