/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerEventHandler.h>

@interface BRMediaPlayerEventHandler (MediaCustomizations)
- (BOOL)_chapteringSupported;
- (void)_setInChapterSkipMode:(BOOL)arg1;
- (BOOL)_chapterSkipSupported;
@end

