/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@interface BRMetadataPopulatorFactory : BRSingleton
{
    id _imagePopulatorForAsset;
    id _imagePopulatorForStoreDictionary;
    id _tvShowPopulator;
    id _podcastPopulator;
    id _musicVideoPopulator;
    id _songPopulator;
    id _moviePopulator;
    id _movieTrailerPopulator;
    id _rssPopulator;
    id _audiobookPopulator;
    id _musicAlbumPopulator;
    id _ytPopulator;
    id _airTunesPopulator;
    id _radioPopulator;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (void)dealloc;
- (id)populatorForAsset:(id)arg1;
- (id)imagePopulatorForAssets;

@end

