/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRNetworkMediaProvider.h>

@class NSMutableArray;

@interface BRMovieTrailersProvider : BRNetworkMediaProvider
{
    NSMutableArray *_mediaCollections;
    int _lastError;
}

+ (void)initialize;
+ (BOOL)trailersAvailable;
- (void)_networkStatusChanged:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)mediaTypes;
- (id)providerID;
- (id)machineID;
- (id)mediaForEntityName:(id)arg1;
- (int)load;
- (int)unload;
- (int)errorCodeForProvider;
- (int)lastError;

@end

