/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BROptionDialog.h>

@interface BRModalOptionDialog : BROptionDialog
{
    long _cancelIdx;
    BOOL _allowMenuButton;
}

- (id)init;
- (id)initAllowingMenuButton:(BOOL)arg1;
- (long)runModal;
- (void)setCancelIndex:(long)arg1;
- (BOOL)brEventAction:(id)arg1;

@end

