/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMusicStore.h>

@interface BRMusicStore (Private)
- (id)_canonicalNameForMediaType:(id)arg1;
- (void)_storeLoadFailed:(id)arg1;
- (void)_bootstrapMusicStore;
- (void)_bootstrapMusicStoreFromURL:(id)arg1;
- (void)_seedMusicStore:(id)arg1;
- (void)_seedRequestProcessed:(id)arg1;
- (BOOL)_seedMusicStoreWithDocument:(id)arg1;
- (BOOL)_initializeMusicStore:(id)arg1;
- (BOOL)_loadRootCollection:(id)arg1;
- (void)_rootCollectionLoaded:(id)arg1;
- (void)_setRootCollection:(id)arg1;
- (void)_retryRootCollection:(id)arg1;
- (void)_initializeGhostrider:(id)arg1;
- (void)_updateStoreFrontFromResponse:(id)arg1;
- (void)_networkStateChanged:(id)arg1;
- (void)_requestStoreFrontList:(id)arg1;
- (void)_storeFrontListRequestProcessed:(id)arg1;
- (id)_defaultStoreFrontsFilePath;
- (id)_currentStoreFrontsFilePath;
- (id)_storeFrontsDictionary;
@end

