/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class NSDictionary;

@interface BRMusicNowPlayingTransportLayer : BRControl
{
    NSDictionary *_textAttributes;
    float _percent;
    float _duration;
    float _elapsedTime;
    float _timeTextWidth;
    float _fillLayerHeight;
    float _fillLayerWidth;
    float _playHeadHeight;
    float _ordinaryTimeTextWidth;
    BOOL _flip;
    BOOL _isRadio;
}

- (id)init;
- (void)dealloc;
- (void)setTextAttributes:(id)arg1;
- (void)setPercentage:(float)arg1;
- (void)setElapsedTime:(float)arg1 andDuration:(float)arg2;
- (void)layoutSubcontrols;
- (void)setFlip:(BOOL)arg1;
- (void)setIsRadio:(BOOL)arg1;

@end

