/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBaseMediaProvider.h>

@interface BRNetworkMediaProvider : BRBaseMediaProvider
{
}

- (int)status;
- (id)objectsWithEntityName:(id)arg1 qualifiedByPredicate:(id)arg2 sortDescriptors:(id)arg3 error:(id *)arg4;
- (id)loadDocumentFromURL:(id)arg1;
- (id)convertData:(id)arg1 fromEncoding:(unsigned int)arg2 toEncoding:(unsigned int)arg3;

@end

