/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@interface BRParentalControlManager : BRSingleton
{
    id _ratingInfoDatabase;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (id)init;
- (void)setAccessControlEnabled:(BOOL)arg1;
- (BOOL)accessControlEnabled;
- (void)setPin:(id)arg1;
- (id)pin;
- (void)setDefaultRatingSystemID:(id)arg1;
- (id)defaultRatingSystemID;
- (void)setRatingDatabase:(id)arg1;
- (id)ratingDatabase;
- (void)clearAccessModeforAppliance:(id)arg1 categoryIdentifier:(id)arg2;
- (void)setAccessMode:(int)arg1 forAppliance:(id)arg2 categoryIdentifier:(id)arg3;
- (int)accessModeForAppliance:(id)arg1 categoryIdentifier:(id)arg2;
- (void)setAccessMode:(int)arg1 forMediaType:(id)arg2 withRatingSystemID:(id)arg3 withThresholdRank:(id)arg4;
- (int)accessModeForMediaType:(id)arg1 withRatingSystemID:(id)arg2 withRank:(id)arg3;
- (void)setAccessModeForPurchase:(int)arg1;
- (int)accessModeForPurchase;
- (void)setExplicitAccessMode:(int)arg1 forMediaType:(id)arg2;
- (int)explicitAccessModeForMediaType:(id)arg1;

@end

