/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

#import "BRTextField-Protocol.h"

@class BRDeviceKeyboardMessage, BRPasscodeSelectionLayer;

@interface BRPasscodeEntryControl : BRControl <BRTextField>
{
    BRPasscodeSelectionLayer *_passcodeLayer;
    unsigned int _numDigits;
    BOOL _isUserEditable;
    struct CGSize _passcodeLayerSize;
    BRDeviceKeyboardMessage *_deviceKeyboardMessage;
    id _textFieldDelegate;
}

- (id)initWithNumDigits:(unsigned int)arg1 userEditable:(BOOL)arg2 hideDigits:(BOOL)arg3;
- (void)dealloc;
- (struct CGSize)preferredSizeFromScreenSize:(struct CGSize)arg1;
- (float)widthOfDigitsFromScreenSize:(struct CGSize)arg1;
- (void)setDelegate:(id)arg1;
- (void)setInitialPasscode:(id)arg1;
- (void)reset;
- (void)shake;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (BOOL)brEventAction:(id)arg1;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (void)setKeyboardTitle:(id)arg1;
- (id)stringValue;
- (void)setString:(id)arg1;

@end

