/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPasscodeSelectionLayer.h>

@interface BRPasscodeSelectionLayer (Building)
- (id)_buildBackgroundLayers;
- (id)_buildDigitLayers;
- (id)_buildBulletLayers;
- (id)_buildArrowsLayer;
- (id)_buildDoneLayer;
@end

