/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRDataStoreProvider.h>

@interface BRPhotoDataStoreProvider : BRDataStoreProvider
{
}

+ (id)providerWithDataStore:(id)arg1 controlFactory:(id)arg2;
- (id)initWithDataStore:(id)arg1 controlFactory:(id)arg2;
- (void)dealloc;
- (void)_updateDataValidity:(id)arg1;

@end

