/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayer.h>

@class BRPhotoMediaCollection, BRPhotoPlayerVisualControl, NSDictionary, NSMutableDictionary, NSString, PhotoConnection;

@interface BRPhotoPlayer : BRMediaPlayer
{
    BRPhotoMediaCollection *_collection;
    BRPhotoPlayerVisualControl *_visuals;
    NSMutableDictionary *_collectionOptions;
    PhotoConnection *_photoConnection;
    int _state;
    BOOL _processingStop;
    BOOL _allowMusicToPlayThrough;
    BOOL _playbackInitiated;
    BOOL _muted;
    long _startIndex;
    struct _opaque_pthread_mutex_t _mutex;
    struct _opaque_pthread_cond_t _condition;
    BOOL _imageRequestPending;
    NSString *_pendingImageID;
    BOOL _ignoreFirstNextCommand;
    NSDictionary *_slideshowPlaybackOptions;
    BOOL _usingInternalMusicPlayback;
    BOOL _shuffleSet;
    BOOL _shuffle;
}

+ (id)contentTypes;
- (id)init;
- (void)dealloc;
- (BOOL)stopsActiveAudioPlayer;
- (BOOL)reverseTouchSwipeBehavior;
- (BOOL)setMediaAtIndex:(long)arg1 inCollection:(id)arg2 error:(id *)arg3;
- (id)collection;
- (id)media;
- (BOOL)setState:(int)arg1 error:(id *)arg2;
- (int)playerState;
- (BOOL)playingVisualContent;
- (id)visuals;
- (void)setMuted:(BOOL)arg1;
- (BOOL)muted;
- (void)setShufflePlayback:(BOOL)arg1;
- (BOOL)shufflePlayback;
- (void)previousMedia;
- (void)nextMedia;
- (BOOL)supportsVolumeControl;
- (void)setVolume:(float)arg1;
- (float)volume;
- (void)setPlayerSpecificOptions:(id)arg1;
- (id)playerSpecificOptions;

@end

