/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPhotoControlFactory.h>

@interface BRPhotoControlFactory (ControlHelpers)
- (id)_menuItemForData:(id)arg1;
- (id)_gridItemForData:(id)arg1;
- (id)_cyclerForData:(id)arg1;
- (id)_cyclerItemForData:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (id)_previewControlForData:(id)arg1;
- (id)_shelfItemForData:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
@end

