/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPhotoPlayer.h>

@interface BRPhotoPlayer (MusicPlayback)
- (void)_startInternalMusicPlayback;
- (void)_stopMusicPlayback;
- (id)_mediaMusicProvider;
- (BOOL)_playMusicShuffled;
- (BOOL)_repeatMusic;
- (id)_currentTrackList;
- (id)_trackListForSongID:(id)arg1 error:(id *)arg2;
- (id)_trackListForPlaylistID:(id)arg1 error:(id *)arg2;
- (id)_trackListForPlaylistName:(id)arg1 error:(id *)arg2;
- (id)_trackListForAllSongs;
- (BOOL)_startPlayingTrackList:(id)arg1 error:(id *)arg2;
@end

