/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPhotoDataStoreProvider.h>

#import "BRPhotoProviderForCollection-Protocol.h"

@interface BRPhotoDataStoreProviderForCollection : BRPhotoDataStoreProvider <BRPhotoProviderForCollection>
{
}

+ (id)providerWithDataStore:(id)arg1 controlFactory:(id)arg2;
- (BOOL)canHaveZeroData;
- (id)collection;

@end

