/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPlaylistsMenuController.h>

@interface BRPlaylistsMenuController (Private)
+ (id)_dataStoreWithMediaTypes:(id)arg1 sortDescriptors:(id)arg2;
- (id)_dataProviderForController:(id)arg1;
- (void)_itemSelected:(id)arg1;
- (void)_pushControllerForPlaylist:(id)arg1;
- (void)_startPlayerWithTrackAtIndex:(long)arg1 tracklist:(id)arg2 shuffle:(BOOL)arg3 list:(id)arg4;
@end

