/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRDataStore.h>

@interface BRPlaylistDataStore : BRDataStore
{
    id _playlist;
}

- (id)initWithPlaylist:(id)arg1 mediaTypes:(id)arg2;
- (void)dealloc;
- (id)playlist;
- (BOOL)storeAppliesToObject:(id)arg1;
- (id)data;
- (void)addObject:(id)arg1;
- (void)objectModified:(id)arg1;
- (void)removeObject:(id)arg1;

@end

