/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRAsyncTask, BRAutoScrollingTextControl, BRImage, BRImageControl, BRTextControl, BRWaitSpinnerControl, NSString, NSTimer;

@interface BRPosterControl : BRControl
{
    int _style;
    int _badgePosition;
    BRTextControl *_subtitleTextControl;
    BRTextControl *_ordinalTextControl;
    BRAutoScrollingTextControl *_autoScrollingTitleControl;
    BRWaitSpinnerControl *_spinnerControl;
    BRImage *_defaultImage;
    BRImage *_badgeImage;
    BRImage *_image;
    BRImage *_tempImage;
    NSTimer *_localFinalFormTimer;
    BRImageControl *_defaultImageControl;
    struct CGColor *_posterBorderColor;
    float _posterBorderWidth;
    BRImage *_posterBorderImage;
    struct CGRect _mainImageRect;
    struct CGRect _focusRect;
    float _reflectionAmount;
    float _reflectionBaseline;
    float _titleWidthScale;
    float _titleVerticalOffset;
    float _cornerRadius;
    float _badgeScale;
    float _badgeOpacity;
    float _badgeFocusedOpacity;
    float _cropAspectRatio;
    BOOL _alwaysShowTitles;
    BOOL _onlyShowSubtitlesWhenFocused;
    BOOL _autoDownsample;
    BOOL _observingBounds;
    BOOL _usingDefaultImage;
    BOOL _imageRequested;
    BOOL _cropAndFill;
    id _imageProxy;
    NSString *_artworkIdentifier;
    BRAsyncTask *_resizeImageTask;
    BOOL _imageLoadSuspended;
    BOOL _badgeAsNowPlayingItem;
    BOOL _deletterboxImage;
}

+ (id)chicletButtonWithImage:(id)arg1;
+ (id)posterButtonWithImage:(id)arg1 title:(id)arg2 badge:(id)arg3;
+ (id)enhancedPosterButtonWithImage:(id)arg1 title:(id)arg2 subtitle:(id)arg3 badge:(id)arg4;
+ (id)twoLinePosterButtonWithImage:(id)arg1 title:(id)arg2 subtitle:(id)arg3 badge:(id)arg4;
+ (id)tilePosterWithImageProxy:(id)arg1 title:(id)arg2 subtitle:(id)arg3;
+ (id)polaroidPosterWithImageProxy:(id)arg1 title:(id)arg2;
+ (Class)layerClass;
- (id)init;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)setDefaultImage:(id)arg1;
- (id)defaultImage;
- (void)setPosterBorderColor:(struct CGColor *)arg1;
- (struct CGColor *)posterBorderColor;
- (void)setPosterBorderWidth:(float)arg1;
- (float)posterBorderWidth;
- (void)setPosterBorderImage:(id)arg1 mainImageRect:(struct CGRect)arg2 focusRect:(struct CGRect)arg3;
- (id)posterBorderImage;
- (struct CGRect)mainImageRect;
- (struct CGRect)focusRect;
- (void)setPosterStyle:(int)arg1;
- (int)posterStyle;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setImageProxy:(id)arg1;
- (id)imageProxy;
- (void)setReflectionAmount:(float)arg1;
- (float)reflectionAmount;
- (void)setReflectionBaseline:(float)arg1;
- (float)reflectionBaseline;
- (void)setOrdinal:(int)arg1;
- (int)ordinal;
- (void)setSpinnerEnabled:(BOOL)arg1;
- (BOOL)spinnerEnabled;
- (void)setCornerRadius:(float)arg1;
- (float)cornerRadius;
- (void)setCropAndFill:(BOOL)arg1;
- (BOOL)cropAndFill;
- (void)setCropAspectRatio:(float)arg1;
- (float)cropAspectRatio;
- (void)setBadgeAsNowPlayingItem:(BOOL)arg1;
- (BOOL)badgeAsNowPlayingItem;
- (void)setBadgeImage:(id)arg1;
- (id)badgeImage;
- (void)setBadgeScale:(float)arg1;
- (float)badgeScale;
- (void)setBadgePosition:(int)arg1;
- (int)badgePosition;
- (void)setBadgeOpacity:(float)arg1;
- (float)badgeOpacity;
- (void)setFocusedBadgeOpacity:(float)arg1;
- (float)focusedBadgeOpacity;
- (void)setTitle:(id)arg1;
- (void)setNonAttributedTitle:(id)arg1;
- (void)setNonAttributedTitleWithCrossfade:(id)arg1;
- (id)title;
- (void)setTitleWidthScale:(float)arg1;
- (float)titleWidthScale;
- (void)setTitleVerticalOffset:(float)arg1;
- (float)titleVerticalOffset;
- (void)setAlwaysShowTitles:(BOOL)arg1;
- (BOOL)alwaysShowTitles;
- (void)setOnlyShowSubtitlesWhenFocused:(BOOL)arg1;
- (BOOL)onlyShowSubtitlesWhenFocused;
- (void)setSubtitle:(id)arg1;
- (void)setNonAttributedSubtitle:(id)arg1;
- (id)subtitle;
- (void)setImage:(id)arg1;
- (id)image;
- (void)setDeletterboxImage:(BOOL)arg1;
- (BOOL)deletterboxImage;
- (struct CGRect)focusCursorFrame;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)layoutSubcontrols;
- (void)scrollingCompleted;
- (float)preferredCursorRadius;

@end

