/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class BRWindow, NSMutableArray;

@interface BRPopUpManager : BRSingleton
{
    NSMutableArray *_queuedPopUps;
    BRWindow *_popUpContainerWindow;
    double _lastUpdate;
}

- (id)init;
- (void)dealloc;
- (void)postPopUpWithControl:(id)arg1 identifier:(id)arg2 position:(unsigned int)arg3 size:(struct CGSize)arg4 options:(id)arg5;
- (void)removePopUpWithIdentifier:(id)arg1;

@end

