/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPosterControlFactory.h>

@interface BRPosterControlFactory (Private)
- (id)_posterForGridFromAsset:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (id)_posterForShelfFromAsset:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (id)_posterFromAsset:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
@end

