/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface BRPreferences : NSObject
{
    NSString *_domain;
}

- (id)initWithDomain:(id)arg1;
- (void)dealloc;
- (id)domain;
- (void)syncNow;
- (id)objectForKey:(id)arg1;
- (int)integerForKey:(id)arg1;
- (int)integerForKey:(id)arg1 withValueForMissingPrefs:(int)arg2;
- (float)floatForKey:(id)arg1;
- (float)floatForKey:(id)arg1 withValueForMissingPrefs:(float)arg2;
- (double)doubleForKey:(id)arg1;
- (BOOL)boolForKey:(id)arg1;
- (BOOL)boolForKey:(id)arg1 withValueForMissingPrefs:(BOOL)arg2;
- (id)stringForKey:(id)arg1;
- (id)descriptionForKey:(id)arg1;
- (BOOL)canSetPreferencesForKey:(id)arg1;
- (BOOL)setInteger:(int)arg1 forKey:(id)arg2;
- (BOOL)setFloat:(float)arg1 forKey:(id)arg2;
- (BOOL)setDouble:(double)arg1 forKey:(id)arg2;
- (BOOL)setBool:(BOOL)arg1 forKey:(id)arg2;
- (BOOL)setObject:(id)arg1 forKey:(id)arg2;

@end

