/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayer.h>

@class BRVideo, BRVideoVisualControl, NSTimer;

@interface BRQTKitVideoPlayer : BRMediaPlayer
{
    BRVideo *_video;
    id _asset;
    BRVideoVisualControl *_visuals;
    id _ccHandler;
    NSTimer *_movieExpirationTimer;
    int _state;
    double _virtualChapterMark;
    double _virtualChapterMarkExpiration;
    id _subtitleHandler;
    int _repeatMode;
    BOOL _waitingOnByteRangeRequest;
    BOOL _disablePlatformFilters;
    BOOL _playbackInitiated;
    BOOL _playheadAdvanced;
    BOOL _gatherStats;
    BOOL _muted;
    float _volume;
}

+ (id)contentTypes;
+ (BOOL)allowMultiplePlayers;
+ (void)setPlatformVideoFilter:(id)arg1;
+ (void)setByteRangeRequester:(id)arg1;
+ (void)setMaxStreamingBufferSize:(long long)arg1;
+ (void)setPlayAllTrackTypes:(BOOL)arg1;
- (id)init;
- (void)dealloc;
- (BOOL)setMediaAtIndex:(long)arg1 inTrackList:(id)arg2 error:(id *)arg3;
- (id)media;
- (BOOL)cueMediaWithError:(id *)arg1;
- (BOOL)setState:(int)arg1 error:(id *)arg2;
- (int)playerState;
- (BOOL)supportsMultipleTrickSpeeds;
- (double)duration;
- (void)setElapsedTime:(double)arg1;
- (double)elapsedTime;
- (void)resetToBeginning;
- (BOOL)hasChapters;
- (id)chapterTimes;
- (void)setVirtualChapterMark:(double)arg1;
- (double)virtualChapterMark;
- (void)nextChapter;
- (void)previousChapter;
- (void)setCurrentChapterIndex:(long)arg1;
- (void)setSubtitleHandler:(id)arg1;
- (id)subtitleHandler;
- (id)localizedSubtitleLanguageSetting;
- (id)localizedListOfSubtitleOptions;
- (void)setSubtitleOptionWithLocalizedSetting:(id)arg1;
- (id)localizedAudioLanguageSetting;
- (id)localizedListOfAudioOptions;
- (void)setAudioOptionWithLocalizedSetting:(id)arg1;
- (long)chapterCount;
- (long)currentChapterIndex;
- (id)currentChapterTitle;
- (id)chapterTitleForIndex:(long)arg1;
- (BOOL)hasRealChapters;
- (BOOL)hasChapterPictures;
- (BOOL)chapterIsPlayable:(long)arg1;
- (id)chapterImageProxyForIndex:(long)arg1;
- (double)startTimeForChapter:(long)arg1;
- (double)endTimeForChapter:(long)arg1;
- (struct BRTimeRange)bufferedRange;
- (float)bufferingProgress;
- (void)setDisablePlatformFilters:(BOOL)arg1;
- (BOOL)disablePlatformFilters;
- (BOOL)playingVisualContent;
- (id)visuals;
- (void)setClosedCaptionHandler:(id)arg1;
- (id)closedCaptionHandler;
- (id)blurredVideoFrame;
- (id)currentVideoFrame;
- (double)keyframeTimeNearTime:(double)arg1 searchForwards:(BOOL)arg2;
- (void)setRepeatMode:(int)arg1;
- (int)repeatMode;
- (void)setMuted:(BOOL)arg1;
- (BOOL)muted;
- (BOOL)supportsVolumeControl;
- (void)setVolume:(float)arg1;
- (float)volume;

@end

