/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRQTKitVideoPlayer.h>

@interface BRQTKitVideoPlayer (MovieNotifications)
- (void)_videoPlayableHandler:(id)arg1;
- (void)_videoLoadedHandler:(id)arg1;
- (void)_videoRateDroppedHandler:(id)arg1;
- (void)_videoPlaybackHitEndHandler:(id)arg1;
- (void)_videoPlaybackHitBeginningHandler:(id)arg1;
- (void)_videoLoadErrorHandler:(id)arg1;
- (void)_postErrorNotificationWithError:(id)arg1;
@end

