/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface BRQTTrackInfo : NSObject
{
    struct TrackType **_track;
    BOOL _isAC3Format;
    NSString *_displayName;
}

+ (id)audioTrackFromTrack:(struct TrackType **)arg1;
- (id)initWithTrack:(struct TrackType **)arg1;
- (void)dealloc;
- (id)description;
- (struct TrackType **)track;
- (long)trackID;
- (BOOL)isAC3Format;
- (id)localizedLanguageName;
- (id)displayName;
- (void)useCombinationDisplayName;
- (id)persistentDescriptor;
- (short)languageCode;
- (void)setEnabled:(BOOL)arg1;
- (BOOL)enabled;

@end

