/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@interface BRReflectionControl : BRControl
{
    float _reflectionAmount;
    float _reflectionOffset;
    BOOL _flipped;
}

- (id)init;
- (void)setImage:(id)arg1;
- (void)setReflectionAmount:(float)arg1;
- (float)reflectionAmount;
- (void)setReflectionOffset:(float)arg1;
- (float)reflectionOffset;
- (void)setFlipped:(BOOL)arg1;
- (BOOL)flipped;

@end

