/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRType.h>

@interface BRResolution : BRType
{
}

+ (void)initialize;
+ (id)SD480i;
+ (id)SD576i;
+ (id)ED480p;
+ (id)ED576p;
+ (id)HD720p;
+ (id)HD1080i;

@end

