/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRRenderPixelFormat : NSObject
{
    struct _CGLPixelFormatObject *_pixFormat;
}

+ (id)doubleBuffered;
+ (id)doubleBufferedWithDisplay:(struct _CGDirectDisplayID *)arg1;
+ (id)formatWithAttributes:(const int *)arg1;
- (id)initWithAttributes:(const int *)arg1;
- (void)dealloc;
- (struct _CGLPixelFormatObject *)CGLPixelFormat;

@end

