/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class BRRenderContext, BRRenderDisplayLink, BRRenderTarget, CARenderer, NSMutableArray;

@interface BRRenderer : BRSingleton
{
    CARenderer *_renderer;
    BRRenderTarget *_target;
    BRRenderContext *_context;
    BRRenderDisplayLink *_link;
    NSMutableArray *_delegates;
    struct BRRendererFrameCountParams _countParams;
    double _lastCAUpdate;
    struct CGRect _previousUpdate;
    struct CGSize _sceneSize;
    BOOL _started;
    BOOL _drawSafeRegions;
    BOOL _drawFrameRate;
    BOOL _dirtyScene;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)startRendering;
- (BOOL)renderingStarted;
- (id)persistentContext;
- (void)addPlaybackDelegate:(id)arg1;
- (void)removePlaybackDelegate:(id)arg1;

@end

