/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRRenderDisplayLink.h>

@interface BRRenderDisplayLink (FakeDisplayLinkThread)
- (void)_stopFakeCVThread;
- (void)_startFakeCVThread;
- (void)_fakeCVTimerFired:(id)arg1;
- (void)_fakeCVEntryPoint;
@end

