/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRReflectionControl.h>

@interface BRReflectionControl (Filter)
- (id)_generateFiltersFrom:(float)arg1 to:(float)arg2;
- (id)_reflectionFilters;
- (id)_unflippedReflectionFilters;
@end

