/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@interface BRRoundRectOutlineLayer : BRControl
{
    struct CGColor *_color;
    float _lineWidth;
    float _cornerRadius;
}

- (id)init;
- (void)dealloc;
- (void)setOutlineColor:(struct CGColor *)arg1;
- (struct CGColor *)outlineColor;
- (void)setLineWidth:(float)arg1;
- (float)lineWidth;
- (void)setCornerRadius:(float)arg1;
- (float)cornerRadius;
- (void)drawInContext:(struct CGContext *)arg1;

@end

