/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRScrollingTextBoxControl.h>

@interface BRScrollingTextBoxControl (Private)
- (void)_listSelectionChanged:(id)arg1;
- (void)_forceSelectionToFocusLimit;
- (void)_calculateFocusLimitsWithTextBoxSize:(struct CGSize)arg1;
- (void)_providerCountChanged:(id)arg1;
@end

