/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRScrollControl.h>

@interface BRScrollControl (EdgeFading)
- (void)_updateEdgeFading;
- (void)_updateVerticalEdgeFading;
- (void)_updateHorizontalEdgeFading;
- (id)_fadeMaskForBounds:(struct CGSize)arg1;
- (void)_attemptToRemoveFadeMask;
- (id)_topFadeFilters;
- (id)_bottomFadeFilters;
- (id)_leftFadeFilters;
- (id)_rightFadeFilters;
@end

