/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRFadeMaskLayer, ScrollAnimationDelegate;

@interface BRScrollControl : BRControl
{
    BRControl *_plane;
    BRControl *_topFade;
    BRControl *_bottomFade;
    BRControl *_leftFade;
    BRControl *_rightFade;
    BRFadeMaskLayer *_mask;
    ScrollAnimationDelegate *_animationDelegate;
    int _scrollDirection;
    int _mode;
    float _edgeFadePercent;
    float _extraBottomSpace;
    float _extraTopSpace;
    float _extraLeftSpace;
    float _extraRightSpace;
    BOOL _scrollPointSet;
    BOOL _constrainAllContentToEdges;
    BOOL _useRealMasks;
    BOOL _followsFocus;
    BOOL _repeatActive;
}

- (id)init;
- (void)dealloc;
- (void)setPlane:(id)arg1;
- (BOOL)brEventAction:(id)arg1;
- (id)plane;
- (BOOL)scrolling;
- (BOOL)autoScrolling;
- (void)setFollowsFocus:(BOOL)arg1;
- (BOOL)followsFocus;
- (void)scrollToPoint:(struct CGPoint)arg1;
- (void)scrollToRect:(struct CGRect)arg1;
- (void)scrollToControl:(id)arg1;
- (void)setUseRealMasks:(BOOL)arg1;
- (BOOL)useRealMasks;
- (void)setEdgeFadePercentage:(float)arg1;
- (float)edgeFadePercentage;
- (void)setConstrainAllContentToEdges:(BOOL)arg1;
- (BOOL)constrainAllContentToEdges;
- (void)setAnimationMode:(int)arg1;
- (int)animationMode;
- (void)setScrollDirection:(int)arg1;
- (int)scrollDirection;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)layoutSubcontrols;

@end

