/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRProvider-Protocol.h"

@class BRTypesetter, NSAttributedString;

@interface BRScrollingTextTextProvider : NSObject <BRProvider>
{
    BRTypesetter *_typesetter;
    NSAttributedString *_string;
    id _factory;
    struct CGSize _boxSize;
}

+ (id)providerWithAttributedString:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)setAttributedString:(id)arg1;
- (id)attributedString;
- (void)setTextBoxSize:(struct CGSize)arg1;
- (id)controlFactory;
- (long)dataCount;
- (id)dataAtIndex:(long)arg1;
- (id)hashForDataAtIndex:(long)arg1;

@end

