/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRScrollingTextControl.h>

@interface BRScrollingTextControl (Private)
- (void)_setSelectedIndexWithControl:(id)arg1;
- (long)_selectedIndex;
- (void)_setDialogIdentifier:(id)arg1;
- (id)_dialogIdentifier;
- (id)_paragraphTextAttributes;
@end

