/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRScrollControl.h>

@interface BRScrollControl (FocusUtilities)
- (void)_updateScrollPositionForFocus;
- (void)_updateFocusNotifications;
- (void)_focusChanged:(id)arg1;
@end

