/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRListControl, BRVerticalScrollBarControl, NSAttributedString;

@interface BRScrollingTextBoxControl : BRControl
{
    BRListControl *_list;
    NSAttributedString *_text;
    BRVerticalScrollBarControl *_scrollBar;
    float _textHeightFactor;
    long _upperFocusLimit;
    long _lowerFocusLimit;
}

- (id)init;
- (void)dealloc;
- (void)setText:(id)arg1;
- (id)text;
- (void)setTextHeightFactor:(float)arg1;
- (float)textHeightFactor;
- (BOOL)brEventAction:(id)arg1;
- (void)layoutSubcontrols;

@end

