/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRDataStore.h>

@class NSSet, NSString;

@interface BRSeriesDataStore : BRDataStore
{
    NSSet *_seriesMediaTypes;
    NSString *_seriesName;
    int _seriesDataStoreType;
}

+ (id)byDateDataStoreWithTypes:(id)arg1;
+ (id)byShowDataStoreWithTypes:(id)arg1 forSeries:(id)arg2;
+ (id)byUnwatchedDataStoreWithTypes:(id)arg1 forSeries:(id)arg2;
+ (id)byMostRecentDataStoreWithTypes:(id)arg1;
+ (id)byUnwatchedByMostRecentDataStoreWithTypes:(id)arg1;
- (void)dealloc;
- (BOOL)storeAppliesToObject:(id)arg1;
- (void)addObject:(id)arg1;
- (void)objectModified:(id)arg1;
- (void)removeObject:(id)arg1;
- (id)data;
- (id)hashForData:(id)arg1;

@end

