/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSegmentedSortControl.h>

@interface BRSegmentedSortControl (Private)
- (id)_leftEndCapTexureForSelectedState:(BOOL)arg1;
- (id)_rightEndCapTexureForSelectedState:(BOOL)arg1;
- (id)_dividerTextureForSelectedState:(BOOL)arg1;
- (id)_contentBackgroundTextureForSelectedState:(BOOL)arg1;
- (id)_attributedTextForSegment:(int)arg1 forSelectedState:(BOOL)arg2;
- (id)_loadImageFromFile:(id)arg1;
- (void)_updateSegmentState;
@end

