/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSeriesProvider.h>

@interface BRSeriesProvider (NotificationHandlers)
- (void)_dataStoreInsertionNotification:(id)arg1;
- (void)_dataStoreModificationNotification:(id)arg1;
- (void)_dataStoreRemovedNotification:(id)arg1;
- (void)_databaseObjectWasAdded:(id)arg1;
@end

