/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class BRIPConfiguration;

@interface BRSettingsFacade : BRSingleton
{
    BRIPConfiguration *_ipConfiguration;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)updateHostID:(id)arg1 to:(id)arg2;
- (void)resetAllSettings;
- (void)refresh;
- (void)flushDiskChanges;
- (id)resolution;
- (BOOL)UISoundsEnabled;
- (void)setUISoundsEnabled:(BOOL)arg1;
- (BOOL)networkActive;
- (BOOL)ethernetIsActive;
- (BOOL)ethernetUsesDHCP;
- (id)ethernetMACaddress;
- (id)ethernetIPaddress;
- (id)ethernetSubnetMask;
- (id)ethernetRouterAddress;
- (id)ethernetDNSAddress;
- (BOOL)airportIsActive;
- (BOOL)airportUsesDHCP;
- (id)airportMACaddress;
- (id)airportIPaddress;
- (id)airportSubnetMask;
- (id)airportRouterAddress;
- (id)airportDNSAddress;
- (long)airportSignalQuality;
- (id)airportNetworkName;
- (int)videoClosedCaptionMode;
- (void)setVideoClosedCaptionMode:(int)arg1;
- (id)localizedDefaultSubtitleLanguageSetting;
- (id)localizedListOfDefaultSubtitleOptions;
- (void)setDefaultSubtitleLanguageOptionWithLocalizedSetting:(id)arg1;
- (id)localizedDefaultAudioLanguageSetting;
- (id)localizedListOfDefaultAudioOptions;
- (void)setDefaultAudioLanguageOptionWithLocalizedSetting:(id)arg1;
- (id)localizedNameForLanguageCode:(short)arg1;
- (long)preferredSubtitleTrackIDForMedia:(id)arg1;
- (void)savePreferredSubtitleTrackID:(long)arg1 forMedia:(id)arg2;
- (long)preferredAlternateAudioTrackIDForMedia:(id)arg1;
- (void)savePreferredAlternateAudioTrackID:(long)arg1 forMedia:(id)arg2;
- (short)videoDefaultSubtitleLanguageCode;
- (void)setVideoSubtitleLanguage:(short)arg1;
- (short)videoDefaultAudioLanguageCode;
- (void)setDefaultVideoAudioLanguage:(short)arg1;
- (int)musicRepeatMode;
- (void)setMusicRepeatMode:(int)arg1;
- (BOOL)musicVolumeControlEnabled;
- (void)setMusicVolumeControlEnabled:(BOOL)arg1;
- (float)musicVolume;
- (void)saveMusicVolume:(float)arg1;
- (int)audioFormat;
- (void)setAudioFormat:(int)arg1;
- (BOOL)playlistsEverywhereEnabled;
- (void)setPlaylistsEverywhereEnabled:(BOOL)arg1;
- (BOOL)screenSaverEnabled;
- (void)setScreenSaverEnabled:(BOOL)arg1;
- (BOOL)screenSaverAllowedOverMusic;
- (void)setScreenSaverAllowedOverMusic:(BOOL)arg1;
- (id)parentalControlsPasscode;
- (int)parentalControlsYTMode;
- (int)slideshowSecondsPerSlide;
- (void)setSlideshowSecondsPerSlide:(int)arg1;
- (BOOL)slideshowRepeat;
- (void)setSlideshowRepeat:(BOOL)arg1;
- (BOOL)slideshowShufflePhotos;
- (void)setSlideshowShufflePhotos:(BOOL)arg1;
- (BOOL)slideshowShuffleMusic;
- (void)setSlideshowShuffleMusic:(BOOL)arg1;
- (BOOL)slideshowPanAndZoom;
- (void)setSlideshowPanAndZoom:(BOOL)arg1;
- (BOOL)slideshowPlayMusic;
- (void)setSlideshowPlayMusic:(BOOL)arg1;
- (id)slideshowPlaylists;
- (id)slideshowSelectedPlaylistName;
- (void)setSlideshowSelectedPlaylistName:(id)arg1;
- (id)slideshowTransitionNames;
- (id)slideshowSelectedTransitionName;
- (void)setSlideshowSelectedTransitionName:(id)arg1;
- (id)slideshowTransitionDirection;
- (void)setSlideshowTransitionDirection:(id)arg1;
- (BOOL)slideshowTransitionsDisabled;
- (BOOL)slideshowTransitionsRandom;
- (id)slideshowPlaybackOptions;
- (id)keyboardLanguageKeys;
- (void)setKeyboardLanguageKeys:(id)arg1;
- (BOOL)keyboardLanguageEnabled:(id)arg1;
- (void)setKeyboardLanguageEnabled:(id)arg1 enabled:(BOOL)arg2;
- (id)lastUsedKeyboardLanguage;
- (void)setLastUsedKeyboardLanguage:(id)arg1;
- (id)versionSoftware;
- (id)versionBuild;
- (BOOL)volumeEnabled;
- (float)systemVolume;
- (void)setSystemVolume:(float)arg1;
- (id)_ipConfig;
- (BOOL)syncIsSynced;
- (id)syncHostName;
- (BOOL)syncControlDisabled;
- (id)hwDeviceName;
- (BOOL)bootedFromRecoveryPartition;
- (BOOL)saveConfiguration:(id)arg1;

@end

