/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRControlFactory-Protocol.h"
#import "BRControlHeightFactory-Protocol.h"

@interface BRSeriesControlFactory : NSObject <BRControlFactory, BRControlHeightFactory>
{
    int _controlType;
    float _textImageMenuItemLayerHeight;
    float _dividerHeight;
    BOOL _hidePartialPlayedImages;
    id _selectionHandler;
}

+ (id)factoryForControlType:(int)arg1 hidePartialPlayedImages:(BOOL)arg2;
- (id)initFactoryForControlType:(int)arg1 hidePartialPlayedImages:(BOOL)arg2;
- (void)dealloc;
- (void)setSelectionHandler:(id)arg1;
- (id)selectionHandler;
- (id)controlForData:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (float)heightForControlForData:(id)arg1 requestedBy:(id)arg2;

@end

