/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageControl;

@interface BRShimmerControl : BRControl
{
    BRControl *_base;
    BRImageControl *_shimmer;
    float _offset;
}

+ (id)shimmerWithOffset:(float)arg1;
- (id)initWithOffset:(float)arg1;
- (id)init;
- (void)setOffset:(float)arg1;
- (float)offset;
- (void)dealloc;
- (void)layoutSubcontrols;

@end

