/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class NSTimer;

@interface BRSoundHandler : BRSingleton
{
    BOOL _isSoundEnabled;
    unsigned int _soundIDs[23];
    NSTimer *_SSSWatchdogTimer;
    unsigned int _queuedSSSCommandID;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
+ (void)playSound:(int)arg1;
+ (void)reloadSoundPreference;
+ (void)activateSoundgraph;
+ (void)deactivateSoundgraph;
- (id)init;
- (void)dealloc;

@end

