/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@interface BRSpacerControl : BRControl
{
}

+ (id)spacerWithScale:(float)arg1 relativeTo:(int)arg2;
- (id)initWithScale:(float)arg1 relativeTo:(int)arg2;

@end

