/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageControl, BRStatusAlertControlDelegate;

@interface BRStatusAlertControl : BRControl
{
    BRStatusAlertControlDelegate *_animationDelegate;
    BRImageControl *_background;
    BRImageControl *_overlay;
    int _fadeHalfCount;
}

+ (id)alertWithType:(int)arg1;
+ (void)postStatusAlertOfType:(id)arg1;
- (void)dealloc;
- (void)layoutSubcontrols;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;

@end

