/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSyncingMediaHost.h>

@class NSDate;

@interface BRStreamingMediaHost : BRSyncingMediaHost
{
    NSDate *_lastAccessedDate;
}

+ (id)streamingMediaHostWithHostInfo:(id)arg1;
- (id)init;
- (void)dealloc;

@end

