/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BRSubtitleHandler <NSObject>
- (void)displaySubtitle:(id)arg1;
- (void)eraseSubtitle;
- (void)setScalingFactor:(float)arg1;
@end

