/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRProvider-Protocol.h"

@class NSMutableArray;

@interface BRSubsetProvider : NSObject <BRProvider>
{
    id _provider;
    int _dataLimit;
    NSMutableArray *_data;
    NSMutableArray *_dataHashes;
}

+ (id)providerWithProvider:(id)arg1;
+ (id)providerWithProvider:(id)arg1 dataLimit:(int)arg2;
- (id)initWithProvider:(id)arg1 dataLimit:(int)arg2;
- (void)dealloc;
- (id)controlFactory;
- (long)dataCount;
- (id)dataAtIndex:(long)arg1;
- (id)hashForDataAtIndex:(long)arg1;
- (void)setDataLimit:(int)arg1;
- (int)dataLimit;

@end

