/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRProgressBarWidget, BRTextControl, NSString;

@interface BRSyncProgressControl : BRControl
{
    BRProgressBarWidget *_progressBar;
    BRTextControl *_sourceText;
    BRTextControl *_currentAssetText;
    NSString *_currentAssetTextFormat;
    unsigned int _numAssets;
}

- (id)initWithSourceName:(id)arg1 notification:(id)arg2;
- (void)dealloc;
- (void)setCurrentAssetName:(id)arg1 num:(unsigned int)arg2;
- (void)setPercentage:(float)arg1;
- (void)layoutSubcontrols;
- (void)_updateProgress:(id)arg1;

@end

