/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class NSArray, NSDictionary;

@interface BRTabControl : BRControl
{
    int _selectedTabIndex;
    float _scaledTextPadding;
    float _scaledPreferredHeight;
    int _tabBeingDeselected;
    id _tabControlDelegate;
    NSArray *_greyImages;
    NSArray *_blackImages;
    NSArray *_blueImages;
    NSDictionary *_tabItemLabelAttributes;
}

+ (id)fullSizeTabControl;
+ (id)menuTabControl;
- (id)init;
- (void)dealloc;
- (void)setScaledTextPadding:(float)arg1;
- (void)setScaledPreferredHeight:(float)arg1;
- (void)setTabItemLabelAttributes:(id)arg1;
- (id)tabControlDelegate;
- (void)setTabControlDelegate:(id)arg1;
- (void)addTabItem:(id)arg1;
- (void)addTabItems:(id)arg1;
- (void)insertTabItem:(id)arg1 atIndex:(int)arg2;
- (void)removeAllTabItems;
- (void)removeTabItem:(id)arg1;
- (int)tabItemCount;
- (id)selectedTabItem;
- (int)selectedTabItemIndex;
- (void)selectTabItem:(id)arg1;
- (void)selectTabItemAtIndex:(int)arg1;
- (void)selectPreviousTabItem;
- (void)selectNextTabItem;
- (id)focusedControlForEvent:(id)arg1 focusPoint:(struct CGPoint *)arg2;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (struct CGSize)preferredFrameSize;
- (void)_loadTabImages;
- (void)setTabItemSelectedInFocusImages:(id)arg1;
- (void)setTabItemSelectedNonFocusedImages:(id)arg1;
- (void)setTabItemNonSelectedImages:(id)arg1;
- (id)_leftTabImagesFromImages:(id)arg1;
- (id)_centerTabImagesFromImages:(id)arg1;
- (id)_rightTabImagesFromImages:(id)arg1;
- (id)_imagesForTabItem:(id)arg1;
- (void)_updateTabItemNames:(int)arg1;
- (void)_updateFocusNotifications;
- (void)_focusChanged:(id)arg1;

@end

