/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

#import "BRTextField-Protocol.h"

@class BRMarqueeTextControl, NSDictionary, NSMutableString;

@interface BRTextFieldControl : BRControl <BRTextField>
{
    id _delegate;
    id _characterDelegate;
    BRMarqueeTextControl *_displayString;
    NSMutableString *_clearString;
    NSDictionary *_savedAttributes;
    BOOL _useSecureText;
    BOOL _showCursor;
}

- (id)init;
- (void)dealloc;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (id)characterDelegate;
- (void)setCharacterDelegate:(id)arg1;
- (BOOL)showCursor;
- (void)setShowCursor:(BOOL)arg1;
- (BOOL)useSecureText;
- (void)setUseSecureText:(BOOL)arg1;
- (id)textAttributes;
- (void)setTextAttributes:(id)arg1;
- (void)setDisplayString:(id)arg1;
- (void)setClearString:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (BOOL)needsScrollingInBounds:(struct CGRect)arg1;
- (float)maxScrollPosition;
- (void)setScrollPosition:(float)arg1;
- (id)stringValue;
- (void)setString:(id)arg1;
- (BOOL)brEventAction:(id)arg1;
- (BOOL)brKeyEvent:(id)arg1;

@end

