/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRTextEntryControl.h>

@interface BRTextEntryControl (DeviceKeyboard)
- (void)deviceKeyboardClose;
- (void)deviceKeyboardUpdate:(BOOL)arg1;
- (void)deviceKeyboardMessageHandler:(id)arg1;
@end

