/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRTextControl.h>

@interface BRTextControl (Shrinkage)
- (void)_shrinkTextToFitInBounds:(struct CGSize)arg1;
- (void)_shrinkTextToTwoLines:(struct CGSize)arg1;
@end

