/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRAsyncImageControl, BRImageControl, BRMarqueeTextControl, BRTextControl, BRWaitSpinnerControl, NSDictionary, NSMutableArray, NSString;

@interface BRTextImageMenuItemLayer : BRControl
{
    BRControl *_background;
    BRImageControl *_thumbnailLayer;
    BRAsyncImageControl *_asyncImageControl;
    id _displayInfoLoader;
    BRMarqueeTextControl *_titleLayer;
    BRImageControl *_titleImageLayer;
    BRTextControl *_subtitleLayer;
    BRTextControl *_rightTextLayer;
    BRImageControl *_rightArrowLayer;
    BRImageControl *_leftImageLayer;
    NSDictionary *_leftImageIconInfo;
    NSMutableArray *_rightImageIconInfos;
    NSString *_thumbnailIdentifier;
    BRWaitSpinnerControl *_spinner;
    NSDictionary *_postTitleIconInfo;
    BRImageControl *_postTitleImageControl;
    float _thumbnailLayerAspect;
    BOOL _cropsThumbnailToSquare;
    BOOL _highlighted;
    BOOL _twoLine;
    BOOL _loadsThumbnails;
    BOOL _dimmed;
    BOOL _rightTextLeavesSpaceForFolderImage;
    BOOL _rightTextAlignsToBottom;
    int _playState;
}

+ (id)menuItem;
+ (id)folderMenuItem;
+ (id)twoLineMenuItem;
+ (id)twoLineFolderMenuItem;
- (id)init;
- (void)dealloc;
- (struct CGSize)preferredFrameSize;
- (void)setMenuItemBackgroundColor:(struct CGColor *)arg1;
- (void)setTitle:(id)arg1;
- (id)title;
- (void)setPostTitleImageInfo:(id)arg1;
- (void)setTitleImage:(id)arg1;
- (void)setSubtitle:(id)arg1;
- (id)subtitle;
- (void)setRightText:(id)arg1;
- (void)setRightTextLeavesSpaceForFolderImage:(BOOL)arg1;
- (BOOL)rightTextLeavesSpaceForFolderImage;
- (void)setRightTextAlignsToBottom:(BOOL)arg1;
- (BOOL)rightTextAlignsToBottom;
- (void)setLeftImageIconInfo:(id)arg1;
- (void)addRightImageIconInfo:(id)arg1;
- (void)setThumbnailImage:(id)arg1;
- (void)setThumbnailImageProxy:(id)arg1;
- (void)setDisplayInfoLoader:(id)arg1;
- (id)displayInfoLoader;
- (void)loadDisplayInfo;
- (void)cancelLoadDisplayInfo;
- (void)setThumbnailIdentifier:(id)arg1;
- (id)thumbnailIdentifier;
- (void)setThumbnailLayerAspectRatio:(float)arg1;
- (float)thumbnailLayerAspectRatio;
- (void)setCropsThumbnailToSquare:(BOOL)arg1;
- (BOOL)cropsThumbnailToSquare;
- (void)setLoadsThumbnails:(BOOL)arg1;
- (BOOL)loadsThumbnails;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (void)setWaitSpinnerActive:(BOOL)arg1;
- (BOOL)waitSpinnerActive;
- (void)setDimmed:(BOOL)arg1;
- (BOOL)dimmed;
- (void)setHDBadge:(BOOL)arg1;
- (void)setPlayState:(int)arg1;
- (int)playState;
- (id)axSelectedItemText;
- (struct CGRect)focusCursorFrame;
- (void)layoutSubcontrols;

@end

