/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageControl, NSArray;

@interface BRTrackInfoLayer : BRControl
{
    BRControl *_background;
    BRImageControl *_art;
    NSArray *_lines;
    float _maxLength;
    long _maxLines;
}

- (id)init;
- (void)dealloc;
- (void)setLines:(id)arg1 withImage:(id)arg2;
- (void)setImage:(id)arg1;
- (void)setMaxLines:(long)arg1;
- (void)layoutSubcontrols;

@end

