/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRTrackInfoControl.h>

@interface BRTrackInfoControl (Notifications)
- (void)_playerStateChanged:(id)arg1;
- (void)_playbackAssetChanged:(id)arg1;
- (void)_updateCoverArt:(id)arg1;
@end

