/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBaseParserDelegate.h>

@class BRMovieTrailer, BRMovieTrailersProvider, BRResolution, NSMutableArray, NSXMLParser;

@interface BRTrailerDelegate : BRBaseParserDelegate
{
    BRMovieTrailersProvider *_provider;
    BRMovieTrailer *_movieTrailer;
    NSMutableArray *_elementCollection;
    BRResolution *_resolution;
    NSXMLParser *_parser;
}

- (id)initWithMediaProvider:(id)arg1 resolution:(id)arg2;
- (void)dealloc;
- (void)setWeakReferenceToParser:(id)arg1;
- (void)startMovieinfoWithAttributes:(id)arg1;
- (void)endMovieinfo;
- (void)endTitle;
- (void)endRuntime;
- (void)endRating;
- (void)endStudio;
- (void)endPostdate;
- (void)endReleasedate;
- (void)endCopyright;
- (void)endDirector;
- (void)endDescription;
- (void)endName;
- (void)startCastWithAttributes:(id)arg1;
- (void)endCast;
- (void)startGenreWithAttributes:(id)arg1;
- (void)endGenre;
- (void)endLocation;
- (void)endXlarge;
- (void)endPoster;
- (void)endLarge;

@end

