/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRTransportLayer.h>

@interface BRTransportLayer (Framing)
- (void)_updateStaticFrames;
- (void)_updateDynamicFrames;
- (void)_drawChapterMarkersInContext:(struct CGContext *)arg1;
@end

