/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRAsyncTaskContext, NSMutableArray;

@interface BRURLDocumentManager : NSObject
{
    NSMutableArray *_activeDocuments;
    NSMutableArray *_queue;
    BRAsyncTaskContext *_taskContext;
}

+ (void)initialize;
+ (id)textDocumentManager;
- (id)init;
- (void)dealloc;
- (void)purgeDocuments;
- (void)loadDocument:(id)arg1;
- (void)cancelLoad:(id)arg1;

@end

