/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRURLDocumentManager.h>

@interface BRURLDocumentManager (private)
- (void)_processLoadDocument:(id)arg1;
- (void)_removeActiveDocument:(id)arg1;
@end

