/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRURLDocument.h>

@interface BRURLDocument (Private)
- (void)_setManager:(id)arg1;
- (id)_manager;
- (void)_cancel;
- (void)_setConnection:(id)arg1;
- (void)_threadDeath:(id)arg1;
- (void)_setDocumentNumber:(unsigned int)arg1;
- (unsigned int)_documentNumber;
- (void)_setRequestDate:(id)arg1;
@end

