/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRImageProxy-Protocol.h"

@class BRMediaType, NSDictionary, NSString, NSURL;

@interface BRURLImageProxy : NSObject <BRImageProxy>
{
    NSString *_imageID;
    NSURL *_url;
    NSDictionary *_headerFields;
    BOOL _encryptedImage;
    BRMediaType *_mediaTypeForDefaultImage;
}

+ (id)proxyWithURL:(id)arg1;
+ (id)proxyWithURL:(id)arg1 encrypted:(BOOL)arg2;
+ (id)proxyWithURL:(id)arg1 headerFields:(id)arg2 encrypted:(BOOL)arg3;
- (id)initWithURL:(id)arg1;
- (id)initWithURL:(id)arg1 encrypted:(BOOL)arg2;
- (id)initWithURL:(id)arg1 headerFields:(id)arg2 encrypted:(BOOL)arg3;
- (void)dealloc;
- (id)imageIDForImageSize:(int)arg1;
- (id)imageForImageSize:(int)arg1;
- (void)setMediaTypeForDefaultImage:(id)arg1;
- (id)mediaTypeForDefaultImage;
- (id)defaultImageForImageSize:(int)arg1;
- (BOOL)supportsImageForImageSize:(int)arg1;
- (void)cancelImageRequestsForImageSizes:(int)arg1;
- (void)setObject:(id)arg1;
- (id)object;
- (id)url;
- (id)headerFields;
- (BOOL)encrypted;

@end

