/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRURLDocumentManager, NSDate, NSError, NSMutableData, NSMutableDictionary, NSThread, NSURLConnection, NSURLRequest, NSURLResponse;

@interface BRURLDocument : NSObject
{
    NSURLRequest *_request;
    NSURLResponse *_response;
    NSError *_error;
    NSMutableData *_content;
    BRURLDocumentManager *_manager;
    NSURLConnection *_connection;
    NSThread *_callingThread;
    NSMutableDictionary *_metadata;
    unsigned int _documentNumber;
    NSDate *_requestDate;
    NSDate *_loadedDate;
    BOOL _wasRedirected;
}

+ (id)documentWithURLRequest:(id)arg1;
- (id)initWithURLRequest:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)URLRequest;
- (id)URLResponse;
- (id)error;
- (id)content;
- (void)documentLoaded;
- (void)setMetadata:(id)arg1 forKey:(id)arg2;
- (id)metadataForKey:(id)arg1;
- (id)requestDate;
- (id)loadedDate;
- (BOOL)wasRedirected;

@end

