/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRVideoLoadMonitor.h>

@class NSTimer;

@interface BRVideoStandardLoadMonitor : BRVideoLoadMonitor
{
    int _state;
    NSTimer *_loadPoll;
    CDAnonymousStruct1 _loadTarget;
    CDAnonymousStruct1 _loadStart;
    BOOL _startsOnPlayable;
    BOOL _disableQTWorkaround;
    BOOL _playable;
}

- (id)initWithMovie:(struct MovieType **)arg1;
- (void)dealloc;
- (void)setStartsOnPlayable:(BOOL)arg1;
- (void)stopMonitoring;
- (BOOL)moviePlayable;
- (float)bufferingProgress;
- (struct BRTimeRange)bufferedRange;
- (double)maxMovieTime;
- (void)playheadHitMax;
- (void)playheadMoved;

@end

