/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRQTTrackInfo, BRVideoLoadMonitor, NSArray, NSMutableArray;

@interface BRVideo : NSObject
{
    struct OpaqueQTVisualContext *_textureContext;
    struct __CVBuffer *_currentFrame;
    BRVideoLoadMonitor *_loadMonitor;
    struct CGSize _contextSizeHint;
    id _media;
    id _filter;
    id _ccHandler;
    id _subtitleHandler;
    float _rate;
    struct ComponentInstanceRecord *_controller;
    struct TrackType **_movieTrack;
    struct TrackType **_chapterPictureTrack;
    struct MovieType **_movie;
    NSArray *_chapters;
    double _prevScanTime;
    double _scanPosition;
    double _movieDuration;
    double _lastMovieTime;
    double _startTime;
    double _stopTime;
    long _cachedChapterIndex;
    int _captionMode;
    short _defaultSubtitleLanguage;
    short _defaultAudioLanguage;
    long _preferredSubtitleTrackID;
    long _preferredAudioTrackID;
    NSMutableArray *_subtitleTracks;
    BRQTTrackInfo *_enabledSubtitleTrack;
    NSMutableArray *_audioTracks;
    BRQTTrackInfo *_enabledAudioTrack;
    struct BRVideoPlaybackStats _stats;
    BOOL _hdcpRequried;
    BOOL _realChapters;
    BOOL _logStalls;
    BOOL _gatherStats;
    BOOL _loops;
    BOOL _muted;
    BOOL _allowAllTrackTypes;
    BOOL _subtitlesEnabled;
    BOOL _expiryDateHasBeenSet;
}

- (id)init;
- (id)initWithMedia:(id)arg1 allowAllTrackTypes:(BOOL)arg2 filter:(id)arg3 error:(id *)arg4;
- (id)media;
- (void)cleanupMovieResources;
- (void)dealloc;
- (void)setPlaybackContext:(id)arg1;
- (void)skip:(double)arg1;
- (void)setElapsedTime:(double)arg1;
- (double)elapsedTime;
- (double)duration;
- (float)aspectRatio;
- (float)bufferingProgress;
- (struct BRTimeRange)bufferedRange;
- (BOOL)videoPlayable;
- (void)gotoBeginning;
- (BOOL)newFrameForTime:(const CDAnonymousStruct2 *)arg1 frame:(struct __CVBuffer **)arg2;
- (struct __CVBuffer *)currentFrame;
- (void)setContextSize:(struct CGSize)arg1;
- (void)setMuted:(BOOL)arg1;
- (BOOL)muted;
- (void)setAudioGain:(float)arg1;
- (float)audioGain;
- (BOOL)isCurrentAudioTrackAC3;
- (void)setLoops:(BOOL)arg1;
- (BOOL)loops;
- (void)setSubtitleHandler:(id)arg1;
- (id)subtitleHandler;
- (id)localizedSubtitleLanguageSetting;
- (id)localizedListOfSubtitleOptions;
- (void)setSubtitleOptionWithLocalizedSetting:(id)arg1;
- (id)localizedAudioLanguageSetting;
- (id)localizedListOfAudioOptions;
- (void)setAudioOptionWithLocalizedSetting:(id)arg1;
- (void)setRate:(float)arg1;
- (float)rate;
- (long)chapterCount;
- (id)chapterList;
- (long)currentChapterIndex;
- (id)currentChapterTitle;
- (id)chapterTitleForIndex:(long)arg1;
- (BOOL)hasRealChapters;
- (BOOL)hasChapterPictures;
- (id)chapterImageProxyForIndex:(long)arg1;
- (double)startTimeForChapter:(long)arg1;
- (double)endTimeForChapter:(long)arg1;
- (id)chapterImageForIndex:(long)arg1;
- (BOOL)chapterIsPlayable:(long)arg1;
- (void)setCurrentChapterIndex:(long)arg1;
- (void)taskVideo;
- (void)setGatherPlaybackStats:(BOOL)arg1;
- (struct BRVideoPlaybackStats)playbackStats;
- (void)setClosedCaptionHandler:(id)arg1;
- (id)closedCaptionHandler;
- (double)keyframeTimeNearTime:(double)arg1 searchForwards:(BOOL)arg2;
- (BOOL)contentProtectionCompliant;

@end

