/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRVideo, BRVideoHardwarePostprocessor;

@interface BRVideoVisualControl : BRControl
{
    BRVideo *_video;
    unsigned long long _currentFrameTime;
    struct __CVBuffer *_currentFrame;
    BRVideoHardwarePostprocessor *_postProcessor;
    BRControl *_warning;
    float _aspectRatio;
}

- (id)init;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)layoutSubcontrols;
- (void)setVideo:(id)arg1;
- (id)video;
- (id)blurredVideoFrame;
- (id)currentVideoFrame;

@end

