/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRVideoHardwarePostprocessor.h>

@interface BRVideoHardwarePostprocessor (ColorSync)
- (void)_updateColorSyncDataForFrame:(struct __CVBuffer *)arg1;
@end

