/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRVideo.h>

@interface BRVideo (Subtitles)
- (id)_subtitleTracks;
- (void)_calculateSubtitleTracks;
- (void)_updateSubtitles;
- (void)_setSubtitlesEnabled:(BOOL)arg1;
- (id)_enabledSubtitleTrack;
- (void)_setEnabledSubtitleTrack:(id)arg1;
- (void)_newSubtitle:(id)arg1;
@end

