/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRVideo.h>

@interface BRVideo (Chaptering)
- (void)_updateChapters;
- (void)_generateFakeChapters;
- (long)_searchForChapterAtTime:(double)arg1;
@end

