/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class NSMutableArray, NSTimer;

@interface BRVideoTasker : BRSingleton
{
    NSMutableArray *_videos;
    NSTimer *_idleTimer;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (void)addVideo:(id)arg1;
- (void)removeVideo:(id)arg1;

@end

