/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRVideoStandardLoadMonitor.h>

@interface BRVideoStandardLoadMonitor (StateMachine)
- (void)_handleWaitingToStartStateAction:(int)arg1;
- (void)_handleBufferingStateAction:(int)arg1;
- (void)_handlePlayableStateAction:(int)arg1;
- (void)_handleAction:(int)arg1;
@end

