/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRVideoVisualControl.h>

#import "BROpenGLPlaybackDelegate-Protocol.h"

@interface BRVideoVisualControl (PlaybackDelegate) <BROpenGLPlaybackDelegate>
- (BOOL)newFrameForTime:(const CDAnonymousStruct2 *)arg1;
- (void)drawFrameInBounds:(struct CGSize)arg1;
- (void)layoutSubcontrols;
@end

