/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRProvider-Protocol.h"

@class BRMediaPlayer, NSTimer;

@interface BRVideoChapterProvider : NSObject <BRProvider>
{
    BRMediaPlayer *_player;
    struct _NSRange _invalidTitlesRange;
    NSTimer *_checkForChapterTitleUpdateTimer;
}

- (id)initWithPlayer:(id)arg1;
- (void)dealloc;
- (id)controlFactory;
- (long)dataCount;
- (id)dataAtIndex:(long)arg1;
- (id)hashForDataAtIndex:(long)arg1;
- (void)stopMonitoring;

@end

