/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageControl, BRPercentageIndicatorLayer;

@interface BRVolumeControl : BRControl
{
    BRImageControl *_speakerOnLayer;
    BRImageControl *_speakerOffLayer;
    BRPercentageIndicatorLayer *_percentageIndicatorLayer;
}

- (id)init;
- (void)dealloc;
- (void)layoutSubcontrols;
- (void)setVolume:(float)arg1;
- (float)volume;

@end

