/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class NSArray;

@interface BRWaitSpinnerControl : BRControl
{
    NSArray *_spinnerImages;
    BOOL _spins;
}

- (id)init;
- (void)dealloc;
- (void)setSpins:(BOOL)arg1;
- (BOOL)spins;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (struct CGSize)preferredSize;

@end

