/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWebMediaElementProxy.h>

@interface BRWebMediaElementProxy (ProxyInterface)
- (int)_interfaceVersion;
- (void)_disconnect;
- (void)_load:(id)arg1 isVideo:(BOOL)arg2;
- (void)_cancelLoad;
- (void)_setPoster:(id)arg1;
- (void)_play;
- (void)_pause;
- (struct _NSSize)_naturalSize;
- (BOOL)_hasVideo;
- (BOOL)_hasAudio;
- (double)_duration;
- (double)_currentTime;
- (void)_setCurrentTime:(double)arg1;
- (BOOL)_seeking;
- (void)_setEndTime:(double)arg1;
- (float)_rate;
- (void)_setRate:(float)arg1;
- (float)_volume;
- (void)_setVolume:(float)arg1;
- (BOOL)_muted;
- (void)_setMuted:(BOOL)arg1;
- (float)_maxTimeBuffered;
- (float)_maxTimeSeekable;
- (id)_bufferedTimeRanges;
- (int)_dataRate;
- (BOOL)_totalBytesKnown;
- (unsigned int)_totalBytes;
- (unsigned int)_bytesLoaded;
- (id)_mimeTypes;
@end

