/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWebFormHelper.h>

@interface BRWebFormHelper (WebFormDelegates)
- (void)formElementDidFocus:(id)arg1 inFrame:(id)arg2;
- (void)formElementDidBlur:(id)arg1 inFrame:(id)arg2;
@end

