/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWebControl.h>

@interface BRWebControl (Messaging)
- (void)webView:(id)arg1 didReceiveMessage:(id)arg2;
- (void)setAllowsMessaging:(BOOL)arg1;
- (BOOL)allowsMessaging;
- (id)messagesMatchingMask:(int)arg1;
- (void)clearMessagesMatchingMask:(int)arg1;
@end

