/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWebControl.h>

@interface BRWebControl (LayoutHelpers)
- (void)_setLayoutComplete:(BOOL)arg1;
- (void)_updateControls;
- (struct CGPoint)_scrollPoint;
- (void)_scrollToPointOnPage:(struct CGPoint)arg1;
- (void)_scrollToRectOnPage:(struct CGRect)arg1;
- (struct CGRect)_safeContentRect;
- (struct CGSize)_minimumPageSize;
@end

