/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWebControl.h>

@interface BRWebControl (FocusHelpers)
- (BOOL)_handleFocusEvent:(id)arg1;
- (id)_newFocusForEvent:(id)arg1;
- (BOOL)_clickOnFocusedElement:(BOOL)arg1;
- (struct CGPoint)_mousePointForElement:(id)arg1;
- (void)_updateDefaultFocus;
@end

