/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBaseMediaAsset.h>

@class NSMutableDictionary;

@interface BRXMLMediaAsset : BRBaseMediaAsset
{
    NSMutableDictionary *_info;
}

- (id)init;
- (id)initWithMediaProvider:(id)arg1;
- (void)dealloc;
- (id)imageProxy;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)resolution;
- (id)assetID;
- (id)artist;
- (id)primaryCollectionTitle;
- (id)mediaSummary;
- (id)copyright;
- (id)thumbnailURL;
- (id)previewURL;
- (id)mediaURL;
- (id)title;
- (id)publisher;
- (id)datePublished;
- (id)dateAcquired;
- (id)dateCreated;
- (id)composer;
- (id)directors;
- (long)duration;
- (id)rating;
- (id)mediaType;
- (BOOL)hasVideoContent;
- (id)primaryGenre;
- (id)genres;
- (id)cast;
- (id)coverArt;
- (id)thumbnailArt;
- (id)coverArtID;
- (id)thumbnailArtID;
- (BOOL)hasCoverArt;
- (id)description;
- (id)dictionary;
- (void)setDictionary:(id)arg1;

@end

