/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRZoomTransitionControl.h>

@interface BRZoomTransitionControl (Private)
- (void)_addPrerender;
- (void)_removePrerender;
- (void)_takePrerenderSnapshot;
- (void)_updateContentForTransitionState;
- (void)_zoomInCompleted:(id)arg1;
- (void)_zoomOutCompleted:(id)arg1;
@end

