/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "CALayer.h"

@interface CALayer (BRCALayerAdditions)
- (id)firstLayerNamed:(id)arg1;
- (void)addBasicAnimationForProperty:(id)arg1 fromValue:(id)arg2 toValue:(id)arg3 duration:(double)arg4 timingFunction:(id)arg5 delegate:(id)arg6;
@end

