/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (Serialization)
- (BOOL)writeToFile:(id)arg1 atomically:(BOOL)arg2 format:(int)arg3;
@end

