/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSNotificationCenter.h"

@interface NSNotificationCenter (BRProviderHelpers)
- (BOOL)postProviderItemsInsertedAndOrRemovedNotificationsComparingOldData:(id)arg1 withNewData:(id)arg2 object:(id)arg3;
- (void)postProviderItemsModifiedNotificationForRange:(struct _NSRange)arg1 object:(id)arg2;
- (void)postProviderItemsModifiedNotificationForRanges:(id)arg1 object:(id)arg2;
- (void)postProviderItemsInsertedNotificationForRange:(struct _NSRange)arg1 object:(id)arg2;
- (void)postProviderItemsInsertedNotificationForRanges:(id)arg1 object:(id)arg2;
- (void)postProviderItemsRemovedNotificationForRange:(struct _NSRange)arg1 object:(id)arg2;
- (void)postProviderItemsRemovedNotificationForRanges:(id)arg1 object:(id)arg2;
- (void)postProviderTitleChangedNotificationFrom:(id)arg1;
@end

