/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSNotificationCenter.h"

@interface NSNotificationCenter (ThreadSpecificNotifications)
- (void)postNotification:(id)arg1 onThread:(id)arg2;
- (void)postNotificationName:(id)arg1 object:(id)arg2 onThread:(id)arg3;
- (void)postNotificationName:(id)arg1 object:(id)arg2 userInfo:(id)arg3 onThread:(id)arg4;
@end

