/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (BRStringUtilities)
+ (id)timeStringForSeconds:(double)arg1;
+ (id)timeStringWithLabelForSeconds:(double)arg1;
- (int)customCompare:(id)arg1;
- (unsigned long)hexValue;
- (id)fileSafeString;
- (BOOL)hasCaseInsensitivePrefix:(id)arg1;
- (id)subStringBefore:(int)arg1;
- (id)subStringAfter:(int)arg1;
- (id)stringByRemovingCharactersInSet:(id)arg1;
- (id)stringByReplacingCharactersInSet:(id)arg1 withString:(id)arg2;
- (id)stringByDecodingFriendlyHTMLCodes;
- (BOOL)boolValue;
@end

