/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRScrollControl;

@interface ScrollAnimationDelegate : NSObject
{
    BRScrollControl *_scroll;
    long _animationBalance;
}

- (id)initWithScroll:(id)arg1;
- (BOOL)scrolling;
- (void)clearScroll;
- (void)animationDidStart:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;

@end

