/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

//#import <BackRow/BRBaseMediaAsset.h>

@class NSString;

@interface BRPhotoMediaAsset //: BRBaseMediaAsset
{
    NSString *_thumbURL;
    NSString *_coverArtURL;
    NSString *_fullURL;
    NSString *_artID;
    double _dateTakenTimerInterval;
    BOOL _isLocal;
}

- (id)init;
- (void)dealloc;
- (void)setIsLocal:(BOOL)fp8;
- (BOOL)isLocal;
- (id)imageProxy;
- (id)assetID;
- (id)thumbnailArtID;
- (id)coverArtID;
- (id)fullSizeArtID;
- (id)thumbnailArt;
- (id)coverArt;
- (id)fullSizeArt;
- (id)title;
- (id)mediaType;
- (id)primaryCollection;
- (id)fullURL;
- (void)setFullURL:(id)fp8;
- (id)thumbURL;
- (void)setThumbURL:(id)fp8;
- (id)coverArtURL;
- (void)setCoverArtURL:(id)fp8;
- (id)dateTaken;
- (void)setDateTaken:(id)fp8;
- (void)setArtID:(id)fp8;

@end

