/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRAccount, BRController;

@interface BRAccountSelector : NSObject
{
    BRAccount *_account;
    BRController *_parentController;
    NSObject *_accountNameCollector;
    NSObject *_passwordCollector;
    id _delegate;
}

- (id)init;
- (void)dealloc;
- (void)selectAccountOfType:(id)arg1;
- (void)qualifyAccount:(id)arg1;
- (void)setDelegate:(id)arg1;

@end

