/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRTextFieldDelegate-Protocol.h"

@class BRAccountSelector, BRAccountType;

@interface BRAccountSelectorUserNameCollector : NSObject <BRTextFieldDelegate>
{
    BRAccountType *_type;
    BRAccountSelector *_accountSelector;
}

- (id)initWithType:(id)arg1 accountSelector:(id)arg2;
- (void)dealloc;
- (void)textDidChange:(id)arg1;
- (void)textDidEndEditing:(id)arg1;

@end

