/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary;

@interface BRAirportNetwork : NSObject
{
    NSDictionary *_data;
}

+ (id)networkWithName:(id)arg1 error:(id *)arg2;
+ (id)networkWithDictionary:(id)arg1;
+ (BOOL)openApple80211Ref:(struct _Apple80211 **)arg1 error:(int *)arg2;
+ (void)checkAirportPower;
- (id)init;
- (void)dealloc;
- (id)name;
- (int)securityType;
- (BOOL)associateUsingPassword:(id)arg1 error:(id *)arg2;

@end

