/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRProvider-Protocol.h"

@class NSArray;

@interface BRApplianceProvider : NSObject <BRProvider>
{
    NSArray *_applianceInfo;
}

- (id)init;
- (void)dealloc;
- (id)applianceInfoAtIndex:(long)arg1;
- (long)applianceInfoIndexForKey:(id)arg1;
- (id)controlFactory;
- (long)dataCount;
- (id)dataAtIndex:(long)arg1;
- (id)hashForDataAtIndex:(long)arg1;
- (void)reloadAppliances;

@end

