/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRApplianceManager.h>

@interface BRApplianceManager (ApplianceLoading)
- (void)_unloadCurrentAppliances;
- (id)_applianceForInfo:(id)arg1;
- (void)_loadAppliancesInFolder:(id)arg1;
- (void)_loadApplianceAtPath:(id)arg1;
@end

