/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@interface BRApplianceColumnControl : BRControl
{
    id _appliance;
    BRControl *_applianceLabel;
    BRControl *_preview;
    float _headerWidth;
    float _maxCategoryWidth;
}

- (id)initWithAppliance:(id)arg1;
- (id)previewControl;
- (void)dealloc;
- (void)reload;
- (void)unloadPreview;
- (float)headerWidth;
- (void)setMaxCategoryWidth:(float)arg1;
- (float)maxCategoryWidth;
- (void)resetMetrics;
- (void)resetMaxCategoryWidth;
- (void)layoutSubcontrols;

@end

