/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface BRAsyncTaskContext : NSObject
{
    int _maxRunningTasks;
    int _numRunningTasks;
    NSMutableArray *_taskQueue;
    NSMutableArray *_allTasks;
}

+ (void)initialize;
+ (id)defaultContext;
- (id)initWithMaxTasks:(int)arg1;
- (void)dealloc;
- (void)cancelTaskWithIdentifier:(id)arg1;

@end

