/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRAsyncTask.h>

@interface BRAsyncTask (Private)
- (id)_initWithSelector:(SEL)arg1 onTarget:(id)arg2 withObject:(id)arg3 withContext:(id)arg4;
@end

