/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRMarqueeTextControl, BRTextControl, NSAttributedString;

@interface BRAutoScrollingTextControl : BRControl
{
    NSAttributedString *_text;
    BRMarqueeTextControl *_scrollingTextControl;
    BRTextControl *_textControl;
    BOOL _crossfadeEnabled;
    BOOL _autoScrollEnabled;
}

- (void)dealloc;
- (void)setText:(id)arg1 withAttributes:(id)arg2;
- (void)setAttributedString:(id)arg1;
- (id)attributedString;
- (void)setCrossfadeEnabled:(BOOL)arg1;
- (BOOL)crossfadeEnabled;
- (void)setAutoScrollEnabled:(BOOL)arg1;
- (BOOL)autoScrollEnabled;
- (void)layoutSubcontrols;
- (id)preferredActionForKey:(id)arg1;

@end

