/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBackgroundTask.h>

@interface BRBackgroundTask (Private)
- (void)_setEnabled:(BOOL)arg1;
- (void)_delayedPerform:(id)arg1;
- (void)_intervalPerform:(id)arg1;
- (id)_userInfo;
@end

