/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRMediaLoading-Protocol.h"
#import "BRMediaProvider-Protocol.h"

@interface BRBaseMediaProvider : NSObject <BRMediaProvider, BRMediaLoading>
{
    int _providerStatus;
    BOOL _passwordProtected;
}

+ (id)errorStateOfProvider:(id)arg1;
+ (id)mediaProvider;
- (void)dealloc;
- (id)providerID;
- (id)machineID;
- (id)providerName;
- (id)mediaTypes;
- (id)mediaForEntityName:(id)arg1;
- (id)objectsWithEntityName:(id)arg1 qualifiedByPredicate:(id)arg2 sortDescriptors:(id)arg3 error:(id *)arg4;
- (id)objectsWithEntityName:(id)arg1 qualifiedByPredicate:(id)arg2 sortDescriptors:(id)arg3 excludeHiddenObjects:(BOOL)arg4 error:(id *)arg5;
- (int)status;
- (int)errorCodeForProvider;
- (void)setStatus:(int)arg1;
- (int)load;
- (int)loadWithUsername:(id)arg1 password:(id)arg2;
- (int)unload;
- (BOOL)autoload;
- (void)reset;
- (BOOL)isPasswordProtected;
- (void)setIsPasswordProtected:(BOOL)arg1;
- (void)flush;
- (long)countOfObjectsWithMediaType:(id)arg1;

@end

