/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRMediaAsset-Protocol.h"

@interface BRBaseMediaAsset : NSObject <BRMediaAsset>
{
    id _provider;
}

- (id)initWithMediaProvider:(id)arg1;
- (void)dealloc;
- (id)provider;
- (id)assetID;
- (id)mediaObjectID;
- (id)artist;
- (id)artistForSorting;
- (id)title;
- (id)titleForSorting;
- (id)mediaSummary;
- (id)mediaDescription;
- (id)copyright;
- (long)duration;
- (long)performanceCount;
- (id)cast;
- (id)directors;
- (id)producers;
- (void)incrementPerformanceCount;
- (void)incrementPerformanceOrSkipCount:(unsigned int)arg1;
- (BOOL)hasBeenPlayed;
- (void)setHasBeenPlayed:(BOOL)arg1;
- (id)mediaURL;
- (id)previewURL;
- (id)imageProxy;
- (id)imageProxyWithBookMarkTimeInMS:(unsigned int)arg1;
- (BOOL)hasCoverArt;
- (id)dateAcquired;
- (id)dateCreated;
- (id)datePublished;
- (id)mediaType;
- (id)primaryGenre;
- (id)genres;
- (int)primaryCollectionOrder;
- (int)physicalMediaID;
- (id)seriesName;
- (id)seriesNameForSorting;
- (id)broadcaster;
- (id)episodeNumber;
- (unsigned int)season;
- (unsigned int)episode;
- (id)mediaCollections;
- (float)userStarRating;
- (void)setUserStarRating:(float)arg1;
- (id)rating;
- (BOOL)isHD;
- (BOOL)isWidescreen;
- (BOOL)closedCaptioned;
- (BOOL)dolbyDigital;
- (float)starRating;
- (id)publisher;
- (id)composer;
- (id)composerForSorting;
- (BOOL)hasVideoContent;
- (BOOL)isDisabled;
- (BOOL)isProtectedContent;
- (id)playbackRightsOwner;
- (void)setBookmarkTimeInSeconds:(unsigned int)arg1;
- (void)setBookmarkTimeInMS:(unsigned int)arg1;
- (unsigned int)bookmarkTimeInSeconds;
- (unsigned int)bookmarkTimeInMS;
- (id)lastPlayed;
- (void)setLastPlayed:(id)arg1;
- (unsigned int)startTimeInSeconds;
- (unsigned int)startTimeInMS;
- (unsigned int)stopTimeInSeconds;
- (unsigned int)stopTimeInMS;
- (id)primaryCollection;
- (id)artistCollection;
- (id)primaryCollectionTitle;
- (id)primaryCollectionTitleForSorting;
- (id)collections;
- (id)dateAcquiredString;
- (id)dateCreatedString;
- (id)datePublishedString;
- (void)logDescription;
- (id)resolution;
- (id)authorName;
- (id)keywords;
- (id)viewCount;
- (id)category;
- (BOOL)isInappropriate;
- (int)grFormat;
- (BOOL)canBePlayedInShuffle;
- (BOOL)isLocal;
- (BOOL)isAvailable;
- (void)skip;
- (void)willBeDeleted;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (void)preparePlaybackContext;
- (void)cleanUpPlaybackContext;
- (long)parentalControlRatingSystemID;
- (long)parentalControlRatingRank;
- (BOOL)isExplicit;
- (BOOL)playable;
- (void *)createMovieWithProperties:(void *)arg1 count:(long)arg2;
- (id)sourceID;
- (BOOL)isCheckedOut;
- (void)performSelector:(SEL)arg1 target:(id)arg2;
- (void)performSelector:(SEL)arg1 target:(id)arg2 withObject:(id)arg3;
- (BOOL)isPlaying;
- (BOOL)isPlayingOrPaused;

@end

