/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRBaseMenuItemLayerPopulator : NSObject
{
    id _object;
    id _delegate;
    unsigned int _matchOrder;
}

+ (BOOL)canHandleObject:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)menuItemLayerForObject:(id)arg1 delegate:(id)arg2;
- (float)menuItemHeightForObject:(id)arg1 delegate:(id)arg2;
- (id)titleForObject:(id)arg1 delegate:(id)arg2;
- (void)setObject:(id)arg1;
- (id)menuItemLayer;
- (id)dividerLayer;
- (id)textMenuItemLayer;
- (id)comboMenuItemLayer;
- (id)textImageMenuItemLayer;
- (id)title;
- (id)rightJustifiedText;
- (id)subtitle;
- (id)lowerLeftString;
- (id)lowerCenteredString;
- (id)thumbnailImage;
- (id)upperRightImage;
- (id)lowerRightImage;
- (BOOL)shouldUseMultilineItem:(id)arg1;

@end

