/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRAppliance-Protocol.h"

@class BRProviderGroup, NSArray;

@interface BRBaseAppliance : NSObject <BRAppliance>
{
    NSArray *_categories;
    BRProviderGroup *_providerGroup;
    BOOL _subsetProvidersArePadded;
}

- (id)init;
- (void)dealloc;
- (id)baseMediaType;
- (id)applianceInfo;
- (id)applianceCategories;
- (id)identifierForContentAlias:(id)arg1;
- (id)controllerForIdentifier:(id)arg1 args:(id)arg2;
- (BOOL)handleObjectSelection:(id)arg1 userInfo:(id)arg2;
- (BOOL)handlePlay:(id)arg1 userInfo:(id)arg2;
- (id)previewControlForIdentifier:(id)arg1;
- (void)refreshPreviewControlDataForIdentifier:(id)arg1;
- (id)previewProvidersForIdentifier:(id)arg1 withNames:(id *)arg2;
- (long)shelfColumnCount;
- (id)musicStoreItemWithIdentifier:(id)arg1;
- (id)categoryWithIdentifier:(id)arg1;
- (id)alertControllerForNoContent;
- (int)noContentBRError;
- (id)alertControllerForNoRemoteContent;
- (int)noRemoteContentBRError;
- (BOOL)previewError;
- (id)previewErrorText;
- (id)previewErrorSubtext;
- (id)previewErrorIconImage;
- (void)previewProviderCountChanged:(id)arg1;

@end

