/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRMediaCollection-Protocol.h"

@interface BRBaseMediaCollection : NSObject <BRMediaCollection>
{
    id _provider;
}

- (id)initWithMediaProvider:(id)arg1;
- (void)dealloc;
- (unsigned int)hash;
- (id)provider;
- (id)childCollections;
- (id)parentCollection;
- (id)collectionType;
- (id)collectionID;
- (id)mediaObjectID;
- (id)imageProxy;
- (int)count;
- (id)mediaAssets;
- (id)assetEnumerator;
- (BOOL)isCompilation;
- (BOOL)isSingleArtistCompilation;
- (id)artist;
- (id)artistForSorting;
- (id)title;
- (id)titleForSorting;
- (id)titleNoDefault;
- (id)titleForSortingNoDefault;
- (long)duration;
- (id)mediaTypes;
- (id)mediaType;
- (BOOL)isLocal;
- (BOOL)isAvailable;
- (BOOL)isHidden;
- (void)willBeDeleted;
- (id)date;
- (void)performSelector:(SEL)arg1 target:(id)arg2;
- (void)performSelector:(SEL)arg1 target:(id)arg2 withObject:(id)arg3;

@end

