/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSelectionLozengeLayer.h>

@interface BRBlueGlowSelectionLozengeLayer : BRSelectionLozengeLayer
{
    BOOL _focusedImage;
}

- (id)init;
- (float)topGlowHeight;
- (float)bottomGlowHeight;
- (float)edgeGlowWidth;
- (void)setFocused:(BOOL)arg1;
- (void)drawInContext:(struct CGContext *)arg1;

@end

