/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBoxLayoutManager.h>

@interface BRBoxFillLayoutManager : BRBoxLayoutManager
{
    float _spacingScale;
    float _horizontalMarginScale;
    float _verticalMarginScale;
    int _scaleRelation;
}

- (void)setSpacingScale:(float)arg1 relativeTo:(int)arg2;
- (void)setHorizontalMarginScale:(float)arg1;
- (float)horizontalMarginScale;
- (void)setVerticalMarginScale:(float)arg1;
- (float)verticalMarginScale;
- (void)layoutSublayersOfLayer:(id)arg1;

@end

