/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRClosedCaptionControl.h>

@interface BRClosedCaptionControl (LayoutHelpers)
- (void)_positionCCTextSublayer:(id)arg1 inLayerFrame:(struct CGRect)arg2;
- (void)_positionCCBubbleSublayer:(id)arg1 inLayerFrame:(struct CGRect)arg2;
@end

