/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageControl, BRMarqueeTextControl, BRTextControl, NSString;

@interface BRComboMenuItemLayer : BRControl
{
    BRControl *_background;
    BRImageControl *_thumbnailLayer;
    BRMarqueeTextControl *_titleLayer;
    BRTextControl *_subtitleLayer;
    BRTextControl *_leftTextLayer;
    BRTextControl *_middleTextLayer;
    BRImageControl *_bottomRightImageLayer;
    BRImageControl *_topRightImageLayer;
    NSString *_thumbnailIdentifier;
    float _thumbnailPaddingFactor;
    float _thumbnailLayerAspect;
}

- (id)init;
- (void)dealloc;
- (float)defaultRowHeight;
- (void)setTitle:(id)arg1;
- (id)title;
- (void)setSubtitle:(id)arg1;
- (id)subtitle;
- (void)setLeftText:(id)arg1;
- (void)setMiddleText:(id)arg1;
- (void)setThumbnailImage:(id)arg1;
- (void)setThumbnailIdentifier:(id)arg1;
- (id)thumbnailIdentifier;
- (void)setThumbnailPaddingFactor:(float)arg1;
- (float)thumbnailPaddingFactor;
- (void)setThumbnailLayerAspectRatio:(float)arg1;
- (float)thumbnailLayerAspectRatio;
- (void)setBottomRightImage:(id)arg1;
- (void)setTopRightImage:(id)arg1;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (struct CGRect)focusCursorFrame;
- (void)layoutSubcontrols;
- (id)axSelectedItemText;

@end

