/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@interface BRControl (BRControlGeometry)
- (void)setFrame:(struct CGRect)arg1;
- (struct CGRect)frame;
- (void)setPosition:(struct CGPoint)arg1;
- (struct CGPoint)position;
- (void)setBounds:(struct CGRect)arg1;
- (struct CGRect)bounds;
- (void)setAnchorPoint:(struct CGPoint)arg1;
- (struct CGPoint)anchorPoint;
- (void)setAffineTransform:(struct CGAffineTransform)arg1;
- (struct CGAffineTransform)affineTransform;
- (void)setAutoresizingMask:(unsigned int)arg1;
- (unsigned int)autoresizingMask;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)sizeToFit;
- (struct CGSize)preferredFrameSize;
- (void)setWidthScale:(float)arg1 relativeTo:(int)arg2;
- (void)setHeightScale:(float)arg1 relativeTo:(int)arg2;
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 fromControl:(id)arg2;
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 toControl:(id)arg2;
- (struct CGRect)convertRect:(struct CGRect)arg1 fromControl:(id)arg2;
- (struct CGRect)convertRect:(struct CGRect)arg1 toControl:(id)arg2;
@end

