/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControllerStack.h>

@interface BRControllerStack (ControllerRefresh)
- (void)_updateControllersOnlyLegacy:(BOOL)arg1;
- (void)_refreshControllersNotification:(id)arg1;
- (void)_databaseObjectModified:(id)arg1;
- (void)_updateControllerValidity:(id)arg1;
@end

