/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRControl, NSString;

@interface BRControlMediator : NSObject
{
    NSString *_identifier;
    BRControl *_control;
    BRControl *_preview;
    BOOL _active;
}

+ (id)mediator;
+ (id)mediatorWithControl:(id)arg1 identifier:(id)arg2;
- (id)init;
- (void)dealloc;
- (void)setIdentifier:(id)arg1;
- (id)identifier;
- (void)setActive:(BOOL)arg1;
- (BOOL)active;
- (void)setControl:(id)arg1;
- (id)control;
- (void)setPreviewControl:(id)arg1;
- (id)previewControl;

@end

