/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@interface BRControl (BRControlHierarchy)
- (id)parent;
- (BOOL)active;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)setName:(id)arg1;
- (id)name;
- (id)firstControlNamed:(id)arg1;
- (void)addControl:(id)arg1;
- (void)insertControl:(id)arg1 atIndex:(long)arg2;
- (void)insertControl:(id)arg1 above:(id)arg2;
- (void)insertControl:(id)arg1 below:(id)arg2;
- (void)setControls:(id)arg1;
- (id)controls;
- (void)removeFromParent;
- (void)setNeedsLayout;
- (void)layoutSubcontrols;
@end

