/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRBoxListControl, NSTimer;

@interface BRContextMenuControl : BRControl
{
    BRControl *_endPositionControl;
    BRControl *_startPositionControl;
    BRControl *_dimControl;
    BRControl *_dimPanel;
    struct CGRect _endPositionControlFrame;
    struct CGRect _startPositionControlFrame;
    struct CGRect _dimControlFrame;
    BRBoxListControl *_contextBox;
    int _dimOption;
    NSTimer *_autoDismissTimer;
}

- (id)init;
- (void)dealloc;
- (void)controlWasDeactivated;
- (BOOL)brEventAction:(id)arg1;
- (void)setProvider:(id)arg1;
- (void)setProviders:(id)arg1;
- (id)providers;
- (void)setStartPositionControl:(id)arg1;
- (id)startPositionControl;
- (void)setEndPositionControl:(id)arg1;
- (id)endPositionControl;
- (void)setDimControl:(id)arg1;
- (id)dimControl;
- (void)setDimOption:(int)arg1;
- (int)dimOption;
- (void)layoutSubcontrols;
- (void)setIsVisible:(BOOL)arg1;
- (BOOL)isVisible;

@end

