/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRContextMenuControl.h>

@interface BRContextMenuControl (Private)
- (void)_addAnimationsForDisplayState:(BOOL)arg1;
- (void)_dissmissAnimationComplete;
- (struct CGRect)_endPositionControlFrame;
- (struct CGRect)_startPositionControlFrame;
- (struct CGRect)_dimControlFrame;
@end

