/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@interface BRControl (FocusUtilities)
- (struct CGPoint)_focusedPointForEvent:(id)arg1;
- (BOOL)_focusControlTreeWithDefaults;
- (BOOL)_focusControlTreeForEvent:(id)arg1 nearPoint:(struct CGPoint)arg2;
- (BOOL)_changeFocusTo:(id)arg1;
- (void)_setFocus:(id)arg1;
- (void)_setControlFocused:(BOOL)arg1;
@end

