/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BREventResponder-Protocol.h"

@class CALayer;

@interface BRControl : NSObject <BREventResponder>
{
    CALayer *_backing;
    BRControl *_defaultFocus;
    BRControl *_focusedControl;
    BRControl *_previousFocus;
    BRControl *_keyEventTargetControl;
    BOOL _acceptsFocus;
    BOOL _focused;
    BOOL _controlActive;
}

+ (id)control;
+ (Class)layerClass;
- (id)init;
- (void)dealloc;
- (id)layer;
- (void)setObject:(id)arg1;
- (id)object;
- (void)setIdentifier:(id)arg1;
- (id)identifier;
- (BOOL)brEventAction:(id)arg1;
- (BOOL)brKeyEvent:(id)arg1;
- (id)valueForUndefinedKey:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
- (void)_layoutSublayersOfLayer:(id)arg1;
- (void)setKeyEventTargetControl:(id)arg1;
- (id)keyEventTargetControl;

@end

