/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRCursorLayer;

@interface BRCursorControl : BRControl
{
    BRControl *_trackedControl;
    BRCursorLayer *_cursorLayer;
    int _style;
    BOOL _cursorInactive;
}

- (id)init;
- (void)dealloc;
- (void)setCursorStyle:(int)arg1;
- (int)cursorStyle;
- (void)setCursorInactive:(BOOL)arg1;
- (BOOL)cursorInactive;
- (id)cursorLayer;
- (void)controlWasActivated;
- (void)layoutSubcontrols;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

