/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRCyclerControl.h>

@interface BRCyclerControl (Private)
- (void)_providerUpdated:(id)arg1;
- (void)_crossFade:(id)arg1;
- (void)_startCrossFadeTimer;
- (void)_stopCrossFadeTimer;
- (void)_returnToStart;
@end

