/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRMarqueeTextControl, BRTextControl;

@interface BRDetailedMusicMetadataControl : BRControl
{
    BRMarqueeTextControl *_songTitle;
    BRTextControl *_songArtist;
    BRTextControl *_albumTitle;
    BRTextControl *_trackInfo;
    BRTextControl *_duration;
    BRTextControl *_releaseDate;
    BRTextControl *_price;
    BOOL _scrollingAllowed;
}

- (id)init;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)setSongTitle:(id)arg1;
- (void)setSongArtist:(id)arg1;
- (void)setAlbumTitle:(id)arg1;
- (void)setTrackInfo:(id)arg1;
- (void)setDuration:(id)arg1;
- (void)setReleaseDate:(id)arg1;
- (void)setPrice:(id)arg1;
- (void)layoutSubcontrols;
- (void)setScrollingAllowed:(BOOL)arg1;
- (BOOL)scrollingAllowed;

@end

