/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRDescriptionOverlayControl.h>

@interface BRDescriptionOverlayControl (OverlayFader)
- (void)_hideOverlay;
- (void)_showOverlay;
- (void)_fadeOverlay:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
@end

