/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWebControl.h>

@interface BRDigitalExtrasWebControl : BRWebControl
{
    id _digitalExtrasDelegate;
}

+ (void)initialize;
+ (id)webControl;
- (void)setDigitalExtrasDelegate:(id)arg1;
- (id)digitalExtrasDelegate;
- (void)loadDigitalExtra:(id)arg1;

@end

