/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRDividerProvider.h>

@interface BRDividerProvider (Private)
- (void)_updateTopDividerControl;
- (BOOL)_shouldShowDivider;
- (id)_shiftRangesDown:(id)arg1;
- (void)_providerItemsModified:(id)arg1;
- (void)_providerItemsInserted:(id)arg1;
- (void)_providerItemsRemoved:(id)arg1;
@end

