/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRController.h>

@class BRControl, BRDigitalExtrasWebControl, BRWaitPromptControl, NSTimer;

@interface BRDigitalExtrasController : BRController
{
    BRDigitalExtrasWebControl *_digitalExtrasWebControl;
    BRControl *_blackBackground;
    BRWaitPromptControl *_spinner;
    NSTimer *_spinnerTimer;
    NSTimer *_busyTimer;
    NSTimer *_syncHoldOffTimer;
    int _pageState;
}

+ (id)controllerWithAsset:(id)arg1;
- (id)initWithAsset:(id)arg1;
- (void)dealloc;
- (BOOL)brEventAction:(id)arg1;
- (void)wasPushed;
- (void)wasPopped;
- (void)layoutSubcontrols;
- (void)webControlDidStartLoad:(id)arg1;
- (void)webControlDidFinishLoad:(id)arg1;
- (void)webControl:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webControl:(id)arg1 didReceiveTitle:(id)arg2;
- (void)openTabNamed:(id)arg1 withRequest:(id)arg2;
- (void)webControl:(id)arg1 saveStateToHistoryItem:(id)arg2;
- (void)handleCustomJSEvent:(id)arg1;
- (void)unnavigableLinkClicked:(id)arg1;

@end

