/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRDigitalExtrasController.h>

@interface BRDigitalExtrasController (Private)
- (void)_mediaHostRemoved:(id)arg1;
- (void)_assetWillBeDeleted:(id)arg1;
- (void)_spinnerTimerFired:(id)arg1;
- (void)_pageLoaded;
- (void)_setPageBusy:(id)arg1;
- (void)_busyTimerFired:(id)arg1;
- (void)_holdOffSyncing:(id)arg1;
@end

