/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRControl, BRWindow, NSString;

@interface BRDialog : NSObject
{
    BRWindow *_window;
    BRControl *_control;
    NSString *_identifier;
}

+ (void)initialize;
+ (void)postDialogWithControl:(id)arg1 identifier:(id)arg2 style:(int)arg3 opaque:(BOOL)arg4;
+ (BOOL)isDialogPostedWithIdentifier:(id)arg1;
+ (BOOL)isDialogCurrentlyPosted;
+ (void)postDialogWithControl:(id)arg1 identifier:(id)arg2;
+ (void)postModalDialogWithControl:(id)arg1 identifier:(id)arg2;
+ (void)postModalDialogWithController:(id)arg1 identifier:(id)arg2;
+ (void)postModalDialog:(id)arg1;
+ (void)postModalDialogWithControl:(id)arg1 identifier:(id)arg2 style:(int)arg3 opaque:(BOOL)arg4;
+ (void)postModalDialogWithController:(id)arg1 identifier:(id)arg2 style:(int)arg3 opaque:(BOOL)arg4;
+ (void)dismissDialogWithIdentifier:(id)arg1;
- (id)initWithControl:(id)arg1 identifier:(id)arg2 style:(int)arg3 opaque:(BOOL)arg4;
- (void)dealloc;
- (id)control;
- (id)identifier;
- (void)transitionIn;
- (void)transitionOut;

@end

