/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary;

@interface BRDisplayMode : NSObject
{
    NSDictionary *_modeDictionary;
}

+ (id)allDisplayModesForDisplay:(struct _CGDirectDisplayID *)arg1;
- (id)initWithDisplayID:(struct _CGDirectDisplayID *)arg1;
- (id)initWithModeDictionary:(id)arg1;
- (void)dealloc;
- (id)modeDictionary;
- (BOOL)isEqualToMode:(id)arg1;
- (BOOL)safe;
- (BOOL)safeForHardware;
- (unsigned long)width;
- (unsigned long)height;
- (unsigned long)bitsPerPixel;
- (BOOL)interlaced;
- (double)refreshRate;
- (int)ioDisplayModeID;
- (BOOL)isEqual:(id)arg1;

@end

