/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRController.h>

#import "BRTextFieldDelegate-Protocol.h"

@class BRHeaderControl, BRIPv4AddressEntryControl, BRTextControl, NSString;

@interface BRDottedQuadEntryController : BRController <BRTextFieldDelegate>
{
    id _delegate;
    BRIPv4AddressEntryControl *_editor;
    BRTextControl *_prompt;
    BRHeaderControl *_header;
    NSString *_dottedQuad;
}

- (id)initWithTitle:(id)arg1 prompt:(id)arg2 label:(id)arg3 notifying:(id)arg4;
- (void)dealloc;
- (void)setFrame:(struct CGRect)arg1;
- (void)setIcon:(id)arg1 horizontalOffset:(float)arg2 kerningFactor:(float)arg3;
- (void)textDidChange:(id)arg1;
- (void)textDidEndEditing:(id)arg1;
- (id)dottedQuad;
- (void)setDottedQuad:(id)arg1;

@end

