/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface BRDownloadManager : NSObject
{
    NSMutableArray *_downloads;
    NSMutableArray *_playableNotifications;
}

+ (void)initialize;
+ (void)_applicationQuit:(id)arg1;
+ (void)registerDownloadManager:(id)arg1 forMediaType:(id)arg2;
+ (void)removeDownloadManagerForMediaType:(id)arg1;
+ (id)downloadManagerForMediaType:(id)arg1;
+ (void)registerDownloadTestManager:(id)arg1;
+ (id)downloadTestManager;
+ (BOOL)downloadsInProgress;
+ (id)allDownloads;
+ (id)displayStringForDownloadState:(int)arg1 context:(int)arg2;
+ (id)shortDisplayStringForDownloadState:(int)arg1;
+ (id)displayStringForDownloadStateWithPercentageForItem:(id)arg1;
+ (id)shortDisplayStringForDownloadStateWithPercentageForItem:(id)arg1;
+ (id)displayStringForDownloadEstimatedTimeUntilPlayableForItem:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)addDownload:(id)arg1;
- (void)removeDownload:(id)arg1;
- (void)deleteDownloadFromITunesQueue:(id)arg1 removeFromDisk:(BOOL)arg2;
- (id)downloads;
- (void)prioritizeDownload:(id)arg1;

@end

