/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRDownloadPlayableAlertControl.h>

@interface BRDownloadPlayableAlertControl (Private)
- (void)_postIfReady:(id)arg1;
- (BOOL)_isVideoPlayerControlActive;
- (BOOL)_dialogShouldBePosted;
- (void)_postWithControl:(id)arg1;
- (void)_setAsset:(id)arg1;
- (void)_playAsset;
@end

