/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRAlertController.h>

@interface BRFatalExceptionAlertController : BRAlertController
{
}

+ (id)controllerForFatalException:(id)arg1;
+ (id)controllerForFatalNSException:(id)arg1;
- (BOOL)brEventAction:(id)arg1;

@end

