/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRFocusEngine : NSObject
{
}

+ (id)initalFocusForPoint:(struct CGPoint)arg1 container:(id)arg2 searchDownwardOnly:(BOOL)arg3;
+ (id)newFocusForCandidate:(id)arg1 container:(id)arg2 event:(id)arg3;
+ (id)newFocusForEdge:(struct BRFocusEdge)arg1 currentCandidate:(id)arg2 container:(id)arg3 event:(id)arg4;
+ (struct BRFocusEdge)focusEdgeForEvent:(id)arg1 elementPosition:(struct CGPoint)arg2 elementBounds:(struct CGSize)arg3;
+ (struct BRFocusEdge)oppositeFocusEdgeForEvent:(id)arg1 elementPosition:(struct CGPoint)arg2 elementBounds:(struct CGSize)arg3;

@end

