/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRImageControl.h>

@class BRImage;

@interface BRFocusableImageControl : BRImageControl
{
    BRImage *_focusedImage;
    BRImage *_unfocusedImage;
    BRImage *_disabledImage;
    BOOL _dimsWhenDisabled;
    BOOL _disabled;
}

- (void)dealloc;
- (void)setFocusedImage:(id)arg1;
- (id)focusedImage;
- (void)setUnfocusedImage:(id)arg1;
- (id)unfocusedImage;
- (void)setDisabled:(BOOL)arg1;
- (BOOL)disabled;
- (void)setDisabledImage:(id)arg1;
- (id)disabledImage;
- (void)setDimsWhenDisabled:(BOOL)arg1;
- (BOOL)dimsWhenDisabled;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (id)preferredActionForKey:(id)arg1;

@end

