/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRController.h>

@class NSString;

@interface BRFullScreenPhotoController : BRController
{
    long _startIndex;
    long _currentIndex;
    id _provider;
    id _delegate;
    BOOL _isNetworkDependent;
    BOOL _syncEventOccurred;
    NSString *_currentPrefetchImageID;
    NSString *_currentPrefetchAssetID;
    BOOL _initialLayoutCompleted;
    int _startTouchXPosition;
    float _curTouchOffset;
}

+ (id)fullScreenPhotoControllerForProvider:(id)arg1 startIndex:(long)arg2;
- (id)initWithProvider:(id)arg1 startIndex:(long)arg2;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (BOOL)isValidAfterDataUpdate;
- (long)currentIndex;
- (void)setControllerDelegate:(id)arg1;
- (void)setIsNetworkDependent:(BOOL)arg1;
- (BOOL)isNetworkDependent;
- (BOOL)brEventAction:(id)arg1;
- (void)layoutSubcontrols;

@end

