/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRGridControl.h>

@interface BRGridControl (Layout)
- (double)_totalHeight;
- (double)_heightToRange;
- (float)_verticalGapValue;
- (float)_positionOfColumn:(long)arg1 inRowWidth:(float)arg2 cellWidth:(float *)arg3;
- (struct CGRect)_frameForControlAtIndex:(long)arg1 controls:(id)arg2;
- (struct CGRect)_frameForControlAtIndex:(long)arg1 rowFrame:(struct CGRect)arg2 controls:(id)arg3;
- (void)_frameRowInRange:(struct _NSRange)arg1 rowFrame:(struct CGRect)arg2 controls:(id)arg3;
@end

