/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRAsyncTaskContext, NSMutableArray;

@interface BRImageLoader : NSObject
{
    long _queueSize;
    NSMutableArray *_imageQueue;
    NSMutableArray *_candidateImages;
    NSMutableArray *_pendingImages;
    id _provider;
    BOOL _randomize;
    long _serialIndex;
    long _imageArrayIndex;
    long _segmentLength;
    long _segmentCount;
    int _fillStrategy;
    long _failedLoadCount;
    BRAsyncTaskContext *_taskContext;
}

- (id)init;
- (void)dealloc;
- (void)setSegmentCount:(long)arg1;
- (long)segmentCount;
- (void)setImageProxies:(id)arg1;
- (void)setProvider:(id)arg1;
- (void)setFillStrategy:(int)arg1;
- (int)fillStrategy;
- (void)setQueueSize:(long)arg1;
- (long)queueSize;
- (void)flushQueue;
- (BOOL)queueReady;
- (void)setRandomize:(BOOL)arg1;
- (BOOL)randomize;
- (long)imageCount;
- (id)finalFormForImage:(id)arg1;
- (BOOL)isImageFinalForm:(id)arg1;
- (id)nextImage;

@end

