/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageControl, BRReflectionControl, BRSyncProgressControl, BRTextControl;

@interface BRImageAndSyncingPreviewController : BRControl
{
    BRImageControl *_imageControl;
    BRReflectionControl *_reflectionControl;
    BRSyncProgressControl *_syncProgressControl;
    BRTextControl *_statusTextControl;
    BOOL _hasProgress;
}

- (id)init;
- (void)dealloc;
- (void)layoutSubcontrols;
- (void)setImage:(id)arg1;
- (id)imageControl;
- (void)controlWasActivated;
- (void)setHasSyncProgress:(BOOL)arg1;
- (void)setStatusMessage:(id)arg1;
- (void)setReflectionOffset:(float)arg1;
- (void)setReflectionAmount:(float)arg1;

@end

