/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImage, NSString;

@interface BRImageControl : BRControl
{
    BRImage *_image;
    struct CGSize _lastDownsample;
    BOOL _autoDownsample;
    NSString *_artworkIdentifier;
}

- (void)dealloc;
- (void)setImage:(id)arg1;
- (id)image;
- (struct CGSize)pixelBounds;
- (float)aspectRatio;
- (void)setAutomaticDownsample:(BOOL)arg1;
- (BOOL)automaticDownsample;
- (void)setArtworkIdentifier:(id)arg1;
- (void)layoutSubcontrols;
- (struct CGSize)preferredFrameSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

