/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRImageLoadJob, NSMutableData;

@interface BRImageLoadDelegate : NSObject
{
    BRImageLoadJob *_job;
    NSMutableData *_data;
}

+ (id)imageLoadDelegateWithJob:(id)arg1;
- (id)initWithJob:(id)arg1;
- (void)dealloc;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (id)job;
- (id)content;

@end

