/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class BRAsyncTaskContext, NSLock, NSMutableArray, NSMutableDictionary, NSString;

@interface BRImageManager : BRSingleton
{
    unsigned long long _maxCacheSize;
    unsigned long long _cacheSize;
    NSString *_imageCachePath;
    NSMutableDictionary *_images;
    NSMutableDictionary *_remoteImageRequests;
    NSLock *_remoteImageLock;
    NSMutableArray *_jobQueue;
    NSMutableDictionary *_pendingCachedImagesToFlush;
    BOOL _processJobs;
    BOOL _cachePurging;
    BRAsyncTaskContext *_loadTaskContext;
    BRAsyncTaskContext *_writeTaskContext;
    NSMutableArray *_activeDelegates;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
+ (id)fullScreenImageResizingOptions;
- (id)init;
- (void)dealloc;
- (BOOL)isImageAvailable:(id)arg1;
- (BOOL)isImageAvailable:(id)arg1 scaledToSize:(struct CGSize)arg2;
- (BOOL)isImageAvailable:(id)arg1 croppedToSize:(struct CGSize)arg2;
- (id)imageNameFromURL:(id)arg1;
- (id)writeImageFromImageProxy:(id)arg1;
- (id)writeImageFromURL:(id)arg1;
- (id)writeEncryptedImageFromURL:(id)arg1;
- (id)writeImageFromURL:(id)arg1 isEncrypted:(BOOL)arg2;
- (id)writeImageFromURL:(id)arg1 headerFields:(id)arg2 isEncrypted:(BOOL)arg3;
- (id)writeImageFromURL:(id)arg1 imageID:(id)arg2 headerFields:(id)arg3 isEncrypted:(BOOL)arg4;
- (void)cancelWriteForImageWithURL:(id)arg1 imageID:(id)arg2;
- (id)loadImageFromURL:(id)arg1 headerFields:(id)arg2 isEncrypted:(BOOL)arg3;
- (void)writeImage:(id)arg1 named:(id)arg2;
- (void)writeImage:(id)arg1 named:(id)arg2 asynchronous:(BOOL)arg3;
- (void)writeScaledImage:(id)arg1 named:(id)arg2 withSize:(struct CGSize)arg3;
- (void)writeCroppedImage:(id)arg1 named:(id)arg2;
- (id)imageNamed:(id)arg1 croppedToSize:(struct CGSize)arg2 create:(BOOL)arg3;
- (id)imageNamed:(id)arg1 scaledToSize:(struct CGSize)arg2 create:(BOOL)arg3;
- (id)imageNamed:(id)arg1;
- (void)remoteImageRequestForMediaID:(id)arg1;
- (void)receivedRemoteITunesImage:(id)arg1 forID:(id)arg2;
- (BOOL)receiveRemoteImageURL:(id)arg1 forID:(id)arg2;
- (BOOL)receiveRemoteImageURL:(id)arg1 forID:(id)arg2 withResizingOptions:(id)arg3;
- (void)receivedRemoteImage:(id)arg1 forID:(id)arg2;
- (BOOL)hasRemoteImageBeenRequestedForMediaID:(id)arg1;
- (void)purgeRemoteRequest;

@end

