/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSInvocation;

@interface BRInvocationAnimationDelegate : NSObject
{
    NSInvocation *_startInvocation;
    NSInvocation *_endInvocation;
    id _endTarget;
}

+ (id)delegateWithEndInvocation:(id)arg1;
+ (id)delegateWithStartInvocation:(id)arg1;
+ (id)delegateWithStartInvocation:(id)arg1 endInvocation:(id)arg2;
+ (id)delegateWithTarget:(id)arg1 endSelector:(SEL)arg2;
+ (id)delegateWithTarget:(id)arg1 startSelector:(SEL)arg2;
+ (id)delegateWithTarget:(id)arg1 startSelector:(SEL)arg2 endSelector:(SEL)arg3;
- (id)initWithStartInvocation:(id)arg1 endInvocation:(id)arg2;
- (void)dealloc;
- (id)startInvocation;
- (id)endInvocation;
- (void)animationDidStart:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;

@end

