/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRSelectionHandler-Protocol.h"

@class NSInvocation;

@interface BRInvocationSelectionHandler : NSObject <BRSelectionHandler>
{
    NSInvocation *_invocation;
    BOOL _useInvocationReturnValue;
}

+ (id)handlerWithInvocation:(id)arg1;
+ (id)handlerWithTarget:(id)arg1 selector:(SEL)arg2;
- (id)initWithInvocation:(id)arg1;
- (void)dealloc;
- (id)invocation;
- (void)setUseInvocationReturnValue:(BOOL)arg1;
- (BOOL)useInvocationReturnValue;
- (BOOL)handleSelectionForControl:(id)arg1;

@end

