/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class NSDate;

@interface BRInternetAvailabilityMonitor : BRSingleton
{
    BOOL _lastKnownState;
    NSDate *_lastRequestDate;
    BOOL _lastKnownYTState;
    NSDate *_lastYTRequestDate;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (void)dealloc;
- (BOOL)isInternetAvailable;
- (BOOL)isYTAvailable;

@end

