/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

#import "BRTextField-Protocol.h"

@class BRIPv4AddressSelectionLayer, BRTextControl;

@interface BRIPv4AddressEntryControl : BRControl <BRTextField>
{
    BRIPv4AddressSelectionLayer *_addressPicker;
    BRTextControl *_labelLayer;
    struct CGSize _addressPickerSize;
    float _labelPadding;
    id _textFieldDelegate;
}

- (id)init;
- (void)dealloc;
- (struct CGSize)preferredSizeFromScreenSize:(struct CGSize)arg1;
- (void)setDelegate:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setInitialAddress:(id)arg1;
- (void)reset;
- (void)setFrame:(struct CGRect)arg1;
- (BOOL)brEventAction:(id)arg1;
- (id)stringValue;
- (void)setString:(id)arg1;

@end

