/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@interface BRITunesLibraryUtilitiesAccess : BRSingleton
{
    id _utilitiesDelegate;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (void)dealloc;
- (void)setITunesUtilitiesDelegate:(id)arg1;
- (id)fairPlayGUID;
- (id)authorizedAccountsFromSyncedHost;
- (BOOL)musicPlaybackUsesSoundCheck;
- (void)setMusicPlaybackUsesSoundCheck:(BOOL)arg1;
- (id)iTunesCompareAscending:(BOOL)arg1 withKey:(id)arg2 fallbackSortSelector:(SEL)arg3;
- (id)sortStringForString:(id)arg1;
- (id)urlSuitableForPlayback:(id)arg1;

@end

