/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRRomanSquareTextEntryLayoutManager.h>

@interface BRJapaneseHiraganaSquareTextEntryLayoutManager : BRRomanSquareTextEntryLayoutManager
{
}

- (struct CGRect)_candidatesBackgroundFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGRect)_candidatesContainerFrame:(id)arg1 resolutionScale:(float)arg2;
- (struct CGSize)_actionKeysContainerSize;
- (struct CGSize)_mainKeysContainerSize:(id)arg1 resolutionScale:(float)arg2;
- (struct CGSize)_preferredSizeOfLayerWithTab;
- (struct CGSize)_preferredSizeOfLayerWithoutTab;
- (float)_backgroundFrameHeightWithTab;
- (float)_backgroundFrameHeightWithoutTab;

@end

