/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRKeyboard.h>

@interface BRKeyboard (BRKeyboardDataFileHandling)
- (id)_keyboardDataFileName;
- (id)_rawKeyboardData;
- (id)_filterRawKeyboardData:(id)arg1;
- (id)_keyRowData;
- (id)_processGlyphDataChunk:(id)arg1;
- (id)_glyphDataForTextString:(id)arg1 attributes:(id)arg2;
- (id)_glyphDataForStrings:(id)arg1 attributes:(id)arg2;
- (struct CGColor *)_createColorFromDictionary:(id)arg1;
- (id)_glyphDataForImage:(id)arg1;
- (id)_controlForData:(id)arg1;
- (float)_preferredGlyphWidth:(id)arg1;
- (float)_preferredGlyphHeight:(id)arg1;
@end

