/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRKeyboardRomanFull.h>

@class BRButtonControl, BRImageControl;

@interface BRKeyboardRomanWeb : BRKeyboardRomanFull
{
    BRButtonControl *_previousButton;
    BRButtonControl *_nextButton;
    BRButtonControl *_autoFillButton;
    BRButtonControl *_clearButton;
    BRImageControl *_rowDividerImageControl;
}

- (void)dealloc;
- (id)name;
- (id)actionKeyRows;
- (id)bottomRow;
- (id)_keyboardDataFileName;
- (id)customizeTextEntryControls:(id)arg1;
- (id)removeCustomizedTextEntryControls:(id)arg1;
- (void)layoutCustomControls:(id)arg1 resolutionScale:(float)arg2;
- (BOOL)canWrapVertically;
- (id)actionKeysContainer;
- (id)focusedControlAndRow:(id *)arg1;
- (BOOL)popupKeyboardShouldBeRightAlignedForKey:(id)arg1;
- (id)actionDictionaryForCustomControl:(id)arg1;
- (int)_numberOfMainKeyRows;
- (int)_numberOfColumnsForMainKeyRowIndex:(int)arg1;
- (id)_preferredLayoutManagerForMainKeyRow:(id)arg1 index:(int)arg2;
- (struct CGSize)_minTextEntryControlSize:(id)arg1 resolutionScale:(float)arg2;
- (float)_topMostUIElementGap:(id)arg1 resolutionScale:(float)arg2;
- (struct CGSize)_mainKeysContainerSize:(id)arg1 resolutionScale:(float)arg2;
- (float)_mainKeysContainerBaseGap:(id)arg1 resolutionScale:(float)arg2;
- (struct CGSize)_actionKeysContainerSize:(id)arg1 resolutionScale:(float)arg2;
- (float)_actionKeysContainerBaseGap:(id)arg1 resolutionScale:(float)arg2;

@end

