/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRKeyboardNaturalWidthLayoutManager : NSObject
{
    float _preferredControlSpacingValue;
    float _preferredHorizontalMargin;
    float _preferredVerticalMargin;
    BOOL _usePreferredMargins;
}

- (id)init;
- (float)preferredControlSpacingValue;
- (void)setPreferredControlSpacingValue:(float)arg1;
- (void)setUsePreferredMargins:(BOOL)arg1;
- (float)preferredHorizontalMargin;
- (void)setPreferredHorizontalMargin:(float)arg1;
- (float)preferredVerticalMargin;
- (void)setPreferredVerticalMargin:(float)arg1;
- (struct CGSize)preferredSizeOfLayer:(id)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;

@end

