/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRKeyboardRomanSquare.h>

@interface BRKeyboardJapaneseRomanSquare : BRKeyboardRomanSquare
{
}

- (id)name;
- (id)actionKeysContainer;
- (void)setFocusToDefaultSwitchKeyboardGlyph:(id)arg1;
- (id)actionDictionaryForKeyControl:(id)arg1;
- (struct CGSize)_minTextEntryControlSize:(id)arg1 resolutionScale:(float)arg2;
- (float)_topMostUIElementGap:(id)arg1 resolutionScale:(float)arg2;
- (struct CGSize)_actionKeysContainerSize:(id)arg1 resolutionScale:(float)arg2;
- (long)_startingIndexOfActionKeysInKeyRowData;

@end

