/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRListControl;

@interface BRListControlMonitor : NSObject
{
    BRListControl *_listControl;
    struct _NSRange _loadingRange;
    long _dataCount;
}

- (void)dealloc;
- (void)setListControl:(id)arg1;
- (void)cancelCurrentLoads;

@end

