/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRListControl.h>

@interface BRListControl (Providers)
- (void)_hideFirstDividerInDividedProviders:(id)arg1;
- (void)_updateProviders;
- (id)_legacyProvider;
- (id)_findDividerProviderForProvider:(id)arg1;
- (long)_dataIndexFromScrollIndex:(long)arg1;
- (long)_scrollIndexForDataIndex:(long)arg1;
@end

