/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRListControl.h>

@interface BRListControl (Deprecated)
- (void)setDisplaysSelectionWidget:(BOOL)arg1;
- (BOOL)displaysSelectionWidget;
- (void)addDividerAtIndex:(long)arg1 withLabel:(id)arg2;
- (void)removeDividerAtIndex:(long)arg1;
- (void)removeDividers;
- (void)reload;
- (void)setDatasource:(id)arg1;
- (id)datasource;
@end

