/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRListControl.h>

@interface BRListControl (Framing)
- (void)_updateScrollPosition;
- (void)_updateWidgetFrame;
- (void)_updateWidgetFrameForWidget:(id)arg1 withItemFrame:(struct CGRect)arg2;
- (float)_maxWidgetTopGlowHeight;
- (float)_maxWidgetBottomGlowHeight;
- (float)_maxWidgetEdgeGlowWidth;
@end

