/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class NSMutableDictionary, NSString;

@interface BRLocalizedStringManager : BRSingleton
{
    NSString *_currentLanguage;
    NSMutableDictionary *_stringFileCache;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
+ (id)backRowLocalizedStringForKey:(id)arg1 inFile:(id)arg2;
+ (id)applicationLocalizedStringForKey:(id)arg1 inFile:(id)arg2;
+ (id)appliance:(id)arg1 localizedStringForKey:(id)arg2 inFile:(id)arg3;
+ (id)localizedStringForKey:(id)arg1 inFile:(id)arg2 fromBundle:(id)arg3;
+ (id)pathForResource:(id)arg1 ofType:(id)arg2 forBundle:(id)arg3;
- (id)init;
- (void)dealloc;

@end

