/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface BRMappingDictionary : NSObject
{
    NSMutableDictionary *_info;
}

- (id)init;
- (void)dealloc;
- (id)transformedValueForKey:(id)arg1 forObject:(id)arg2;
- (void)setValueTransformer:(id)arg1 forKey:(id)arg2;
- (id)valueTransformerForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)valueForKey:(id)arg1;
- (long)count;
- (id)keyEnumerator;
- (id)objectEnumerator;

@end

