/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageControl, BRTextControl;

@interface BRMainMenuShelfErrorControl : BRControl
{
    BRTextControl *_text;
    BRTextControl *_subtext;
    BRImageControl *_icon;
}

- (id)preferredActionForKey:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)setText:(id)arg1;
- (id)text;
- (void)setSubtext:(id)arg1;
- (id)subtext;
- (void)setIcon:(id)arg1;
- (void)layoutSubcontrols;

@end

