/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

#import "BRApplianceBrowserProtocol-Protocol.h"

@class BRApplianceCategoryListProvider, BRApplianceProvider, BRCursorControl, BRImage, BRImageControl, BRListControl, NSArray, NSDate, NSMutableDictionary, NSTimer;

@interface BRMainMenuControl : BRControl <BRApplianceBrowserProtocol>
{
    int _focusState;
    BRApplianceProvider *_applianceProvider;
    id _currentAppliance;
    NSArray *_columns;
    long _activeColumn;
    float _columnScrollAdjustment;
    long _curPreviewedColumn;
    long _oldPreviewedColumn;
    BRControl *_curPreview;
    BRControl *_oldPreview;
    NSTimer *_previewTimer;
    BRImageControl *_logo;
    BRImageControl *_topGradient;
    BRImageControl *_barGlow;
    BRImage *_barGlowActiveImage;
    BRImage *_barGlowInactiveImage;
    BRControl *_topDivider;
    BRControl *_bottomDivider;
    BRControl *_leftColumnFade;
    BRControl *_rightColumnFade;
    BRCursorControl *_cursor;
    BRListControl *_categoryList;
    BRApplianceCategoryListProvider *_categoryListProvider;
    NSTimer *_menuTimer;
    NSDate *_menuTriggerTime;
    NSMutableDictionary *_remembery;
    BOOL _reloadingCategoryList;
    BOOL _isLoaded;
}

- (id)init;
- (void)dealloc;
- (struct CGSize)preferredFrameSize;
- (id)controllerForCurrentSelection;
- (id)actionForCurrentSelection;
- (void)highlightItemsForController:(id)arg1;
- (void)highlightApplianceWithKey:(id)arg1 andCategoryWithIdentifier:(id)arg2;
- (BOOL)controllerMatchesCurrentSelection:(id)arg1;
- (void)clearRemembery;
- (BOOL)brEventAction:(id)arg1;
- (id)focusedControlForEvent:(id)arg1 focusPoint:(struct CGPoint *)arg2;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)layoutSubcontrols;

@end

