/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerController.h>

@interface BRMediaPlayerController (Queries)
- (id)_photoSet;
- (BOOL)_shouldShowResumeMenu;
- (BOOL)_mediaSupportsSubtitles:(id)arg1;
- (BOOL)_shouldUseMusicContextMenu;
@end

