/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaType.h>

@interface BRMediaType (Private)
+ (id)_defaultImageForMediaType:(id)arg1 forImageSize:(int)arg2;
@end

