/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerManager.h>

@interface BRMediaPlayerManager (Popup)
- (void)_updateTrackPopupForPlayer:(id)arg1;
- (void)_removeTrackPopup;
- (void)_showTrackPopupForPlayer:(id)arg1;
- (void)_showTrackPopupWithDelayForPlayer:(id)arg1;
- (void)_popupDelayTimerFired:(id)arg1;
@end

