/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRTextWithSpinnerController.h>

@class BRController, BRMediaHost;

@interface BRMediaHostConnectionDialog : BRTextWithSpinnerController
{
    BRMediaHost *_mediaHost;
    id _providerNeedingAuth;
    BRController *_controllerUnderneath;
    BOOL _timerSatisfied;
    BOOL _wasBuried;
    BOOL _passwordWasEntered;
    BOOL _authAlreadyAttempted;
}

- (id)initWithHost:(id)arg1;
- (void)dealloc;
- (void)setMediaHost:(id)arg1;
- (id)mediaHost;
- (BOOL)brEventAction:(id)arg1;
- (void)wasPushed;
- (void)wasBuried;
- (void)textDidChange:(id)arg1;
- (void)textDidEndEditing:(id)arg1;

@end

