/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@class NSMutableDictionary;

@interface BRMenuSavedState : BRSingleton
{
    NSMutableDictionary *_cachedMenuState;
    BOOL _enabled;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
+ (void)saveSelection:(id)arg1 atIndex:(id)arg2 forOwnerKey:(id)arg3;
+ (void)clearSavedSelectionForOwnerKey:(id)arg1;
+ (id)selectionInfoForOwnerKey:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)purge;
- (BOOL)enabled;
- (void)setEnabled:(BOOL)arg1;

@end

