/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRControlFactory-Protocol.h"

@class BRMediaType;

@interface BRMediaPreviewControlFactory : NSObject <BRControlFactory>
{
    BRMediaType *_missingType;
    BOOL _deletterboxArtwork;
    BOOL _shouldShowMetadata;
    BOOL _showMetadataImmediately;
}

+ (id)factory;
- (id)init;
- (void)dealloc;
- (id)previewControlForAsset:(id)arg1;
- (id)previewControlForImageProxy:(id)arg1;
- (id)previewControlForAssets:(id)arg1;
- (id)previewControlForImageProxies:(id)arg1;
- (void)setMissingType:(id)arg1;
- (id)missingType;
- (void)setPreviewShouldShowMetadata:(BOOL)arg1;
- (BOOL)previewShouldShowMetadata;
- (void)setPreviewShouldShowMetadataImmediately:(BOOL)arg1;
- (BOOL)previewShouldShowMetadataImmediately;
- (void)setShouldDeletterboxArtwork:(BOOL)arg1;
- (BOOL)shouldDeletterboxArtwork;
- (id)controlForData:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;

@end

