/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRMediaCollectionGeniusInfo : NSObject
{
}

+ (void)setImplementationClass:(Class)arg1;
+ (id)geniusInfoForGeniusPlaylist:(id)arg1;
+ (BOOL)isGeniusDBAvailable;
- (id)initWithGeniusPlaylist:(id)arg1;
- (BOOL)assetIsCurrentSeed:(id)arg1;
- (BOOL)assetIsValidSeed:(id)arg1;
- (BOOL)setGeniusSeed:(id)arg1;
- (BOOL)refreshGeniusPlaylist;
- (id)saveGeniusPlaylist;
- (BOOL)playlistIsDirty;

@end

