/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMenuController.h>

@interface BRMenuController (Deprecated)
- (void)setSelectedItem:(long)arg1;
- (long)selectedItem;
- (long)itemCount;
- (void)itemSelected:(long)arg1;
- (long)defaultIndex;
- (int)soundForSelectingItem:(long)arg1;
- (BOOL)_itemSelected:(id)arg1;
- (BOOL)isVolatile;
@end

