/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRController.h>

@class BRHeaderControl, BRListControl, BRListControlMonitor, BRTextControl;

@interface BRMenuController : BRController
{
    BRListControl *_list;
    BRHeaderControl *_header;
    id _selectedObject;
    BOOL _clearSavedSelection;
    BRListControlMonitor *_listControlMonitor;
    float _menuWidthFactor;
    float _headerWidthFactor;
    BOOL _useCenteredLayout;
    BRTextControl *_primaryTextControl;
    BRTextControl *_secondaryTextControl;
    BRTextControl *_labelControl;
}

- (id)init;
- (void)dealloc;
- (void)layoutSubcontrols;
- (id)list;
- (void)setMenuWidthFactor:(float)arg1;
- (float)menuWidthFactor;
- (id)header;
- (void)setHeaderWidthFactor:(float)arg1;
- (float)headerWidthFactor;
- (void)clearSavedSelection;
- (void)controlWasActivated;
- (void)wasPushed;
- (void)setSelectedObject:(id)arg1;
- (id)selectedObject;
- (id)loadModelData;
- (void)refreshControllerForModelUpdate;
- (void)refreshControllerForModelUpdateToObject:(id)arg1;
- (BOOL)isCurrentSelectionValidForModelData:(id)arg1;
- (BOOL)shouldRefreshForUpdateToObject:(id)arg1;
- (BOOL)isValidAfterDataUpdate;
- (void)cancelCurrentListMonitorLoads;
- (void)setUseCenteredLayout:(BOOL)arg1;

@end

