/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaMenuController.h>

@interface BRMediaMenuController (ControlManagement)
- (void)_updatePreview;
- (void)_updateControls;
- (void)_setDislaysActionControl:(BOOL)arg1;
- (void)_updateActionControl;
@end

