/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class NSArray;

@interface BRMetadataLinesLayer : BRControl
{
    NSArray *_lineLayers;
    float _lineHeight;
}

- (id)init;
- (void)dealloc;
- (void)setMetadataValues:(id)arg1 withLabels:(id)arg2 frameWidth:(float)arg3 maxHeight:(float)arg4;

@end

