/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayer.h>

@interface BRMediaPlayer (CollectionSupport)
- (void)setShufflePlayback:(BOOL)arg1;
- (BOOL)shufflePlayback;
- (BOOL)supportsShufflePlayback;
- (void)setRepeatMode:(int)arg1;
- (int)repeatMode;
- (BOOL)supportsRepeatModes;
- (void)setSkipExplicit:(BOOL)arg1;
- (BOOL)skipExplicit;
- (void)previousMedia;
- (void)nextMedia;
@end

