/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRDividerControl, BRImageControl, BRMetadataLinesLayer, BRTextControl, NSArray;

@interface BRMetadataControl : BRControl
{
    BRTextControl *_titleLayer;
    BRImageControl *_ratingImageLayer;
    BRImageControl *_starRatingImageLayer;
    BRImageControl *_topRightImageLayer;
    BRTextControl *_summaryLayer;
    BRMetadataLinesLayer *_metadataLinesLayer;
    BRTextControl *_copyrightLayer;
    BRDividerControl *_topDividerLayer;
    BRDividerControl *_middleDividerLayer;
    BRDividerControl *_bottomDividerLayer;
    NSArray *_metadataObjs;
    NSArray *_metadataLabels;
    float _totalHeight;
    int _alignment;
}

- (id)init;
- (void)dealloc;
- (void)resetAllFields;
- (void)setTitle:(id)arg1;
- (void)setRating:(id)arg1;
- (void)setStarRating:(id)arg1;
- (id)topRightImageControl;
- (void)setTopRightImage:(id)arg1;
- (void)setSummary:(id)arg1;
- (void)setMetadata:(id)arg1 withLabels:(id)arg2;
- (void)setCopyright:(id)arg1;
- (struct CGSize)renderedSize;
- (void)layoutSubcontrols;
- (void)setAlignment:(int)arg1;

@end

