/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayer.h>

@interface BRMediaPlayer (StateStack)
- (void)pushState:(int)arg1;
- (int)swapState:(int)arg1;
- (int)peekState;
- (int)popState;
- (void)clearStack;
@end

