/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayer.h>

@interface BRMediaPlayer (VolumeControls)
- (void)setMuted:(BOOL)arg1;
- (BOOL)muted;
- (BOOL)supportsVolumeControl;
- (void)setVolume:(float)arg1;
- (float)volume;
@end

