/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRMediaCollectionGeniusMixInfo : NSObject
{
}

+ (void)setImplementationClass:(Class)arg1;
+ (id)geniusMixInfoForGeniusMix:(id)arg1;
- (id)initWithGeniusMix:(id)arg1;
- (id)basedOnText;
- (BOOL)isValid;
- (id)images;
- (id)generatedImage;
- (void)setGeneratedImage:(id)arg1;

@end

