/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRType.h>

@interface BRMediaCollectionType : BRType
{
}

+ (id)unknown;
+ (id)iTunesPlaylist;
+ (id)iTunesSmartPlaylist;
+ (id)iTunesPurchasesPlaylist;
+ (id)iTunesFolderPlaylist;
+ (id)iTunesInternetRadioPlaylist;
+ (id)iTunesMainGeniusPlaylist;
+ (id)iTunesGeniusMix;
+ (id)iTunesSavedGeniusPlaylist;
+ (id)iTunesMainOnTheGoPlaylist;
+ (id)iTunesSavedOnTheGoPlaylist;
+ (id)iTunesAlbum;
+ (id)iTunesArtist;
+ (id)iPhotoSlideshow;
+ (id)iPhotoAlbum;
+ (id)iPhotoEvent;
+ (id)iPhotoFaces;
+ (id)iPhotoFolder;
+ (id)movieTrailer;
+ (id)podcastCollection;
+ (id)podcastSubscriptionCollection;
+ (id)video;
+ (id)videoSlideshow;
+ (id)compoundITunesAlbum;
+ (id)compoundITunesArtist;
+ (id)genre;
+ (id)composer;
+ (id)playlistCollectionTypes;
+ (id)onTheGoCollectionTypes;
+ (id)photoCollectionTypes;
- (id)description;
- (int)playlistTypeCompare:(id)arg1;

@end

