/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPreviewControlFactory.h>

@interface BRMediaPreviewControlFactory (Private)
- (id)_coverArtControllerForAssets:(id)arg1;
- (id)_metadataControllerForAsset:(id)arg1;
- (id)_paradeControllerForAssets:(id)arg1;
@end

