/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRMediaAssetExpiryInfo : NSObject
{
    id _mediaAsset;
}

+ (void)setImplementationClass:(Class)arg1;
+ (id)expiryInfoForMediaAsset:(id)arg1;
- (id)initWithMediaAsset:(id)arg1;
- (id)asset;
- (void)dealloc;
- (BOOL)isExpired;
- (id)expiryDate;
- (void)setExpiryDate:(id)arg1;
- (unsigned int)rentalPlaybackDuration;
- (int)compare:(id)arg1;
- (id)expiryDescription;
- (id)rentalPlaybackDurationDescription;

@end

