/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerController.h>

@interface BRMediaPlayerController (VolumeWarning)
- (BOOL)_shouldRestoreVolume;
- (BOOL)_shouldShowVolumeWarning;
- (void)_volumeWarningDismissed:(id)arg1;
@end

