/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaShareListController.h>

@interface BRMediaShareListController (ShareMounting)
- (void)_mountHost:(id)arg1;
- (void)_checkMountStatus:(id)arg1;
- (void)_unmountStreamingHostsExcludingHost:(id)arg1;
- (BOOL)_isHostValid:(id)arg1;
@end

