/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaShelfControl.h>

@interface BRMediaShelfControl (InternalDividerSupport)
- (long)_groupCountIgnoringDividers;
- (struct _NSRange)_dividedRangeForRange:(struct _NSRange)arg1 andDirection:(int)arg2;
- (unsigned int)_dividerCountInRange:(struct _NSRange)arg1;
- (BOOL)_isDividerAtIndex:(long)arg1;
- (void)_hideFirstDividerInDividedProviders:(id)arg1;
- (long)_dividedProviderIndexForProvider:(id)arg1;
@end

