/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMenuController.h>

@interface BRMenuController (CenteredMenuLayout)
- (void)layoutSubcontrolsUsingCenteredLayout;
- (void)setTitle:(id)arg1;
- (void)setIcon:(id)arg1 horizontalOffset:(float)arg2 kerningFactor:(float)arg3;
- (void)setPrimaryInfoText:(id)arg1;
- (void)setPrimaryInfoText:(id)arg1 withAttributes:(id)arg2;
- (id)primaryInfoTextControl;
- (void)setSecondaryInfoText:(id)arg1;
- (void)setSecondaryInfoText:(id)arg1 withAttributes:(id)arg2;
- (id)secondaryInfoTextControl;
- (void)setLabel:(id)arg1;
- (void)setLabel:(id)arg1 withAttributes:(id)arg2;
@end

