/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRType.h>

@interface BRMediaType : BRType
{
    BRMediaType *_derivedFrom;
}

+ (void)initialize;
+ (id)song;
+ (id)songPreview;
+ (id)cdSong;
+ (id)musicVideo;
+ (id)musicVideoPreview;
+ (id)podcast;
+ (id)podcastSubscription;
+ (id)movie;
+ (id)dvd;
+ (id)moviePreview;
+ (id)TVShow;
+ (id)TVShowPreview;
+ (id)audioBook;
+ (id)movieTrailer;
+ (id)ytVideo;
+ (id)booklet;
+ (id)interactiveBooklet;
+ (id)coachedAudio;
+ (id)photo;
+ (id)internetPhoto;
+ (id)dotMacPhoto;
+ (id)flikrPhoto;
+ (id)storeRentalMovie;
+ (id)demoRentalMovie;
+ (id)dotMacVideo;
+ (id)dotMacVideoSlideshow;
+ (id)streamingPodcast;
+ (id)radioStation;
+ (id)syncedInternetRadioStation;
+ (id)internetRadioStation;
+ (id)airTunes;
+ (id)downloadSpeedTest;
+ (id)iTunesExtras;
+ (id)iTunesLP;
+ (id)storeMediaTypes;
+ (id)internetPhotoMediaTypes;
+ (id)onTheGoMediaTypes;
+ (id)unchapteredTypes;
+ (id)defaultImageForMediaType:(id)arg1 forImageSize:(int)arg2;
+ (id)storeMediaTypeStringForMediaType:(id)arg1;
- (void)dealloc;
- (id)description;
- (void)setParentType:(id)arg1;
- (id)parentType;
- (BOOL)isKindOfMediaType:(id)arg1;

@end

