/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaPlayerManager.h>

@interface BRMediaPlayerManager (ShroudWindow)
- (void)_addShroudWindowWithSelector:(SEL)arg1;
- (void)_removeShroudWindowWithAnimation;
- (void)_safetyTimerFired:(id)arg1;
- (void)_removeShroudWindow;
@end

