/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface BRMediaHostEvent : NSObject
{
    NSString *_description;
}

+ (id)mediaProviderAdded;
+ (id)mediaProviderRemoved;
+ (id)mediaHostReady;
+ (id)mediaProviderLoaded;
+ (id)mediaProviderLoadFailed;
+ (id)mediaProviderUnloading;
+ (id)mediaProviderUnloaded;
+ (id)reset;
+ (id)mount;
+ (id)unmount;
+ (id)remove;
- (id)initWithDescription:(id)arg1;
- (void)dealloc;
- (id)description;

@end

