/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRMediaAccessUtilities : NSObject
{
}

+ (id)uniqueAlbumsForTracks:(id)arg1;
+ (id)allowedMusicMediaTypesPredicate;
+ (id)oldestUnwatchedAssetInCollection:(id)arg1;
+ (id)oldestUnwatchedAssetInArray:(id)arg1;

@end

