/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BRMediaProvider <NSObject>
- (id)providerID;
- (id)machineID;
- (id)providerName;
- (id)objectsWithEntityName:(id)arg1 qualifiedByPredicate:(id)arg2 sortDescriptors:(id)arg3 error:(id *)arg4;
- (id)objectsWithEntityName:(id)arg1 qualifiedByPredicate:(id)arg2 sortDescriptors:(id)arg3 excludeHiddenObjects:(BOOL)arg4 error:(id *)arg5;
- (long)countOfObjectsWithMediaType:(id)arg1;
- (int)status;
- (id)mediaTypes;
- (BOOL)autoload;
- (void)reset;
- (BOOL)isPasswordProtected;
- (void)setIsPasswordProtected:(BOOL)arg1;
- (void)flush;
@end

