/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRHeaderControl, BRListControl, NSTimer;

@interface BRMediaListControl : BRControl
{
    BRListControl *_list;
    BRHeaderControl *_header;
    BRControl *_preview;
    float _previewDelay;
    NSTimer *_previewDelayTimer;
}

- (id)init;
- (void)dealloc;
- (void)layoutSubcontrols;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)setListProviders:(id)arg1;
- (id)listProviders;
- (void)setListSelectionHandler:(id)arg1;
- (id)listSelectionHandler;
- (void)setTitle:(id)arg1;
- (id)title;
- (void)updatePreview;
- (id)listProviderRequester;
- (void)setSelection:(long)arg1;
- (long)selection;
- (long)itemCount;
- (void)reload;

@end

