/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMovieTrailersProvider.h>

@interface BRMovieTrailersProvider (Private)
- (void)_loadTrailers;
- (void)_postLoadedNotification:(id)arg1;
- (void)_loadTrailersWithResolution:(id)arg1 forURL:(id)arg2;
@end

