/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBaseMediaCollection.h>

@class NSMutableArray;

@interface BRMovieTrailerCollection : BRBaseMediaCollection
{
    NSMutableArray *_mediaAssets;
}

- (id)initWithMediaProvider:(id)arg1;
- (void)dealloc;
- (id)collectionType;
- (id)collectionID;
- (id)coverArt;
- (BOOL)hasCoverArt;
- (void)addObject:(id)arg1;
- (int)count;
- (id)mediaAssets;
- (BOOL)isCompilation;
- (id)artist;
- (id)artistForSorting;
- (id)title;
- (id)titleForSorting;
- (long)duration;
- (id)mediaType;
- (BOOL)isLocal;
- (id)primaryGenre;

@end

