/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMusicNowPlayingControl.h>

@interface BRMusicNowPlayingControl (Notifications_And_Timers)
- (void)_playbackAssetChanged:(id)arg1;
- (void)_playlistChanged:(id)arg1;
- (void)_updateCoverArt:(id)arg1;
- (void)_chapterPictureChanged:(id)arg1;
- (void)_playbackProgressChanged:(id)arg1;
- (void)_flipNow:(id)arg1;
- (void)_unblockAssetChangeAnimation:(id)arg1;
- (void)_radioBufferingStart:(id)arg1;
- (void)_radioBufferingEnd:(id)arg1;
- (void)_shuffleModeChanged:(id)arg1;
- (void)_repeatModeChanged:(id)arg1;
- (void)_setTransitionDirection:(id)arg1;
@end

