/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBaseMenuItemLayerPopulator.h>

@interface BRMusicVideoMenuItemPopulator : BRBaseMenuItemLayerPopulator
{
}

+ (BOOL)canHandleObject:(id)arg1;
- (id)menuItemLayer;
- (id)textMenuItemLayer;
- (id)textImageMenuItemLayer;
- (float)menuItemHeightForObject:(id)arg1 delegate:(id)arg2;
- (id)_textMenuItemLayerWithIconInfo:(id)arg1 dimmed:(BOOL)arg2 showWaitSpinner:(BOOL)arg3;
- (id)_textImageMenuItemLayerWithIconInfo:(id)arg1 dimmed:(BOOL)arg2 showWaitSpinner:(BOOL)arg3;
- (id)_videoIconInfoDictionaryWithYFactor:(float)arg1;

@end

