/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRContextMenuUtility-Protocol.h"

@interface BRMusicContextMenuUtility : NSObject <BRContextMenuUtility>
{
    BOOL _onTheGoEnabled;
    BOOL _startGeniusEnabled;
    BOOL _airTunesSettingsEnabled;
    BOOL _browseArtistEnabled;
    BOOL _browseAlbumEnabled;
    BOOL _navigateToArtistForBrowseArtist;
    BOOL _navigateToAlbumForBrowseAlbum;
}

+ (id)utility;
+ (void)setImplementationClass:(Class)arg1;
- (id)init;
- (void)setOnTheGoEnabled:(BOOL)arg1;
- (void)setStartGeniusEnabled:(BOOL)arg1;
- (void)setAirTunesSettingsEnabled:(BOOL)arg1;
- (void)setBrowseArtistEnabled:(BOOL)arg1;
- (void)setBrowseAlbumEnabled:(BOOL)arg1;
- (void)setNavigateToArtistForBrowseArtist:(BOOL)arg1;
- (void)setNavigateToAlbumForBrowseAlbum:(BOOL)arg1;
- (id)contextMenuProviderForObject:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
- (void)handleSelectionForObject:(id)arg1 sender:(id)arg2 context:(id)arg3;

@end

