/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRAlertController.h>

@interface BRNetworkAlertController : BRAlertController
{
}

- (id)initWithType:(int)arg1 titled:(id)arg2 primaryText:(id)arg3 secondaryText:(id)arg4;
- (void)dealloc;
- (void)_networkStatusChanged:(id)arg1;

@end

