/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@interface BRNinePartWidgetLayer : BRControl
{
    BOOL _suppressAnimations;
    BRControl *_ninePartControls[10];
}

- (id)init;
- (void)setTopRightCorner:(id)arg1;
- (void)setTopLeftCorner:(id)arg1;
- (void)setBottomRightCorner:(id)arg1;
- (void)setBottomLeftCorner:(id)arg1;
- (void)setRightEdge:(id)arg1;
- (void)setLeftEdge:(id)arg1;
- (void)setTopEdge:(id)arg1;
- (void)setBottomEdge:(id)arg1;
- (void)setImageMap:(const struct BRNinePartImageMap *)arg1 forBundle:(id)arg2;
- (void)setCenter:(id)arg1;
- (struct CGSize)edgeSize;
- (void)setCenterOverlapFactor:(float)arg1;
- (void)setSuppressAnimations:(BOOL)arg1;
- (void)layoutSubcontrols;

@end

