/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRNinePartWidgetLayer.h>

@interface BRNinePartWidgetLayer (Private)
+ (void)_setAntialiasingFlagsForLayer:(int)arg1 control:(id)arg2;
- (id)_defaultActions;
- (void)_updateImage:(id)arg1 forLayer:(int)arg2;
@end

