/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMenuController.h>

@class NSDictionary, NSMutableArray, NSString;

@interface BROptionDialog : BRMenuController
{
    NSString *_tag;
    int _currentSelection;
    NSDictionary *_userInfo;
    NSMutableArray *_options;
    id _delegate;
    SEL _actionSelector;
}

- (id)init;
- (void)dealloc;
- (void)setActionSelector:(SEL)arg1 target:(id)arg2;
- (void)addOptionText:(id)arg1;
- (void)addOptionText:(id)arg1 isDefault:(BOOL)arg2;
- (id)selectedText;
- (long)selectedIndex;
- (void)setTag:(id)arg1;
- (id)tag;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;

@end

