/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BROptionDialog.h>

@interface BROptionAlertControl : BROptionDialog
{
    long _cancelIdx;
}

+ (int)postAlertWithTitleAndCancel:(id)arg1 primaryText:(id)arg2 secondaryText:(id)arg3 firstButton:(id)arg4 secondButton:(id)arg5 thirdButton:(id)arg6 defaultFocus:(int)arg7 identifier:(id)arg8 cancelIndex:(int)arg9;
+ (int)postAlertWithTitle:(id)arg1 primaryText:(id)arg2 secondaryText:(id)arg3 firstButton:(id)arg4 secondButton:(id)arg5 thirdButton:(id)arg6 defaultFocus:(int)arg7;
+ (void)postError:(id)arg1;
+ (int)postDeleteConfirmationWithName:(id)arg1;
- (void)setCancelIndex:(long)arg1;
- (BOOL)brEventAction:(id)arg1;

@end

