/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageControl, BRPasscodeSelectionWidget, BRTextControl, NSArray;

@interface BRPasscodeSelectionLayer : BRControl
{
    NSArray *_backgroundLayers;
    NSArray *_digitLayers;
    NSArray *_bulletLayers;
    BRImageControl *_arrowsLayer;
    BRPasscodeSelectionWidget *_selectionWidget;
    BRTextControl *_doneLayer;
    BOOL _isUserEditable;
    unsigned int _numDigits;
    BOOL _hideDigits;
    int _selection;
}

- (id)initWithNumDigits:(unsigned int)arg1 userEditable:(BOOL)arg2 hideDigits:(BOOL)arg3;
- (void)dealloc;
- (struct CGRect)preferredFrameForScreenSize:(struct CGSize)arg1;
- (float)widthOfDigitsForScreenSize:(struct CGSize)arg1;
- (BOOL)moveSelectionRight;
- (BOOL)moveSelectionLeft;
- (BOOL)incrementSelection;
- (BOOL)decrementSelection;
- (BOOL)setSelection:(int)arg1;
- (id)passcode;
- (void)setPasscode:(id)arg1;
- (BOOL)doneButtonSelected;
- (void)reset;
- (void)setFrame:(struct CGRect)arg1;
- (BOOL)digitsHidden;
- (void)hideDigits:(int)arg1;

@end

