/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPhotoBrowserController.h>

@interface BRPhotoBrowserController (NotificationHandlers)
- (void)_focusChanged:(id)arg1;
- (void)_providerUpdated:(id)arg1;
- (void)_playerAssetChanged:(id)arg1;
- (void)_playerStateChanged:(id)arg1;
@end

