/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRDividerControl, BRImageControl, BRTextControl, NSString;

@interface BRPhotoBrowserHeaderControl : BRControl
{
    BRTextControl *_titleControl;
    BRTextControl *_subtitleControl;
    BRImageControl *_icon;
    BRDividerControl *_divider;
    NSString *_title;
    long _count;
    BOOL _displaysCount;
    float _iconVerticalOffset;
}

- (id)photoBrowserHeader;
- (id)init;
- (void)dealloc;
- (void)setTitle:(id)arg1;
- (id)title;
- (void)setCount:(long)arg1;
- (long)count;
- (void)setDisplaysCount:(BOOL)arg1;
- (BOOL)displaysCount;
- (void)setSubtitle:(id)arg1;
- (id)subtitle;
- (void)setIcon:(id)arg1;
- (id)icon;
- (void)setIconVerticalOffset:(float)arg1;
- (float)iconVerticalOffset;
- (void)setDividerBrightness:(float)arg1;
- (float)dividerBrightness;
- (struct CGSize)preferredFrameSize;
- (void)layoutSubcontrols;

@end

