/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRDataStore.h>

@class BRPhotoMediaCollection;

@interface BRPhotoCollectionDataStore : BRDataStore
{
    BRPhotoMediaCollection *_collection;
}

+ (id)dataStoreWithCollection:(id)arg1;
- (id)initWithPhotoCollection:(id)arg1;
- (void)dealloc;
- (id)collection;
- (BOOL)storeAppliesToObject:(id)arg1;
- (id)data;

@end

