/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPhotoPlayer.h>

@interface BRPhotoPlayer (PlaybackControl)
- (void)_setNewMedia:(id)arg1;
- (void)_setNewState:(int)arg1;
- (BOOL)_handleStopActionWithError:(id *)arg1;
- (BOOL)_handlePauseActionWithError:(id *)arg1;
- (BOOL)_handlePlayActionWithError:(id *)arg1;
@end

