/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPhotoImageProxy.h>

@class NSString;

@interface BRPhotoSubImageProxy : BRPhotoImageProxy
{
    struct CGRect _rect;
    NSString *_rectString;
    int _requestedImageSize;
}

+ (id)imageProxyWithAsset:(id)arg1 rect:(struct CGRect)arg2;
- (id)initWithAsset:(id)arg1 rect:(struct CGRect)arg2;
- (void)dealloc;
- (id)imageIDForImageSize:(int)arg1;
- (id)imageForImageSize:(int)arg1;

@end

