/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPhotoPlayer.h>

@interface BRPhotoPlayer (PhotoConnection)
- (long)_performPhotoConnectionCommand:(int)arg1;
- (void)_setPhotoConnection:(id)arg1;
- (void)_photoSlideshowDidEnd:(id)arg1;
- (void)_photoSlideshowDidEndMainThread;
- (void)_slideshowSettingsUpdated:(id)arg1;
@end

