/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPhotoConnectionUtility.h>

@interface BRPhotoConnectionUtility (PhotoConnectionCreationHelpers)
- (id)_photoConnectionWithDelegate:(id)arg1;
- (id)_albumDictionary;
- (id)_generateiPhotoCollectionDictionaryWithImageCount:(long)arg1 slides:(id)arg2;
- (id)_generateMasterImageDictionaryFromAssets:(id)arg1 slides:(id)arg2;
- (id)_collectionPlaybackOptions;
@end

