/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRControlFactory-Protocol.h"
#import "BRControlHeightFactory-Protocol.h"

@class BRMediaType, NSSet;

@interface BRPlaylistsControlFactory : NSObject <BRControlFactory, BRControlHeightFactory>
{
    BOOL _showMetadata;
    BRMediaType *_missingType;
    NSSet *_mediaTypes;
    BOOL _useMultilineItems;
    BOOL _showIconForVideo;
    BOOL _resolveArtworkFromParent;
}

+ (id)factoryWithMissingType:(id)arg1 mediaTypes:(id)arg2 showMetadata:(BOOL)arg3;
+ (id)factoryWithMissingType:(id)arg1 mediaTypes:(id)arg2 showMetadata:(BOOL)arg3 resolveArtworkFromParentCollections:(BOOL)arg4;
- (id)initWithMissingType:(id)arg1 mediaTypes:(id)arg2 showMetadata:(BOOL)arg3;
- (id)initWithMissingType:(id)arg1 mediaTypes:(id)arg2 showMetadata:(BOOL)arg3 resolveArtworkFromParentCollections:(BOOL)arg4;
- (void)dealloc;
- (id)controlForData:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (float)heightForControlForData:(id)arg1 requestedBy:(id)arg2;
- (id)mediaTypes;
- (void)setShouldUseMultilineItems:(BOOL)arg1;
- (BOOL)shouldUseMultilineItems;
- (void)setShowIconForVideo:(BOOL)arg1;
- (BOOL)showIconForVideo;

@end

