/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPodcastMenuController.h>

@interface BRPodcastMenuController (Private)
- (id)_mediaProvider;
- (BOOL)_hasUnplayedShows:(id)arg1;
- (id)_displayNameForItem:(id)arg1;
- (id)_hashNameForItem:(id)arg1;
- (id)_unplayedTitles;
- (void)_resetUnplayedTitles;
- (void)_aggregateCollections:(id)arg1 aggregate:(id)arg2;
- (id)_headerRows;
- (id)_buildPlaylistsMenu;
- (id)_playlistsParade;
@end

