/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMediaMenuController.h>

#import "BRMenuListItemProvider-Protocol.h"

@class BRMetadataPreviewControl, NSArray, NSMutableArray;

@interface BRPodcastMenuController : BRMediaMenuController <BRMenuListItemProvider>
{
    NSArray *_assets;
    NSArray *_collection;
    NSArray *_collections;
    NSMutableArray *_titlesWithUnplayedContent;
    BRMetadataPreviewControl *_cachedPreviewController;
    NSArray *_headerRows;
}

- (id)initWithPodcastCollection:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)collections;
- (void)setCollections:(id)arg1;
- (id)collection;
- (BOOL)isVolatile;
- (BOOL)shouldRefreshForUpdateToObject:(id)arg1;
- (void)refreshControllerForModelUpdateToObject:(id)arg1;
- (id)loadModelData;
- (long)errorNumberForNoContent;
- (void)refreshControllerForModelUpdate;
- (void)setAssets:(id)arg1;
- (id)assets;
- (void)controlWasActivated;
- (void)wasPopped;
- (void)itemSelected:(long)arg1;
- (id)actionSelectionHandlerForItemAtIndex:(long)arg1;
- (id)actionItemAtIndex:(long)arg1;
- (id)itemForRow:(long)arg1;
- (long)itemCount;
- (id)titleForRow:(long)arg1;
- (float)heightForRow:(long)arg1;
- (BOOL)rowSelectable:(long)arg1;
- (id)previewControlForItem:(long)arg1;
- (long)defaultIndex;

@end

