/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPosterControl.h>

@interface BRPosterControl (DeferredArtworkLoading)
- (void)_setFinalFormImage:(id)arg1;
- (void)_setFinalFormImage:(id)arg1 needsLayout:(BOOL)arg2;
- (id)_fetchImage;
- (void)_startImageProcessingTaskForImage:(id)arg1;
- (void)_startDeletterboxTaskForImage:(id)arg1;
- (id)_getImageFromImageManagerNamed:(id)arg1 withSize:(struct CGSize)arg2;
- (void)_updateDeferredArtwork;
- (void)_delayedFinalFormSetting:(id)arg1;
- (BOOL)_usesDeferredArtworkLoading;
@end

