/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface BRProviderGroup : NSObject
{
    NSArray *_providers;
}

+ (id)groupWithProviders:(id)arg1;
- (id)initWithProviders:(id)arg1;
- (void)dealloc;
- (id)providers;
- (long)dataCount;
- (id)dataForGroupIndex:(long)arg1;
- (id)hashForDataAtGroupIndex:(long)arg1;
- (id)providerForDataAtGroupIndex:(long)arg1 providerIndex:(long *)arg2;
- (long)groupIndexForHash:(id)arg1;
- (id)createControlAtGroupIndex:(long)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (id)createControlsInGroupRange:(struct _NSRange)arg1 requestedBy:(id)arg2;

@end

