/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRPreferenceManager.h>

@interface BRPreferenceManager (PrivateMethods)
+ (void)_flushDiskChanges;
- (void)_setValue:(id)arg1 forKey:(id)arg2 forDomain:(id)arg3;
- (id)_valueForKey:(id)arg1 forDomain:(id)arg2;
- (void)_markPreferencesAsDirty;
- (void)_flushPreferences:(id)arg1;
- (void)_applicationTerminating:(id)arg1;
- (void)_backgroundTasksSuspending:(id)arg1;
- (void)_diskWillBeFlushed:(id)arg1;
- (void)_synchronizeDomains;
@end

