/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRQTKitVideoPlayer.h>

@interface BRQTKitVideoPlayer (DataHandler)
- (BOOL)_setupDataHandler;
- (void)_byteRangeRequestCompleted:(id)arg1;
- (void)_setRingBufferEnabled:(BOOL)arg1;
@end

