/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRRadioMenuItemPopulator.h>

@interface BRRadioMenuItemPopulator (Private)
- (id)_textMenuItemLayerWithIconInfo:(id)arg1 dimmed:(BOOL)arg2;
- (id)_textImageMenuItemLayerWithIconInfo:(id)arg1 dimmed:(BOOL)arg2;
@end

