/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRRenderer.h>

@interface BRRenderer (Private)
- (void)_updateContextAndSize;
- (void)_displayConfigurationEnd:(id)arg1;
- (void)_displayConfigurationBegin:(id)arg1;
@end

