/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRRenderContext;

@interface BRRenderTarget : NSObject
{
    BRRenderContext *_persistent;
}

- (void)dealloc;
- (struct CGSize)renderingSize;
- (id)persistentContext;
- (id)startRenderingOnDisplay:(struct _CGDirectDisplayID *)arg1;
- (struct _CGDirectDisplayID *)display;

@end

