/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRImageControl, BRReflectionControl;

@interface BRReflectedImageControl : BRControl
{
    BRImageControl *_image;
    BRReflectionControl *_reflection;
    float _offset;
}

- (id)init;
- (void)dealloc;
- (void)setImage:(id)arg1;
- (void)setAutomaticDownsample:(BOOL)arg1;
- (BOOL)automaticDownsample;
- (id)image;
- (void)setReflectionOffset:(float)arg1;
- (float)reflectionOffset;
- (void)setImageBorderWidth:(float)arg1;
- (float)imageBorderWidth;
- (void)setImageBorderColor:(struct CGColor *)arg1;
- (struct CGColor *)imageBorderColor;
- (struct CGRect)reflectedImageFrameForImageFrame:(struct CGRect)arg1 reflectionAmount:(float)arg2;
- (void)layoutSubcontrols;

@end

