/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRProvider-Protocol.h"

@class NSArray, NSSet;

@interface BRRecentAlbumsProvider : NSObject <BRProvider>
{
    long _maxCount;
    long _dataCount;
    id _controlFactory;
    NSArray *_data;
    NSSet *_musicTypes;
    BOOL _invalidateOnValidityCheck;
}

- (id)initWithControlFactory:(id)arg1 maxCount:(long)arg2;
- (void)dealloc;
- (id)controlFactory;
- (long)dataCount;
- (id)dataAtIndex:(long)arg1;
- (id)hashForDataAtIndex:(long)arg1;

@end

