/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRRenderDisplayLink : NSObject
{
    id _delegate;
    struct _CGDirectDisplayID *_display;
    struct __CVDisplayLink *_link;
    BOOL _stopFakeThread;
    BOOL _fakeThreadRunning;
    BOOL _running;
}

- (void)dealloc;
- (id)initWithDisplay:(struct _CGDirectDisplayID *)arg1;
- (struct _CGDirectDisplayID *)display;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)setLinkRunning:(BOOL)arg1;
- (BOOL)linkRunning;

@end

