/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRRomanSquareTextEntryLayoutManager.h>

@interface BRRomanSquareTextEntryLayoutManager (BRRomanSquareLayoutManagerProtected)
- (struct CGSize)_preferredSizeOfLayerWithTab;
- (struct CGSize)_preferredSizeOfLayerWithoutTab;
- (float)_backgroundFrameHeightWithTab;
- (float)_backgroundFrameHeightWithoutTab;
- (struct CGSize)_actionKeysContainerSize;
- (struct CGSize)_mainKeysContainerSize;
- (struct CGRect)_tabControlFrame:(id)arg1;
- (struct CGRect)_magnifyingGlassFrame:(id)arg1;
- (struct CGRect)_spinnerFrame:(id)arg1;
@end

