/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRBaseMetadataPopulator.h>

@interface BRRSSMetadataPopulator : BRBaseMetadataPopulator
{
}

- (void)populateMetadataLabels:(id *)arg1 andValues:(id *)arg2 forAsset:(id)arg3;

@end

