/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class NSAttributedString;

@interface BRScrollingTextPlane : BRControl
{
    NSAttributedString *_string;
    float _pursuitGap;
}

+ (Class)layerClass;
- (void)dealloc;
- (void)setAttributedString:(id)arg1;
- (id)attributedString;
- (void)setPursuitGap:(float)arg1;
- (void)setTileSize:(struct CGSize)arg1;
- (struct CGSize)naturalTextSize;
- (void)drawInContext:(struct CGContext *)arg1;

@end

