/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRNinePartWidgetLayer.h>

@interface BRSelectionLozengeLayer : BRNinePartWidgetLayer
{
}

- (void)setFocused:(BOOL)arg1;
- (float)overHeightFactor;
- (float)topGlowHeight;
- (float)bottomGlowHeight;
- (float)edgeGlowWidth;
- (float)edgeInset;
- (id)preferredActionForKey:(id)arg1;

@end

