/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSeriesMediaMenuController.h>

@interface BRSeriesMediaMenuController (Private)
- (id)_initWithTypes:(id)arg1 forSeries:(id)arg2 forSharedContent:(BOOL)arg3 forceFilterOutWatched:(BOOL)arg4;
- (id)_identifierFromTypes:(id)arg1;
- (id)_currentProviders;
- (void)_itemSelected;
- (void)_handleContextMenuSelection:(id)arg1;
- (long)_rowForHash:(id)arg1;
- (id)_hashForIndex:(long)arg1;
- (id)_playlistProvider;
- (void)_buildPlaylistsMenu;
- (id)_playlistsParade;
- (BOOL)_checkProviderOK:(id)arg1;
- (id)_deepestFocusedControl;
@end

