/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSentinel.h>

@interface BRSentinel (DatabaseSyncing)
- (void)_databaseUpdateStarted:(id)arg1;
- (void)_databaseUpdateComplete:(id)arg1;
- (void)_databaseObjectWasModified:(id)arg1;
- (void)_databaseObjectWasAdded:(id)arg1;
- (void)_databaseObjectWillBeDeleted:(id)arg1;
- (void)_databaseObjectWasDeleted:(id)arg1;
- (void)_databaseUpdatedWhileSyncStateIdle:(id)arg1;
- (void)_syncHostAvailabilityChanged:(id)arg1;
- (void)_newPhotoDatabaseAvailable:(id)arg1;
@end

