/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRDataStoreProvider.h>

@interface BRSeriesProvider : BRDataStoreProvider
{
}

- (id)initWithDataStore:(id)arg1;
- (void)dealloc;
- (id)hashForDataAtIndex:(long)arg1;

@end

