/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSeriesMediaMenuController.h>

@interface BRSeriesMediaMenuController (Subclassers)
- (int)defaultSortItem;
- (id)providerForSortState:(int)arg1;
- (void)arrayItemSelected:(id)arg1;
- (void)mediaAssetSelected:(id)arg1;
- (BOOL)showPlaylists;
- (BOOL)okToShowNoItemsWithCurrentProvider:(id)arg1;
- (id)itemForContextMenuFromSelection:(id)arg1;
- (void)setDefaultSelection;
- (id)keyForSortState:(int)arg1;
@end

