/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSingleton.h>

@interface BRSentinel : BRSingleton
{
    id _musicStoreImageDecryptionAgent;
    id _syncProgressAgent;
    id _signingAgent;
    id _daapListenerEnabler;
    unsigned int _networkDependentControllerCount;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)setMusicStoreImageDecryptionAgent:(id)arg1;
- (id)musicStoreImageDecryptionAgent;
- (void)networkDependentControllerWasPushed;
- (void)networkDependentControllerWasPopped;
- (void)setSyncProgressAgent:(id)arg1;
- (id)syncProgressAgent;
- (void)setYTSigningAgent:(id)arg1;
- (id)YTSigningAgent;
- (void)setDAAPListenerEnabler:(id)arg1;
- (id)daapListenerEnabler;

@end

