/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSeriesControlFactory.h>

@interface BRSeriesControlFactory (Private)
- (id)_listItemForAsset:(id)arg1 currentControl:(id)arg2;
- (id)_acquiredDateBasedAssetListItem:(id)arg1 currentControl:(id)arg2;
- (id)_showBasedAssetListItem:(id)arg1 currentControl:(id)arg2;
- (id)_episodeBasedAssetListItem:(id)arg1 currentControl:(id)arg2;
- (id)_showBasedSeriesItem:(id)arg1 currentControl:(id)arg2;
- (id)_posterControlForSeriesArray:(id)arg1 currentControl:(id)arg2;
- (id)_previewControlForData:(id)arg1 currentControl:(id)arg2;
- (id)_acquiredDateFromAsset:(id)arg1;
- (id)_airedDateFromAsset:(id)arg1;
- (void)_badgeListItem:(id)arg1 withInfoFromAsset:(id)arg2 setRightJustifiedText:(char *)arg3;
- (void)_assets:(id)arg1 areHD:(char *)arg2 haveUnplayed:(char *)arg3 havePartiallyPlayed:(char *)arg4 latestDate:(id *)arg5;
- (void)_markPlayedUnplayedState:(id)arg1 markNew:(BOOL)arg2 markPartialPlayed:(BOOL)arg3;
@end

