/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSeriesMostRecentNoStoreProvider.h>

@interface BRSeriesMostRecentNoStoreProvider (Private)
- (id)_initForMediaTypes:(id)arg1 controlFactory:(id)arg2 filteringOutProvider:(id)arg3;
- (void)_checkStore;
- (void)_setStoreAvailable:(BOOL)arg1;
- (BOOL)_storeAvailable;
- (id)_data;
- (void)_reloadData;
- (id)_filteredSeriesNames;
- (id)_filteredDataFrom:(id)arg1;
- (void)_postInsertionRemovalNotifcationsComparingOldData:(id)arg1 withNewData:(id)arg2;
@end

