/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface BRSimpleMenuItem : NSObject
{
    NSString *_title;
    NSString *_rightJustifiedText;
    int _titlePosition;
    int _menuItemType;
}

+ (id)simpleMenuItemWithTitle:(id)arg1 titlePosition:(int)arg2 menuItemType:(int)arg3;
+ (id)simpleMenuItemWithTitle:(id)arg1 rightJustifiedText:(id)arg2 titlePosition:(int)arg3 menuItemType:(int)arg4;
- (id)initWithTitle:(id)arg1 titlePosition:(int)arg2 menuItemType:(int)arg3;
- (id)initWithTitle:(id)arg1 rightJustifiedText:(id)arg2 titlePosition:(int)arg3 menuItemType:(int)arg4;
- (void)dealloc;
- (id)title;
- (id)rightJustifiedText;
- (int)titlePosition;
- (int)menuItemType;

@end

