/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRStatusAlertControl.h>

@interface BRStatusAlertControl (Private)
- (void)_setType:(int)arg1;
- (void)_cancel;
@end

