/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSubtitleControl.h>

@interface BRSubtitleControl (Private)
- (BOOL)_setTextFrameToSubtitleBox:(struct CGRect *)arg1;
- (void)_setTextColor:(id)arg1 inAttributes:(id)arg2;
- (void)_setTextFont:(id)arg1 inAttributes:(id)arg2;
- (void)_setTextWrap:(id)arg1 inAttributes:(id)arg2;
@end

