/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSBundle;

@interface BRSystemLanguages : NSObject
{
    NSBundle *_promptBundle;
    NSBundle *_refBundle;
}

+ (void)setUsePreferredLanguage:(BOOL)arg1;
+ (id)currentLanguage;
- (id)init;
- (void)dealloc;
- (id)getLangsAndPrompts:(BOOL)arg1;

@end

