/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRNinePartWidgetLayer, BRTextControl;

@interface BRTabControlItem : BRControl
{
    id _opaqueIdentifier;
    BRNinePartWidgetLayer *_baseControl;
    BRTextControl *_label;
}

- (id)init;
- (void)dealloc;
- (id)identifier;
- (void)setIdentifier:(id)arg1;
- (id)label;
- (void)setLabel:(id)arg1;
- (void)setLabelAttributes:(id)arg1;
- (void)setLabelOpacity:(float)arg1;
- (void)setTabImages:(id)arg1;
- (void)layoutSubcontrols;
- (struct CGSize)preferredFrameSize;

@end

