/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRController.h>

@class BRWaitPromptControl, NSTimer;

@interface BRTextWithSpinnerController : BRController
{
    NSTimer *_revealTimer;
    double _revealInterval;
    BRWaitPromptControl *_prompt;
    BOOL _isNetworkDependent;
}

- (id)initWithTitle:(id)arg1 text:(id)arg2;
- (id)initWithTitle:(id)arg1 text:(id)arg2 revealAfter:(double)arg3;
- (id)initWithTitle:(id)arg1 text:(id)arg2 isNetworkDependent:(BOOL)arg3;
- (id)initWithTitle:(id)arg1 text:(id)arg2 isNetworkDependent:(BOOL)arg3 revealAfter:(double)arg4;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (BOOL)isNetworkDependent;
- (void)setIcon:(id)arg1 horizontalOffset:(float)arg2 kerningFactor:(float)arg3;

@end

