/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRMarqueeTextControl, BRWaitSpinnerControl, NSAttributedString, NSDictionary, NSNumber;

@interface BRTextMenuItemLayer : BRControl
{
    BRMarqueeTextControl *_scroller;
    BRWaitSpinnerControl *_spinner;
    NSAttributedString *_titleText;
    NSAttributedString *_rightJustifiedText;
    NSDictionary *_rightIconInfo;
    NSDictionary *_leftIconInfo;
    NSDictionary *_textIconInfo;
    NSDictionary *_rightJustifiedTextIconInfo;
    NSDictionary *_indentedLeftIconInfo;
    int _style;
    NSNumber *_ordinal;
    long _largestOrdinal;
    float _indentedLeftIconLayerAlignment;
    float _leftInset;
    float _rightInset;
    BOOL _dimmed;
}

+ (id)folderMenuItem;
+ (id)networkMenuItem;
+ (id)menuItem;
+ (id)progressMenuItem;
+ (id)progressFolderItem;
+ (id)shuffleMenuItem;
+ (id)refreshMenuItem;
+ (float)baseRowHeight;
+ (float)smallRowHeight;
- (id)init;
- (void)dealloc;
- (id)baseTextAttributes;
- (id)centeredTextAttributes;
- (id)smallTextAttributes;
- (id)smallCenteredTextAttributes;
- (void)setRightIconInfo:(id)arg1;
- (id)rightIconInfo;
- (void)setLeftIconInfo:(id)arg1;
- (id)leftIconInfo;
- (void)setTextIconInfo:(id)arg1;
- (id)textIconInfo;
- (void)setTitle:(id)arg1;
- (void)setTitle:(id)arg1 withAttributes:(id)arg2;
- (id)title;
- (void)setRightJustifiedText:(id)arg1;
- (void)setRightJustifiedText:(id)arg1 attributes:(id)arg2;
- (id)rightJustifiedText;
- (void)setRightJustifiedText:(id)arg1 withIconInfo:(id)arg2;
- (id)rightJustifiedTextIconInfo;
- (void)setOrdinalNumber:(id)arg1 largestOrdinal:(int)arg2;
- (id)ordinalNumber;
- (void)setIndentedLeftIconInfo:(id)arg1 largestOrdinal:(int)arg2;
- (void)setIndentedLeftIconInfo:(id)arg1 largestOrdinal:(int)arg2 iconAlignmentFactor:(float)arg3;
- (id)indentedLeftIconInfo;
- (void)setDimmed:(BOOL)arg1;
- (BOOL)dimmed;
- (void)setWaitSpinnerActive:(BOOL)arg1;
- (BOOL)waitSpinnerActive;
- (struct CGSize)preferredFrameSize;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (void)setTextMenuItemHeightStyle:(int)arg1;
- (int)textMenuItemHeightStyle;
- (void)setLeftInset:(float)arg1;
- (void)setRightInset:(float)arg1;

@end

