/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRTextImageMenuItemLayer.h>

@interface BRTextImageMenuItemLayer (Private)
- (void)_addDimToLayer:(id)arg1;
- (void)_setTwoLine:(BOOL)arg1;
- (void)_setArrowImage:(id)arg1;
- (void)_thumbnailImageUpdated:(id)arg1;
- (void)_updateRightImageHighlightAndVisibility;
- (void)_updatePostTitleImageHighlight;
- (id)_titleAttributes;
- (id)_subtitleAttributes;
- (id)_rightImageLayerNameForIndex:(int)arg1;
@end

