/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRCursorLayer.h>

@interface BRTextEntryCursorLayer : BRCursorLayer
{
}

- (id)init;
- (id)imageMapForCornerRadius:(float)arg1;

@end

