/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRMenuController.h>

@class BRTextEntryControl;

@interface BRTextEntryController : BRMenuController
{
    BRTextEntryControl *_editor;
}

- (id)init;
- (id)initWithTextEntryStyle:(int)arg1;
- (void)dealloc;
- (id)editor;
- (BOOL)isValidAfterDataUpdate;
- (void)layoutSubcontrols;
- (void)setPrimaryInfoText:(id)arg1 withAttributes:(id)arg2;
- (void)setTextEntryTextFieldLabel:(id)arg1;
- (void)setTextFieldDelegate:(id)arg1;
- (void)setInitialTextEntryText:(id)arg1;
- (void)setFocusToGlyphNamed:(id)arg1;
- (void)setShowUserEnteredText:(BOOL)arg1;
- (void)reset;

@end

