/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRCursorControl, BRDeviceKeyboardMessage, BRInputMethod, BRKeyboard, BRRoundRectOutlineLayer, BRScrollControl, BRTabControl, BRTextControl, BRTextFieldBackgroundLayer, BRTextFieldControl, NSArray, NSAttributedString, NSMutableString;

@interface BRTextEntryControl : BRControl
{
    int _textEntryStyle;
    BRInputMethod *_inputMethod;
    BRKeyboard *_activeKeyboard;
    BRControl *_roundRectBackground;
    BRRoundRectOutlineLayer *_roundRectOutline;
    BRControl *_candidatesBackground;
    BRScrollControl *_candidatesKeysContainer;
    BRScrollControl *_keyboardContainer;
    BRControl *_actionKeysContainer;
    BRTextFieldBackgroundLayer *_textFieldBackground;
    BRTextControl *_textFieldLabel;
    NSAttributedString *_textFieldLabelString;
    BRTextFieldControl *_textField;
    BRTabControl *_tabControl;
    BRCursorControl *_cursor;
    NSArray *_customizedTextFieldControls;
    BRDeviceKeyboardMessage *_deviceKeyboardMessage;
    BRKeyboard *_popupKeyboard;
    struct CGColor *_popupBackgroundColor;
    struct CGColor *_popupBorderColor;
    int _popupShadowStyle;
    BOOL _constrainCursorToPopupKeyboard;
    BRScrollControl *_popupKeyboardControl;
    BRControl *_previouslyFocusedRow;
    int _previouslySelectedCharacterKeyIndex;
    NSMutableString *_userEnteredText;
    BOOL _showUserEnteredText;
    BOOL _textFieldIsInternal;
    BOOL _shouldWrapHorizontally;
    BOOL _shouldWrapVertically;
    BOOL _clientHasSpecifiedHorizontalWrapping;
    BOOL _clientHasSpecifiedVerticalWrapping;
}

- (id)init;
- (void)dealloc;
- (id)initWithTextEntryStyle:(int)arg1;
- (id)initWithTextEntryStyle:(int)arg1 textField:(id)arg2;
- (void)setTextEntryStyle:(int)arg1;
- (void)_setActiveKeyboard:(id)arg1;
- (void)_addMainKeyboardContainerForKeyboard:(id)arg1;
- (void)_addActionKeysRowForKeyboard:(id)arg1;
- (void)_removeActionKeysRow;
- (void)_addOrRemoveCandidatesContainer:(id)arg1;
- (void)_customizeTextEntryControls;
- (void)_addCustomizedTextFieldControls;
- (void)_removeCustomizedTextFieldControls;
- (int)textEntryStyle;
- (id)textField;
- (void)setTextField:(id)arg1;
- (void)setDeviceKeyboardTitle:(id)arg1 subText:(id)arg2;
- (void)startSpinning;
- (void)stopSpinning;
- (BOOL)canWrapHorizontally;
- (void)setCanWrapHorizontally:(BOOL)arg1;
- (BOOL)canWrapVertically;
- (void)setCanWrapVertically:(BOOL)arg1;
- (id)tabControl;
- (void)setTabControl:(id)arg1;
- (void)setShowUserEnteredText:(BOOL)arg1;
- (void)setTextFieldDelegate:(id)arg1;
- (id)textFieldDelegate;
- (void)setInitialText:(id)arg1;
- (void)reset;
- (void)setTextFieldLabel:(id)arg1;
- (void)setFocusToGlyphNamed:(id)arg1;
- (void)_wrapAroundEdge:(int)arg1;
- (void)_handleCustomActionKeyEvent:(id)arg1;
- (void)_handleCharacterSelectionEvent:(id)arg1;
- (void)_invokeInputActionWithDictionary:(id)arg1;
- (void)_removePopupKeyboard;
- (void)_inputActionAppendText:(id)arg1;
- (void)_inputActionAppendCandidate:(id)arg1;
- (void)_inputActionClearText:(id)arg1;
- (void)_inputActionDeleteText:(id)arg1;
- (void)_inputActionSwitchKeyboard:(id)arg1;
- (void)_inputActionSwitchInputMethod:(id)arg1;
- (void)_inputActionEscape:(id)arg1;
- (void)_generateKeyEventWithCharacters:(id)arg1;
- (void)_handlePopupKeyboardEvent;
- (BOOL)brEventAction:(id)arg1;
- (BOOL)_keyboardFocusIsAtEdge:(int)arg1;
- (void)controlWasFocused;
- (void)_finalizeControlWasFocused;
- (void)controlWasUnfocused;
- (id)_bestKeyboardLanguage:(int)arg1;
- (void)setBackgroundColor:(struct CGColor *)arg1;
- (struct CGSize)preferredFrameSize;
- (void)layoutSubcontrols;
- (void)setOutlineColor:(struct CGColor *)arg1;
- (void)setPopupBackgroundColor:(struct CGColor *)arg1;
- (void)setPopupShadowStyle:(int)arg1;
- (void)setPopupOutlineColor:(struct CGColor *)arg1;
- (void)setConstrainCursorToPopupKeyboard:(BOOL)arg1;
- (void)addSelectionHandlerForControl:(id)arg1 forKeyboard:(id)arg2;
- (id)_keyboardMappingData;

@end

