/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRTextMenuItemLayer.h>

@interface BRTextMenuItemLayer (Private)
- (id)_selectImageForInfo:(id)arg1;
- (float)_scaleFactorForInfo:(id)arg1;
- (struct CGRect)_adjustTextPositioning:(struct CGRect)arg1 forIconFrame:(struct CGRect)arg2 paddingFactor:(float)arg3;
- (struct CGRect)_adjustFramePosition:(struct CGRect)arg1 forInfo:(id)arg2;
- (float)_ordinalColumnWidth;
- (id)_ordinalString;
- (void)_switchToScrollerForTextFrame:(struct CGRect)arg1;
- (void)_drawDimmedImage:(id)arg1 inRect:(struct CGRect)arg2 context:(struct CGContext *)arg3;
- (void)_drawDimmedText:(id)arg1 inRect:(struct CGRect)arg2 context:(struct CGContext *)arg3;
@end

