/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRThemeInfo.h>

@interface BRThemeInfo (ImageLoading)
- (id)_cachedImageForFile:(id)arg1 ofType:(id)arg2;
- (id)_imageForFile:(id)arg1 ofType:(id)arg2;
@end

