/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock, NSMutableArray;

@interface BRThreadCallback : NSObject
{
    struct __CFRunLoop *_loop;
    struct __CFRunLoopSource *_source;
    NSMutableArray *_notifications;
    NSLock *_lock;
}

- (id)init;
- (void)dealloc;

@end

