/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControlMediator.h>

@class BRProviderGroup;

@interface BRThresholdControlMediator : BRControlMediator
{
    BRProviderGroup *_dataProviderGroup;
    int _activeThreshold;
}

- (void)dealloc;
- (void)setDataProviders:(id)arg1;
- (void)setDataProvider:(id)arg1;
- (void)setActiveThreshold:(int)arg1;

@end

