/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRMediaPlayer, BRTextControl, BRTransportLayer, NSArray, NSTimer;

@interface BRTransportControl : BRControl
{
    long _duration;
    long _elapsedTime;
    BRMediaPlayer *_player;
    BRTransportLayer *_layer;
    BRTextControl *_durationLayer;
    BRTextControl *_elapsedTimeLayer;
    BRTextControl *_chapterLayer;
    NSArray *_chapterMarkers;
    NSTimer *_fadeTimer;
    NSTimer *_pollTimer;
}

- (id)init;
- (void)dealloc;
- (void)setPlayer:(id)arg1;
- (void)hideTransport;
- (void)showTransport;
- (void)showTransportWithShortTimeout;
- (void)showTransportWithMediumTimeout;
- (void)showTransportWithLongTimeout;
- (void)layoutSubcontrols;
- (void)controlWasDeactivated;
- (BOOL)isHidden;
- (void)setShowChapterMarks:(BOOL)arg1;
- (BOOL)showChapterMarks;

@end

