/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class BRMarqueeTextControl, BRTextControl, BRWaitSpinnerControl;

@interface BRTwoLineTextMenuItemLayer : BRControl
{
    BRControl *_background;
    BRMarqueeTextControl *_titleLayer;
    BRTextControl *_subtitleLayer;
    BRWaitSpinnerControl *_spinner;
}

- (id)init;
- (void)dealloc;
- (void)setWaitSpinnerActive:(BOOL)arg1;
- (void)setTitle:(id)arg1;
- (id)title;
- (void)setSubtitle:(id)arg1;
- (id)subtitle;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (struct CGRect)focusCursorFrame;
- (void)layoutSubcontrols;
- (id)axSelectedItemText;

@end

