/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSAttributedString, NSMutableArray;

@interface BRTypesetter : NSObject
{
    NSAttributedString *_resolvedString;
    struct __CTTypesetter *_setter;
    NSMutableArray *_lines;
    struct CGSize _boxSize;
    struct CGSize _shadowOffset;
    float _flushFactor;
    BOOL _renderingAttributesFetched;
}

- (id)initWithAttributedString:(id)arg1 textBoxSize:(struct CGSize)arg2;
- (void)dealloc;
- (struct CGSize)typographicBounds;
- (void)drawTextAtPoint:(struct CGPoint)arg1 inContext:(struct CGContext *)arg2;
- (long)numLines;
- (id)lineAtIndex:(long)arg1;

@end

