/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface BRTypesetLine : NSObject
{
    struct __CTLine *_line;
    struct CGSize _shadowOffset;
    float _flushFactor;
}

- (id)initWithCTLineRef:(struct __CTLine *)arg1 shadowOffset:(struct CGSize)arg2 flushFactor:(float)arg3;
- (void)dealloc;
- (void)typographicBounds:(float *)arg1 descent:(float *)arg2 leading:(float *)arg3;
- (void)drawLineAtPoint:(struct CGPoint)arg1 withWidth:(float)arg2 inContext:(struct CGContext *)arg3;

@end

