/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRSelectionLozengeLayer.h>

@class BRImage;

@interface BRUnboundedSelectionLozengeLayer : BRSelectionLozengeLayer
{
    BRImage *_topImage;
    BRImage *_bottomImage;
    BOOL _brighterImage;
    BOOL _focusedImage;
}

- (id)init;
- (void)dealloc;
- (void)setUseBrighterUnselectedImage:(BOOL)arg1;
- (BOOL)useBrighterUnselectedImage;
- (void)setFocused:(BOOL)arg1;
- (void)layoutSubcontrols;
- (void)drawInContext:(struct CGContext *)arg1;

@end

