/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRVideo.h>

@interface BRVideo (ErrorHandling)
- (id)_generateBadMediaErrorForMedia:(id)arg1;
- (id)_generateMissingMediaErrorForMedia:(id)arg1;
- (id)_generateNotAuthorizedErrorForMedia:(id)arg1;
- (id)_generateNotHDCPCompliantErrorForMedia:(id)arg1;
- (id)_generateExpiredErrorForMedia:(id)arg1;
- (id)_generateUnplayableMovieErrorForMedia:(id)arg1;
@end

