/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRVideoVisualControl.h>

@interface BRVideoVisualControl (BlurGen)
- (id)_currentVideoFrameWithBlurOption:(BOOL)arg1;
- (id)_generateBRImageFromCIImage:(id)arg1 addBlur:(BOOL)arg2;
@end

