/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRRenderContext;

@interface BRVideoHardwarePostprocessor : NSObject
{
    BRRenderContext *_context;
    struct BRPostProcessMatrix _matrix709;
    struct BRPostProcessMatrix _matrix601;
    unsigned int _vpName;
    unsigned int _fpNames[32];
    unsigned int _noiseTexName;
    int _fpIndex;
    int _forceFPBitsOff;
    int _forceFPBitsOn;
    struct CGColorSpace *_colorsync_cachedspaceref;
    struct CGColorSpace *_to_spaceref;
    int _tdBitDepth;
    float _tdOnFrame;
    unsigned long long _noiseSeedTime;
    float _noiseParamX;
    float _noiseParamY;
    struct BRVideoColorSyncData _cSyncData;
}

- (id)initWithContext:(id)arg1;
- (void)dealloc;
- (void)renderFrame:(struct __CVBuffer *)arg1 fromTime:(unsigned long long)arg2 inRect:(struct CGRect)arg3;

@end

