/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSTimer;

@interface BRVideoLoadMonitor : NSObject
{
    struct MovieType **_movie;
    NSTimer *_loadStatePoll;
    long _lastLoadState;
    BOOL _loaded;
}

- (id)initWithMovie:(struct MovieType **)arg1;
- (void)stopMonitoring;
- (BOOL)moviePlayable;
- (BOOL)movieLoaded;
- (float)bufferingProgress;
- (struct BRTimeRange)bufferedRange;
- (double)maxMovieTime;
- (void)playheadHitMax;
- (void)playheadMoved;
- (long)loadState;
- (void)updateLoadState;

@end

