/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRControl.h>

@class CALayer, DOMElement, WAKWindow, WebView;

@interface BRWebWindowControl : BRControl
{
    WebView *_webView;
    WAKWindow *_window;
    DOMElement *_focusedElement;
    CALayer *_rootEffectsLayer;
    id _delegate;
}

- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)webView;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)setRootEffectsLayer:(id)arg1;
- (void)setFocusedElement:(id)arg1;
- (id)focusedElement;
- (BOOL)postGSEvent:(id)arg1;
- (struct CGRect)focusCursorFrame;
- (void)layoutSubcontrols;
- (int)touchSensitivity;

@end

