/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRMediaPlayer, BRXMLMediaAsset;

@interface BRWebMediaElementProxy : NSObject
{
    BRMediaPlayer *_player;
    BRXMLMediaAsset *_asset;
    BOOL _buffering;
    BOOL _isVideo;
}

- (void)dealloc;

@end

