/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "WebFormDelegate.h"

@class BRWebControl, DOMHTMLElement;

@interface BRWebFormHelper : WebFormDelegate
{
    BRWebControl *_webControl;
    DOMHTMLElement *_focused;
}

- (void)dealloc;
- (id)initWithControl:(id)arg1;
- (void)clearWebControl;
- (BOOL)handleFormEvent:(id)arg1;
- (BOOL)addInputString:(id)arg1;
- (BOOL)deleteFromInput;
- (void)setStringValue:(id)arg1;
- (id)stringValue;

@end

