/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWebControl.h>

@interface BRWebControl (Capabilities)
- (id)_activeDocument;
- (void)_processMetaTagsForWebView:(id)arg1;
- (void)_determineCursorState:(id)arg1;
- (id)_findContentValueForMetaTagNamed:(id)arg1 metaTags:(id)arg2;
@end

