/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWebControl.h>

@interface BRWebControl (Private)
- (void)_displayJavaScriptConsole;
- (void)_nextRunLoopDisplayJavaScriptConsole;
- (void)_webView:(id)arg1 didFailLoadWithError:(id)arg2 forFrame:(id)arg3 provisional:(BOOL)arg4;
@end

