/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWebControl.h>

#import "WebWindowDelegate-Protocol.h"

@interface BRWebControl (WindowDelegate) <WebWindowDelegate>
- (void)focusedElementChangedTo:(id)arg1 forWindow:(id)arg2;
@end

