/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWebControl.h>

@interface BRWebControl (PointerSupport)
- (BOOL)_handlePointerEvent:(id)arg1;
- (BOOL)_handlePointerDirectionalEvent:(id)arg1;
- (BOOL)_handlePointerClickEvent:(id)arg1;
@end

