/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWindow.h>

@interface BRWindow (ScenePrivate)
+ (id)rootLayer;
+ (id)windowList;
+ (void)setMaxBounds:(struct CGSize)arg1;
+ (BOOL)dispatchEvent:(id)arg1;
+ (id)focusedLeafControl;
@end

