/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRWindow.h>

@interface BRWindow (PrivateWindowing)
- (id)_controlPlane;
- (void)_orderWindowOut:(id)arg1;
- (void)_orderWindowFront:(id)arg1;
- (void)_orderWindowBack:(id)arg1;
- (void)_orderWindow:(id)arg1 below:(id)arg2;
- (void)_orderWindow:(id)arg1 above:(id)arg2;
- (void)_addWindow:(id)arg1 atIndex:(long)arg2;
- (void)_updateRenderedWindows;
- (void)_updateContent;
@end

