/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <BackRow/BRTransitionControl.h>

@class BRControl;

@interface BRZoomTransitionControl : BRTransitionControl
{
    BRControl *_prerender;
    BOOL _prerenderAnimation;
}

- (void)dealloc;
- (void)setContent:(id)arg1;
- (void)setPrerenderAnimation:(BOOL)arg1;
- (BOOL)prerenderAnimation;
- (void)setTransitionedIn:(BOOL)arg1;
- (void)layoutSubcontrols;

@end

