/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

struct BRDisplayStringMappingEntry {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    float _field6;
    char _field7;
    char _field8;
    id *_field9;
};

struct BRFocusEdge {
    struct CGPoint _field1;
    struct CGPoint _field2;
};

struct BRNinePartImageMap {
    id _field1;
    id _field2;
};

struct BRPostProcessMatrix {
    double m[4][4];
};

struct BRRendererFrameCountParams {
    long frameCount;
    float frameRate;
    double frameTimeAccum;
    double prevFrameTime;
    char drawFrameRate;
};

struct BRTimeRange {
    double location;
    double length;
};

struct BRVideoColorSyncData {
    float addvector[4];
    float matrix[3][4];
    float gamma1[4];
    float gamma2[4];
    float a1[4];
    float b1[4];
    float c1[4];
    float d1[4];
    float e1[4];
    float f1[4];
    float a2[4];
    float b2[4];
    float c2[4];
    float d2[4];
    float e2[4];
    float f2[4];
};

struct BRVideoPlaybackStats {
    long stallCount;
    struct CGSize movieDimensions;
    char hardwareCodec;
    char needsPostprocessing;
};

struct CATransform3D {
    float m11;
    float m12;
    float m13;
    float m14;
    float m21;
    float m22;
    float m23;
    float m24;
    float m31;
    float m32;
    float m33;
    float m34;
    float m41;
    float m42;
    float m43;
    float m44;
};

struct CGAffineTransform {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
};

struct CGColor;

struct CGColorSpace;

struct CGContext;

struct CGFunction;

struct CGImage;

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct CVSMPTETime {
    short _field1;
    short _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    short _field6;
    short _field7;
    short _field8;
    short _field9;
};

struct ComponentInstanceRecord {
    long _field1[1];
};

struct MovieType;

struct OpaqueQTVisualContext;

struct Picture;

struct TrackType;

struct _Apple80211;

struct _CGDirectDisplayID;

struct _CGLContextObject;

struct _CGLPixelFormatObject;

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSSize {
    float _field1;
    float _field2;
};

struct _NSZone;

struct __CFRunLoop;

struct __CFRunLoopSource;

struct __CFString;

struct __CTFont;

struct __CTLine;

struct __CTTypesetter;

struct __CVBuffer;

struct __CVDisplayLink;

struct __SCDynamicStore;

struct __SCNetworkService;

struct _opaque_pthread_cond_t {
    long __sig;
    char __opaque[24];
};

struct _opaque_pthread_mutex_t {
    long __sig;
    char __opaque[40];
};

typedef struct {
    long long timeValue;
    long timeScale;
    long flags;
} CDAnonymousStruct1;

typedef struct {
    unsigned int _field1;
    int _field2;
    long long _field3;
    unsigned long long _field4;
    double _field5;
    long long _field6;
    struct CVSMPTETime _field7;
    unsigned long long _field8;
    unsigned long long _field9;
} CDAnonymousStruct2;

