/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "DOMEventListener-Protocol.h"

@class BRWebControl;

@interface DOMEventBridge : NSObject <DOMEventListener>
{
    BRWebControl *_webControl;
    SEL _selector;
}

- (id)initWithWebControl:(id)arg1 selector:(SEL)arg2;
- (void)setTarget:(id)arg1;
- (void)handleEvent:(id)arg1;

@end

