/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRTextEntryController.h"

#import "BRTextFieldDelegate-Protocol.h"

@class BRAirportNetwork;

@interface ATVAPPasswordEntryController : BRTextEntryController <BRTextFieldDelegate>
{
    BRAirportNetwork *_network;
    id _delegate;
}

- (id)initForNetwork:(id)arg1 acceptOnlyHex:(BOOL)arg2 notifying:(id)arg3;
- (void)dealloc;
- (void)textDidChange:(id)arg1;
- (void)textDidEndEditing:(id)arg1;
- (void)setInitialPassword:(id)arg1;

@end

