/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVBSRController.h>

@interface ATVBSRController (BlackScreenRecovery)
- (void)_setListOfResolutionsToTry:(id)arg1;
- (id)_nextModeToTry;
- (id)_countdownString;
- (void)_timerCallback:(id)arg1;
- (void)_executeDisplayChangeEvent;
- (void)_restoreOriginalModeAndPopController;
@end

