/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "ATVScreenSaverPluginProtocol-Protocol.h"

@class BRControl;

@interface ATVBlackScreenSaver : NSObject <ATVScreenSaverPluginProtocol>
{
    BRControl *_blackShroudOfDeath;
}

- (id)init;
- (void)dealloc;
- (id)screenSaverControl;

@end

