/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRMenuController.h"

@class ATVBSRLayer, BRDisplayMode, NSArray, NSTimer;

@interface ATVBSRController : BRMenuController
{
    ATVBSRLayer *_bsrControl;
    int _selectionKind;
    BRDisplayMode *_originalMode;
    NSArray *_listOfResolutionsToTry;
    NSTimer *_modeTimer;
    id _confirmationDelegate;
    int _secondsLeftBeforeNextDisplayMode;
    int _attemptedModeNumber;
    int _numberOfBSRAttempts;
    BOOL _isBSRController;
}

+ (id)controllerForBlackScreenRecovery;
+ (id)controllerForChangingToResolution:(id)arg1;
- (id)init;
- (id)_initWithModeList:(id)arg1 selectionKind:(int)arg2 fromBSR:(BOOL)arg3;
- (void)setConfirmationDelegate:(id)arg1;
- (void)dealloc;
- (void)layoutSubcontrols;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (BOOL)brEventAction:(id)arg1;
- (void)itemSelected:(long)arg1;

@end

