/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVEvaluation.h>

@interface ATVClientVersionEvaluation : ATVEvaluation
{
}

- (BOOL)eq:(id)arg1;
- (BOOL)neq:(id)arg1;
- (BOOL)gt:(id)arg1;
- (BOOL)lt:(id)arg1;
- (BOOL)gte:(id)arg1;
- (BOOL)lte:(id)arg1;

@end

