/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRBaseParserDelegate.h"

@class NSMutableArray, NSMutableDictionary;

@interface ATVDotMacRecentAlbumsRSSFeedDelegate : BRBaseParserDelegate
{
    NSMutableArray *_recentAlbums;
    NSMutableDictionary *_currentAlbumInfo;
}

+ (id)delegate;
- (id)init;
- (void)dealloc;
- (id)recentAlbums;
- (void)startItemWithAttributes:(id)arg1;
- (void)startEnclosureWithAttributes:(id)arg1;
- (void)endItem;
- (void)endPubDate;
- (void)endTitle;
- (void)endLink;

@end

