/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacControlFactory.h>

@interface ATVDotMacControlFactory (Private)
- (id)_menuItemForDotMacData:(id)arg1 currentControl:(id)arg2;
- (id)_dividerForData:(id)arg1;
- (id)_previewControlForDotMacData:(id)arg1;
- (id)_posterControlForDotMacData:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (id)_durationStringFromLong:(long)arg1;
@end

