/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDownloadMenuItem.h>

@interface ATVDownloadMenuItem (Updating)
- (void)_requeryAssetAndUpdateUI;
- (void)_downloadStateChangedNotificationHandler:(id)arg1;
- (void)_updateRequestNotificationHandler:(id)arg1;
@end

