/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacProvider.h>

@interface ATVDotMacProvider (Private)
- (id)_initForPersistentAccounts;
- (id)_persistentAccounts;
- (void)_cancelDataMonitoringForAccounts;
- (void)_newAccountToAdd:(id)arg1;
- (void)_accountToRemove:(id)arg1;
- (void)_listenerUpdate:(id)arg1;
- (void)_processChangeToObject:(id)arg1;
- (void)_sendUpdateNotificationAfterDelay;
- (void)_sendUpdateNotification;
- (void)_postUpdateNotification:(id)arg1;
- (BOOL)_handlesObject:(id)arg1;
- (BOOL)_mediaLoadedForAccount:(id)arg1 updateData:(id)arg2;
- (BOOL)_accountIconLoadedForAccount:(id)arg1 updateData:(id)arg2;
- (BOOL)_newAuthenticationForCollection:(id)arg1 updateData:(id)arg2;
- (BOOL)_assetsLoadedForCollection:(id)arg1 updateData:(id)arg2;
- (BOOL)_imageLoadedForAsset:(id)arg1 updateData:(id)arg2;
- (id)_cachedAccountIconForIconPath:(id)arg1;
@end

