/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDetailedMetadataControlFactory.h>

@interface ATVDetailedMetadataControlFactory (Private)
- (id)_setupBaseDetailedMetadataControl:(id)arg1;
- (id)_setupMusicDetailedMetadataControl:(id)arg1;
- (void)_setupSpecificDetailedMetadataControl:(id)arg1 forControl:(id)arg2;
- (void)_populateMovieDetails:(id)arg1 forControl:(id)arg2 isTrailer:(BOOL)arg3;
- (void)_populateActors:(id)arg1 forControl:(id)arg2;
- (void)_populateDirectors:(id)arg1 forControl:(id)arg2;
- (void)_populateProducers:(id)arg1 forControl:(id)arg2;
@end

