/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDirectionalRemoteConnectionHandler.h>

@interface ATVDirectionalRemoteConnectionHandler (MessageHandling)
- (id)_checkDataIntegrity:(id)arg1;
- (void)_setupControlReceiver:(id)arg1 encryptionKey:(unsigned long)arg2;
- (unsigned long)_decryptReceivedWord:(unsigned long)arg1;
- (void)_processTouchCommand:(id)arg1;
- (void)_promptReceived:(id)arg1;
@end

