/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRBaseParserDelegate.h"

@class NSMutableArray;

@interface ATVDotMacParserDelegate : BRBaseParserDelegate
{
    NSMutableArray *_entries;
    BOOL _entryCreated;
    int _curIndex;
}

+ (id)delegate;
- (id)init;
- (void)dealloc;
- (id)modDate;
- (void)startEntryWithAttributes:(id)arg1;
- (void)endEntry;
- (id)entries;
- (void)setEntryObject:(id)arg1 forKey:(id)arg2;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;

@end

