/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacMainMenuController.h>

@interface ATVDotMacMainMenuController (SelectionHandlers)
- (void)_handleAddSelection:(id)arg1;
- (void)_handleAccountSelection:(id)arg1;
@end

