/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacMonitor.h>

@interface ATVDotMacMonitor (DataMonitoringHelpers)
- (BOOL)_isAccountRegisteredForDataMonitoring:(id)arg1;
- (void)_addCollectionForTemporaryDataMonitoring:(id)arg1;
@end

