/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacProvider.h>

@class ATVInternetPhotosAccount, NSArray, NSSet;

@interface ATVDotMacProviderForAccount : ATVDotMacProvider
{
    ATVInternetPhotosAccount *_account;
    NSSet *_ignoredMediaCollectionTypes;
    NSArray *_dataWithTypeDividers;
    BOOL _disableTypeDividers;
}

+ (id)providerForAccount:(id)arg1;
- (id)initWithAccount:(id)arg1;
- (void)dealloc;
- (id)account;
- (void)setDisableTypeDividers:(BOOL)arg1;
- (long)dataCount;
- (id)dataAtIndex:(long)arg1;
- (id)hashForDataAtIndex:(long)arg1;
- (id)_dataWithTypeDividers;
- (id)_data;
- (BOOL)_handlesObject:(id)arg1;
- (void)_updateDataCount;
- (id)ignoredMediaCollectionTypes;
- (void)setIgnoredMediaCollectionTypes:(id)arg1;

@end

