/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacCollectionController.h>

@interface ATVDotMacCollectionController (Private)
- (void)_startPlaybackForCollection:(id)arg1;
- (void)_setScreenSaverForCollection:(id)arg1;
- (void)_authenticateCollection:(id)arg1 withUserName:(id)arg2 password:(id)arg3;
- (void)_pushWaitSpinnerController;
@end

