/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDownloadMenuItem.h>

@interface ATVDownloadMenuItem (Layout)
- (void)_setTitle:(id)arg1;
- (void)_setStatusText:(id)arg1;
- (void)_setDownloadStateForDownload:(id)arg1;
- (void)_setPercentComplete:(float)arg1;
@end

