/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacMonitor.h>

@interface ATVDotMacMonitor (Loads)
- (void)_performAuthenticateCollection:(id)arg1;
- (void)_performAccountLoad:(id)arg1;
- (void)_performAccountMediaLoad:(id)arg1;
- (void)_performCollectionAssetsLoad:(id)arg1;
- (void)_performCollectionAssetsLoadForPhotoCollection:(id)arg1;
- (void)_performCollectionAssetsLoadForVideoCollection:(id)arg1;
- (void)_collectionLoadFailure:(id)arg1 newCollectionInfo:(id)arg2 status:(int)arg3;
- (void)_performAssetThumbnailImageLoad:(id)arg1;
- (void)_performAssetCoverArtImageLoad:(id)arg1;
- (void)_performAssetFullSizeImageLoad:(id)arg1;
- (void)_performAccountIconImageLoad:(id)arg1;
- (void)_performAssetImageLoad:(id)arg1 sizeKey:(id)arg2;
@end

