/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacParserDelegate.h>

@class NSDate;

@interface ATVDotMacVideoDelegate : ATVDotMacParserDelegate
{
    NSDate *_modDate;
}

- (void)dealloc;
- (void)endTitle;
- (void)endDotmacTitle;
- (void)endContent;
- (void)endDotmacWebImagePath;
- (void)endDotmacPosterPath;
- (void)endDotmacVideoPathSmall;
- (void)endDotmacVideoDurationSmall;
- (void)endDotmacVideoPathMed;
- (void)endDotmacVideoDurationMed;
- (void)endDotmacVideoPathLrg;
- (void)endDotmacVideoDurationLrg;
- (void)endUpdated;
- (id)modDate;
- (id)videoName;

@end

