/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacAccountDelegate.h>

@interface ATVDotMacAccountDelegate (Private)
- (void)_updateEntriesWithDateTaken:(id)arg1 withType:(id)arg2;
- (id)_publicMedia;
@end

