/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVFavorite.h>

@interface ATVFavorite (Protected)
- (int)_currentVersion;
- (id)_currentDsid;
- (id)_currentStoreFront;
@end

