/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVInternetPhotosMonitor.h>

@class BRBackgroundTask;

@interface ATVFlickrMonitor : ATVInternetPhotosMonitor
{
    BRBackgroundTask *_backgroundTask;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)removeAccountWithName:(id)arg1;
- (void)addAccount:(id)arg1;
- (void)loadAccountWithName:(id)arg1;
- (void)loadMediaForAccount:(id)arg1;
- (void)loadSubAccountsForAccount:(id)arg1;
- (void)loadAccountIconForAccount:(id)arg1;
- (void)loadAssetsForCollection:(id)arg1;
- (void)loadThumbnailImageForAsset:(id)arg1;
- (void)loadCoverArtImageForAsset:(id)arg1;
- (void)loadFullSizeImageForAsset:(id)arg1;
- (void)searchWithSearchTerm:(id)arg1;
- (void)saveSearchTerm:(id)arg1;
- (void)removeSavedSearchTerm:(id)arg1;
- (id)savedSearchTerms;
- (void)cancelLoadMediaForAccount:(id)arg1;
- (void)cancelLoadSubAccountsForAccount:(id)arg1;
- (void)cancelLoadAccountIconForAccount:(id)arg1;
- (void)cancelLoadAssetsForCollection:(id)arg1;
- (void)cancelLoadThumbnailImageForAsset:(id)arg1;
- (void)cancelLoadCoverArtImageForAsset:(id)arg1;
- (void)cancelLoadFullSizeImageForAsset:(id)arg1;
- (id)backgroundTask;

@end

