/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRSelectionHandler-Protocol.h"

@class NSString;

@interface ATVFlickrSaveRemoveSearchSelectionHandler : NSObject <BRSelectionHandler>
{
    NSString *_searchTerm;
}

+ (id)selectionHandlerWithSearchTerm:(id)arg1;
- (id)initWithSearchTerm:(id)arg1;
- (void)dealloc;
- (BOOL)handleSelectionForControl:(id)arg1;

@end

