/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVFlickrProvider.h>

#import "BRPhotoProviderForCollection-Protocol.h"

@class ATVFlickrCollection;

@interface ATVFlickrProviderForCollection : ATVFlickrProvider <BRPhotoProviderForCollection>
{
    ATVFlickrCollection *_collection;
}

+ (id)providerForCollection:(id)arg1;
- (id)initWithCollection:(id)arg1;
- (void)dealloc;
- (id)hashForDataAtIndex:(long)arg1;
- (id)_data;
- (BOOL)_handlesObject:(id)arg1;
- (id)collection;
- (BOOL)canHaveZeroData;

@end

