/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

#import "BRSelectionHandler-Protocol.h"

@interface ATVFavoritesSelectionHandler : BRSingleton <BRSelectionHandler>
{
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (BOOL)handleSelectionForControl:(id)arg1;

@end

