/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVFavoritesGridProvider.h>

@interface ATVFavoritesGridProvider (ManagerNotifications)
- (void)_favoriteAdded:(id)arg1;
- (void)_favoriteRemoved:(id)arg1;
@end

