/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVFlickrProvider.h>

@interface ATVFlickrProvider (DataAccessor)
- (id)_data;
- (id)_collectionWithIdentifier:(id)arg1 withParentAccount:(id)arg2;
- (id)_assetWithIdentifier:(id)arg1 parentCollection:(id)arg2;
- (id)_accountWithName:(id)arg1;
@end

