/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

@class NSConditionLock, NSInvocation, NSThread;

@interface ATVHIDThread : BRSingleton
{
    NSThread *_hidThread;
    struct __CFRunLoop *_runLoop;
    NSConditionLock *_startLock;
    struct __CFRunLoopSource *_invocationRunLoopSource;
    NSInvocation *_pendingInvocation;
    NSConditionLock *_invocationLock;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (id)init;
- (void)dealloc;
- (BOOL)invokeOnHIDThread:(id)arg1;

@end

