/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVHardwareUtility.h>

@interface ATVHardwareUtility (Private)
- (BOOL)_isEmbeddedHardwareDevice;
- (void)_turnLEDOn:(int)arg1;
- (void)_turnLEDOff:(int)arg1;
- (void)_turnOffLEDs;
- (void)_blinkWhiteLED;
- (void)_blinkAmberLED;
- (void)_changeLED:(int)arg1 state:(BOOL)arg2;
- (BOOL)_determineIfEmbeddedHardwareDevice;
- (BOOL)_lowPowerMode;
- (void)_setLowPowerMode:(BOOL)arg1;
@end

