/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVInternetPhotosMonitor.h>

@interface ATVInternetPhotosMonitor (SubclassUtilitites)
- (void)queueTaskWithIdentifier:(id)arg1 selector:(SEL)arg2 object:(id)arg3;
- (void)cancelTaskWithIdentifier:(id)arg1;
- (void)performDataMonitoring;
- (void)invokeUpdateDelegateForObject:(id)arg1 updateData:(id)arg2;
- (id)backgroundTask;
- (void)postUpdateNotification:(id)arg1;
- (id)currentUpdateDelegate;
@end

