/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

#import "ATVITunesTouchRemoteManager-Protocol.h"

@interface ATVITunesLibraryTouchRemoteAccess : BRSingleton <ATVITunesTouchRemoteManager>
{
    id _delegate;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (void)dealloc;
- (void)setITunesTouchRemoteManagerDelegate:(id)arg1;
- (id)pairedTouchRemotes;
- (BOOL)removePairedTouchRemote:(id)arg1;
- (id)pairableTouchRemotes;
- (void)pairWithTouchRemote:(id)arg1 withPIN:(id)arg2;
- (unsigned long)sendGeneralPurposeMessage:(id)arg1;

@end

