/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

@class BRAsyncTaskContext, NSMutableArray, NSMutableDictionary;

@interface ATVInternetPhotosMonitor : BRSingleton
{
    NSMutableDictionary *_tasks;
    BRAsyncTaskContext *_taskContext;
    NSMutableArray *_dataMonitoredObjects;
    NSMutableArray *_temporaryDataMonitoredObjects;
    NSMutableArray *_temporaryUpdateDelegateCandidates;
    id _updateDelegate;
    NSMutableArray *_accountListeners;
    NSMutableArray *_collectionListeners;
}

- (void)dealloc;
- (void)removeAccountWithName:(id)arg1;
- (void)loadAccountWithName:(id)arg1;
- (void)cancelLoadAccountWithName:(id)arg1;
- (void)loadMediaForAccount:(id)arg1;
- (void)loadSubAccountsForAccount:(id)arg1;
- (void)loadAccountIconForAccount:(id)arg1;
- (void)loadAssetsForCollection:(id)arg1;
- (void)loadThumbnailImageForAsset:(id)arg1;
- (void)loadCoverArtImageForAsset:(id)arg1;
- (void)loadFullSizeImageForAsset:(id)arg1;
- (void)cancelLoadMediaForAccount:(id)arg1;
- (void)cancelLoadSubAccountsForAccount:(id)arg1;
- (void)cancelLoadAccountIconForAccount:(id)arg1;
- (void)cancelLoadAssetsForCollection:(id)arg1;
- (void)cancelLoadThumbnailImageForAsset:(id)arg1;
- (void)cancelLoadCoverArtImageForAsset:(id)arg1;
- (void)cancelLoadFullSizeImageForAsset:(id)arg1;
- (void)registerAccountForDataMonitoring:(id)arg1;
- (void)cancelDataMonitoringForAccount:(id)arg1;
- (void)registerCollectionForDataMonitoring:(id)arg1;
- (void)cancelDataMonitoringForCollection:(id)arg1;
- (id)dataMonitoredObjects;
- (void)addOneTimeDataMonitoredObject:(id)arg1;
- (void)registerUpdateDelegate:(id)arg1;
- (void)unregisterUpdateDelegate:(id)arg1;
- (void)registerTemporaryUpdateDelegate:(id)arg1;
- (void)unregisterTemporaryUpdateDelegate:(id)arg1;
- (void)registerAccountListenerWithID:(id)arg1;
- (void)unregisterAccountListenerWithID:(id)arg1;
- (void)notifyAccountListenersOfChangeToObject:(id)arg1;
- (void)registerCollectionListenerWithID:(id)arg1;
- (void)unregisterCollectionListenerWithID:(id)arg1;
- (void)notifyCollectionListenersOfChangeToObject:(id)arg1;

@end

