/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRMenuController.h"

#import "BRMenuListItemProvider-Protocol.h"

@class BRSystemLanguages, NSArray, NSDictionary;

@interface ATVLanguageChooserController : BRMenuController <BRMenuListItemProvider>
{
    BRSystemLanguages *_systemLanguages;
    NSArray *_languageKeys;
    NSDictionary *_languageKeysAndPrompts;
    id _delegate;
    BOOL _canBePopped;
}

- (id)init;
- (void)dealloc;
- (void)itemSelected:(long)arg1;
- (id)itemForRow:(long)arg1;
- (long)itemCount;
- (id)titleForRow:(long)arg1;
- (float)heightForRow:(long)arg1;
- (BOOL)rowSelectable:(long)arg1;
- (void)setSelectionDelegate:(id)arg1;
- (long)defaultIndex;
- (void)setCanBePopped:(BOOL)arg1;
- (BOOL)canBePopped;
- (BOOL)brEventAction:(id)arg1;

@end

