/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

@class NSMutableDictionary, NSString;

@interface ATVMusicStoreTabManager : BRSingleton
{
    NSMutableDictionary *_tabsContainer;
    NSString *_savedTabsFilePath;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)preferredSegmentNameForTabName:(id)arg1;
- (void)setPreferredSegmentName:(id)arg1 forTabName:(id)arg2;
- (BOOL)preferredSegmentExistsForTabName:(id)arg1;
- (BOOL)segmentNamed:(id)arg1 isPreferredSegmentForTabName:(id)arg2;

@end

