/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSString;

@interface ATVMusicStoreOffer : NSObject
{
    NSString *_storeOfferType;
    NSDictionary *_storeOfferInfo;
}

+ (id)offerListFromStoreOffersDictionary:(id)arg1;
+ (id)_filterStoreOfferList:(id)arg1;
+ (id)primaryOfferFromStoreOffersDictionary:(id)arg1;
+ (id)storeOfferFromDictionary:(id)arg1 forType:(id)arg2;
+ (id)priceRangeFromStoreOffersDictionary:(id)arg1;
+ (BOOL)anyOfferHasDigitalExtras:(id)arg1;
- (id)initWithStoreOfferDictionary:(id)arg1 forType:(id)arg2;
- (void)dealloc;
- (id)storeOfferType;
- (long)duration;
- (long)previewDuration;
- (id)fileSize;
- (id)price;
- (BOOL)hasPurchase;
- (id)purchaseParams;
- (id)purchasePrice;
- (BOOL)hasRental;
- (id)rentalParams;
- (id)rentalPrice;
- (BOOL)hasDateAvailable;
- (id)dateAvailable;
- (BOOL)hasDownload;
- (id)downloadURL;
- (BOOL)hasPreview;
- (id)previewURL;
- (BOOL)isClosedCaptioned;
- (BOOL)isWideScreen;
- (BOOL)isHD;
- (BOOL)isDolbyDigital;
- (BOOL)isITunesPlus;
- (BOOL)shouldShowPlusBadge;
- (BOOL)hasDigitalExtras;
- (id)actionDisplayName;
- (id)preActionWarning;
- (BOOL)usesStoreDrivenFlow;

@end

