/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStorePresentsProvider.h>

@interface ATVMusicStorePresentsProvider (StoreDataLoading)
- (void)_clearStoreData;
- (void)_resetStoreData;
- (BOOL)_okToFetchNewData;
- (void)_loadCachedEntry;
- (void)_loadStoreDataFromURL:(id)arg1;
- (void)_supplementalResponseReceived:(id)arg1;
- (void)_parseStorePage:(id)arg1;
- (void)_parseCatalogCollection:(id)arg1;
- (id)_cachedResultDirectory;
- (id)_cachedResultPath;
- (id)_cachedResultModDate;
- (void)_networkChanged:(id)arg1;
- (void)_parentalControlAccessChanged:(id)arg1;
@end

