/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface ATVMusicStoreControlPopulator : NSObject
{
    unsigned int _matchOrder;
}

+ (BOOL)canHandleData:(id)arg1;
- (id)init;
- (id)buttonForData:(id)arg1;
- (id)mainMenuButtonForData:(id)arg1;
- (id)shelfForData:(id)arg1;
- (id)gridForData:(id)arg1;
- (id)listForData:(id)arg1;
- (id)listRowForData:(id)arg1;
- (id)mediaPreviewControlForData:(id)arg1;
- (float)buttonHeightForData:(id)arg1;
- (float)shelfHeightForData:(id)arg1;
- (float)gridHeightForData:(id)arg1;
- (float)listHeightForData:(id)arg1;
- (float)listRowHeightForData:(id)arg1;
- (float)mediaPreviewHeightForData:(id)arg1;

@end

