/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRTitleProvider-Protocol.h"

@class BRMediaType, NSDictionary, NSMutableArray, NSString, NSURL;

@interface ATVMusicStorePresentsProvider : NSObject <BRTitleProvider>
{
    NSString *_requestID;
    BRMediaType *_mediaType;
    NSURL *_url;
    NSURL *_fallbackURL;
    NSMutableArray *_items;
    NSDictionary *_catalogCollection;
    BOOL _storeLoadInProgress;
    double _lastStoreLoadTime;
    BOOL _networkIsOK;
    BOOL _storeRestricted;
    NSString *_title;
    unsigned int _collectionNumber;
    unsigned int _fallbackCollectionNumber;
    BOOL _usingFallback;
    BOOL _usingTestData;
}

+ (id)providerWithMediaType:(id)arg1 forID:(id)arg2;
- (id)title;
- (void)dealloc;
- (void)reloadStoreData;
- (BOOL)isLoading;
- (id)controlFactory;
- (long)dataCount;
- (id)dataAtIndex:(long)arg1;
- (id)hashForDataAtIndex:(long)arg1;

@end

