/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRControl.h"

@class BRReflectedImageControl, BRTextControl;

@interface ATVMusicStoreDownloadFailurePopup : BRControl
{
    BRControl *_boundingControl;
    BRTextControl *_directionsTextCtl;
    BRTextControl *_messageTextCtl;
    BRTextControl *_optionsTextCtl;
    BRReflectedImageControl *_warningImage;
    struct CGSize _size;
}

+ (void)postDownloadFailurePopup:(id)arg1;
+ (void)_postDialogWhenReady:(id)arg1;
+ (void)_postDialog:(id)arg1;
- (id)_initWithAsset:(id)arg1;
- (struct CGSize)preferredFrameSize;
- (BOOL)brEventAction:(id)arg1;

@end

