/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRBaseMediaAsset.h"

@interface ATVMusicCoversMediaAsset : BRBaseMediaAsset
{
    id _asset;
}

+ (id)assetWrapperWithAsset:(id)arg1;
- (id)initWithAsset:(id)arg1;
- (void)dealloc;
- (id)assetID;
- (id)imageProxy;
- (id)mediaType;

@end

