/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRBaseAppliance.h"

@interface ATVMusicStoreBaseAppliance : BRBaseAppliance
{
}

- (id)init;
- (void)dealloc;
- (id)controllerForIdentifier:(id)arg1 args:(id)arg2;
- (id)applianceSpecificControllerForIdentifier:(id)arg1 args:(id)arg2;
- (id)localizedSearchTitle;
- (BOOL)previewError;
- (id)previewErrorText;
- (id)previewErrorSubtext;
- (id)previewErrorIconImage;
- (id)previewProvidersForIdentifier:(id)arg1 withNames:(id *)arg2;
- (void)refreshPreviewControlDataForIdentifier:(id)arg1;

@end

