/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRController.h"

@class NSDictionary;

@interface ATVMusicStoreCatalogItemController : BRController
{
    NSDictionary *_itemDictionary;
}

- (id)initWithItemDictionary:(id)arg1;
- (void)dealloc;
- (id)itemDictionary;
- (void)setItemDictionary:(id)arg1;

@end

