/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreAssetController.h>

@interface ATVMusicStoreAssetController (Private)
- (id)_storeID;
- (void)_setImageProxy;
- (id)_actionProviders;
- (void)_setMetadataControl;
- (void)_assetPlayable:(id)arg1;
@end

