/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRRSSMediaAsset.h"

@class NSDictionary;

@interface ATVMusicStorePodcastAsset : BRRSSMediaAsset
{
    NSDictionary *_feedInfo;
}

- (id)initWithFeedInfo:(id)arg1;
- (void)dealloc;
- (void)setFeedInfo:(id)arg1;
- (id)feedInfo;
- (id)assetID;
- (id)title;
- (id)mediaDescription;
- (long)duration;
- (id)cast;
- (id)directors;
- (id)producers;
- (id)mediaURL;
- (id)previewURL;
- (BOOL)hasCoverArt;
- (id)coverArtID;
- (id)thumbnailArtID;
- (id)datePublished;
- (id)dateAcquired;
- (id)mediaType;
- (id)primaryGenreAsString;
- (id)primaryGenre;
- (id)genres;
- (float)userStarRating;
- (id)rating;
- (BOOL)hasVideoContent;
- (id)datePublishedString;
- (id)artist;
- (id)primaryCollectionTitle;
- (id)mediaSummary;
- (id)copyright;
- (id)thumbnailURL;
- (id)publisher;
- (id)description;
- (BOOL)isExplicit;

@end

