/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMoviesButtonControl.h>

@interface ATVMoviesButtonControl (Private)
- (void)_setAsset:(id)arg1;
- (BOOL)_isRental;
- (void)_assetDeleted:(id)arg1;
- (void)_downloadStateChanged:(id)arg1;
- (void)_swapDownloadDescriptionText;
- (void)_downloadConvertedToAsset:(id)arg1;
- (void)_updateExpiryText;
- (void)_startDownloadDescriptionSwitchingTimer;
- (void)_startExpiryCheckTimer;
@end

