/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVCatalogApplianceController.h>

#import "BRTabControlDelegate-Protocol.h"

@class BRControl, BRTabControl, NSTimer;

@interface ATVMusicStoreTabbedPageController : ATVCatalogApplianceController <BRTabControlDelegate>
{
    BRControl *_contentControl;
    BRTabControl *_tabControl;
    NSTimer *_activeTabSelectionChangedTimer;
    BOOL _showingWaitContent;
    BOOL _initialTabContentLoaded;
    BOOL _transitionInhibited;
}

- (id)initWithContentControl:(id)arg1 tabControl:(id)arg2;
- (void)dealloc;
- (void)_delayedTabSelectionTimerFired:(id)arg1;
- (void)tabControl:(id)arg1 didSelectTabItem:(id)arg2;
- (void)tabControl:(id)arg1 willSelectTabItem:(id)arg2;
- (void)tabControlDidChangeNumberOfTabItems:(id)arg1;

@end

