/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class BRURLDocumentManager;

@interface ATVMusicStoreXMLDocumentPreProcessor : NSObject
{
    BRURLDocumentManager *_includesManager;
}

+ (id)processDocument:(id)arg1;
- (void)dealloc;

@end

