/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRMetadataProvider-Protocol.h"

@class NSDictionary;

@interface ATVMusicStoreBaseMetadataProvider : NSObject <BRMetadataProvider>
{
    NSDictionary *_catalogItem;
    BOOL _useAlternateMetadata;
}

+ (id)providerWithCatalogItem:(id)arg1;
- (id)initWithCatalogItem:(id)arg1;
- (void)dealloc;
- (BOOL)useAlternateMetadata;
- (void)setUseAlternateMetadata:(BOOL)arg1;
- (id)controlForData:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (long)dataCount;
- (id)controlFactory;
- (id)dataAtIndex:(long)arg1;
- (void)populateMetadataForControl:(id)arg1;
- (id)hashForDataAtIndex:(long)arg1;

@end

