/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRControl.h"

@class BRAccount, BRWaitPromptControl, NSDictionary, NSString, NSTimer;

@interface ATVMusicStoreTransactionDialog : BRControl
{
    int _txState;
    BRWaitPromptControl *_waitPrompt;
    BRAccount *_account;
    NSDictionary *_item;
    id _diskReservation;
    NSString *_id;
    NSTimer *_timer;
}

- (id)initWithItem:(id)arg1;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)_showPromptTimer:(id)arg1;
- (int)runModal;
- (void)controlDidDisplayAsModalDialog;
- (BOOL)brEventAction:(id)arg1;

@end

