/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface ATVRCButtonPatternSet : NSObject
{
    NSArray *_commandPattern;
    NSArray *_repeatPattern;
    double _maxRepeatInterval;
}

- (id)initWithDictionary:(id)arg1;
- (void)dealloc;
- (void)setCommandPattern:(id)arg1;
- (void)setRepeatPattern:(id)arg1;
- (id)commandPattern;
- (id)repeatPattern;
- (void)setMaxRepeatInterval:(double)arg1;
- (double)maxRepeatInterval;
- (BOOL)isOneShot;
- (BOOL)isValid;
- (void)clear;
- (id)encodeToDictionary;
- (id)description;
- (BOOL)isEqualTo:(id)arg1;

@end

