/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVRCCapture.h>

@interface ATVRCCapture (Private)
- (void)_setCaptureState:(int)arg1;
- (void)_firstCommandEventReceived;
- (void)_mainCaptureDoneTrigger:(id)arg1;
- (void)_resetDiscontinuityTrigger;
- (void)_clearDiscontinuityTrigger;
- (void)_discontinuityTrigger:(id)arg1;
- (BOOL)_identifyCommandPattern;
- (double)_maxIntervalBetweenEvents;
@end

