/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class ATVRCButtonPatternSet, NSDate, NSMutableArray, NSTimer;

@interface ATVRCCapture : NSObject
{
    int _captureState;
    NSMutableArray *_capturedEvents;
    ATVRCButtonPatternSet *_workingPatternSet;
    NSTimer *_discontinuityTrigger;
    NSDate *_captureStartTime;
}

- (id)init;
- (void)dealloc;
- (void)startCapture;
- (void)addEvent:(id)arg1;
- (void)reset;
- (int)captureState;
- (id)workingPatternSet;
- (double)captureProgress;

@end

