/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVRemoteSet.h>

@interface ATVRemoteSet (Private)
- (id)_initPatternMatcherArray;
- (void)_setupTargetRemoteEvents;
- (void)_releasePatternMatchers;
- (void)_setupTargetEventForMatcher:(id)arg1 index:(int)arg2;
@end

