/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

#import "BRSelectionHandler-Protocol.h"

@class ATVSWUpdateRecord, ATVUpdateVerifier, NSDate, NSError, NSLock, NSMutableArray, NSString, NSTimer;

@interface ATVSWUpdateManager : BRSingleton <BRSelectionHandler>
{
    NSTimer *_updateCheckTimer;
    NSDate *_lastCheckTime;
    NSDate *_nextCheckTime;
    BOOL _checkInProgress;
    BOOL _downloadInProgress;
    BOOL _singleFileDownloadInProgress;
    BOOL _installUpdates;
    BOOL _automaticUpdateTriggered;
    BOOL _cancelRequested;
    BOOL _seedUpdateMode;
    BOOL _waitingForUserConfirmation;
    unsigned long long _amountDownloaded;
    NSDate *_downloadStartTime;
    NSError *_downloadError;
    ATVSWUpdateRecord *_pendingRecord;
    NSMutableArray *_licenses;
    BOOL _licenseAccepted;
    ATVUpdateVerifier *_verifier;
    NSString *_combinedUpdatePassphrase;
    NSString *_updateURLRoot;
    NSLock *_accessLock;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)startMonitoring;
- (void)stopMonitoring;
- (BOOL)checkForUpdates:(BOOL)arg1;
- (BOOL)updateCheckInProgress;
- (BOOL)updateDownloadInProgress;
- (unsigned long long)updateDownloadSize;
- (void)applyUpdatesIfAvailable;
- (void)clearDownloadedUpdates;
- (void)cancelUpdates;
- (id)localUpdateFolderPath;
- (void)updatesPostponed;
- (BOOL)handleSelectionForControl:(id)arg1;

@end

