/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

@class BRWindow, NSTimer;

@interface ATVScreenSaverManager : BRSingleton
{
    NSTimer *_timer;
    double _interval;
    BRWindow *_window;
    long _state;
    BOOL _enabled;
    BOOL _screenSaverPosted;
    BOOL _handlingTimeoutChangeNotification;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)enable;
- (void)showScreenSaver;
- (id)screenSaverPathsFromDirectory:(id)arg1;

@end

