/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVSWUpdateManager.h>

#import "BRXSWUpdateConfirmDelegate-Protocol.h"

@interface ATVSWUpdateManager (Callbacks) <BRXSWUpdateConfirmDelegate>
- (void)_updateCheckFinishedWithInfo:(id)arg1;
- (void)updateConfirmed:(BOOL)arg1;
@end

