/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

@interface ATVSettingsHelper : BRSingleton
{
    struct AuthorizationOpaqueRef *_authRef;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (id)init;
- (void)dealloc;
- (BOOL)setSystemLanguage:(id)arg1;
- (BOOL)setNetworkSettings:(id)arg1 forInterface:(int)arg2;
- (BOOL)setLowPowerMode:(BOOL)arg1;
- (BOOL)setTimeZoneFromMessage:(CDAnonymousStruct1)arg1;
- (BOOL)performOSUpdate:(BOOL)arg1 EFIUpdate:(BOOL)arg2 IRUpdate:(BOOL)arg3 SIUpdate:(BOOL)arg4;
- (BOOL)prepareForFactoryRestore;
- (BOOL)tellWatchdogWeAreUpAndRunning;
- (BOOL)haveWeQuitSinceBoot;
- (void)reboot;
- (void)setDate:(struct timeval *)arg1 inZone:(struct timezone *)arg2;
- (void)setSSHEnabled:(BOOL)arg1;

@end

