/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVScreenSaverManager.h>

@interface ATVScreenSaverManager (ScreenSaverNotifications)
- (void)_updateActivity:(id)arg1;
- (void)_dismissScreenSaver:(id)arg1;
- (void)_screenSaverControllerActivate:(id)arg1;
- (void)_screenSaverControllerDeactivate:(id)arg1;
- (void)_screenSaverIntervalChanged:(id)arg1;
@end

