/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVFavorite.h>

@class NSString;

@interface ATVStoreFavorite : ATVFavorite
{
    NSString *_dsid;
    NSString *_storeFront;
    NSString *_artworkURL;
    NSString *_thumbnailArtworkURL;
    NSString *_latestContentURL;
    int _itemType;
}

- (id)initWithCatalogItem:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)dsid;
- (id)storeFront;
- (id)artworkURLString;
- (id)thumbnailArtworkURLString;
- (id)latestContentURLString;
- (int)itemType;

@end

