/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRControl.h"

@class BRMediaPlayer;

@interface ATVScreenSaverControl : BRControl
{
    BRMediaPlayer *_player;
}

+ (id)screenSaverControlWithPlugin:(id)arg1;
- (id)initWithPlugin:(id)arg1;
- (void)dealloc;
- (BOOL)brEventAction:(id)arg1;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)layoutSubcontrols;

@end

