/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVSearchController.h>

@interface ATVSearchController (Private)
- (void)_performSearchWithString:(id)arg1;
- (void)_handleContextMenuSelection:(id)arg1;
@end

