/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/TCPServer.h>

@class NSMutableArray;

@interface ATVTCPControlReceiver : TCPServer
{
    Class connClass;
    NSMutableArray *_openConnections;
}

- (id)init;
- (void)dealloc;
- (Class)connectionClass;
- (void)setConnectionClass:(Class)arg1;
- (void)handleNewConnectionFromAddress:(id)arg1 inputStream:(id)arg2 outputStream:(id)arg3;
- (void)connectionClosed:(id)arg1;
- (void)newBytesReceived:(id)arg1 data:(id)arg2;

@end

