/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

@class ATVRemoteControlMessageHandler, NSMutableArray, NSTimer;

@interface ATVTouchRemoteManager : BRSingleton
{
    NSMutableArray *_outstandingNowPlayingRequests;
    NSMutableArray *_outstandingDialogUpdateRequests;
    NSMutableArray *_pairableTouchRemotes;
    NSTimer *_trickSpeedAdvanceTimer;
    ATVRemoteControlMessageHandler *_remoteMessageHandler;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
+ (id)touchablePlayer;
- (id)init;
- (void)dealloc;
- (void)removePairableTouchRemote:(id)arg1;
- (id)pairedTouchRemotes;
- (BOOL)removePairedTouchRemote:(id)arg1;
- (id)pairableTouchRemotes;
- (void)pairWithTouchRemote:(id)arg1 withPIN:(id)arg2;
- (void)playMediaAtIndex:(long)arg1 inTracklist:(id)arg2 shuffle:(BOOL)arg3 repeat:(BOOL)arg4;
- (void)playMediaAtIndex:(long)arg1 inCollection:(id)arg2 shuffle:(BOOL)arg3 repeat:(BOOL)arg4;
- (void)shuffleSongs;
- (void)play;
- (void)playPause;
- (void)playResume;
- (void)pause;
- (void)stop;
- (void)restartItem;
- (void)beginFF;
- (void)beginRW;
- (void)nextChapter;
- (void)prevChapter;
- (void)nextItem;
- (void)prevItem;
- (void)shuffleToggle;
- (void)repeatAdvance;
- (unsigned long)sendGeneralPurposeMessage:(id)arg1;

@end

