/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRAccountType.h"

@interface BRAccountType (ATVAdditions)
+ (id)airTunes;
+ (id)iTunes;
+ (id)flickr;
+ (id)dotMac;
+ (id)dotMacSecondary;
+ (id)youTube;
@end

