/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BRDownload <NSObject>
- (int)downloadState;
- (int)qualifiedDownloadState;
- (int)downloadStateContext;
- (unsigned long long)expectedSize;
- (unsigned long long)byteCount;
- (double)timeUntilPlayable;
- (void)setPlayable:(BOOL)arg1;
- (void)pause;
- (void)resume;
- (BOOL)testContent;
@end

