/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BRMediaObject <NSObject>
- (id)mediaObjectID;
- (void)performSelector:(SEL)arg1 target:(id)arg2;
- (void)performSelector:(SEL)arg1 target:(id)arg2 withObject:(id)arg3;
@end

