/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BRTabControlDelegate <NSObject>
- (void)tabControl:(id)arg1 didSelectTabItem:(id)arg2;
- (void)tabControl:(id)arg1 willSelectTabItem:(id)arg2;
- (void)tabControlDidChangeNumberOfTabItems:(id)arg1;
@end

