/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRThemeInfo.h"

@interface BRThemeInfo (ATVExtensions)
- (id)localContentProviderImage;
- (id)appleTVIconGlow;
- (id)hdPosterBadge;
- (id)dolbyDigitalBadge;
- (id)ccBadge;
- (float)storeRentalIconHorizontalOffset;
- (float)storeRentalIconKerningFactor;
- (id)loadMoreSquareImage;
- (id)loadMoreRectangleImage;
- (id)storeRentalPlaceholderImage;
- (id)storeRentalPlaceholderImageLarge;
- (id)tvShowPlaceholderImage;
- (id)musicPlaceholderImage;
- (id)podcastPlaceholderImage;
- (id)storeRentalFeaturedPlaceholderImage;
- (id)tvShowFeaturedPlaceholderImage;
- (id)musicFeaturedPlaceholderImage;
- (id)podcastFeaturedPlaceholderImage;
- (id)moreActionImage;
- (id)moreActionHighlightedImage;
- (id)checkForPurchasesTextAttributes;
- (id)downloadMenuItemPrimaryTextAttributes;
- (id)downloadMenuItemSecondaryTextAttributes;
- (float)heightForDownloadItemRow;
- (id)pauseButtonImage;
- (id)progressBarComponents_ActiveFilled;
- (id)progressBarComponents_ActiveEmpty;
- (id)progressBarActive_Endcap;
- (id)progressBarComponents_PausedFilled;
- (id)progressBarComponents_PausedEmpty;
- (id)progressBarPaused_Endcap;
- (id)progressBarComponents_Waiting;
- (float)shelfBoxTitleHeightScaleForFeatured:(BOOL)arg1;
- (float)shelfWidthScaleForCollectionType:(id)arg1 featured:(BOOL)arg2 showTitleAndSubtitle:(BOOL)arg3 showAllTitles:(BOOL)arg4;
- (float)shelfHeightScaleForCollectionType:(id)arg1 featured:(BOOL)arg2 related:(BOOL)arg3 showTitleAndSubtitle:(BOOL)arg4 showAllTitles:(BOOL)arg5;
- (float)shelfHorizontalGapForCollectionType:(id)arg1 featured:(BOOL)arg2 showTitleAndSubtitle:(BOOL)arg3 showAllTitles:(BOOL)arg4;
- (float)shelfCoverflowMarginForCollectionType:(id)arg1 featured:(BOOL)arg2 showTitleAndSubtitle:(BOOL)arg3 showAllTitles:(BOOL)arg4;
- (float)shelfTitleWidthScaleForCollectionType:(id)arg1 featured:(BOOL)arg2 moreInfoContent:(BOOL)arg3 showTitleAndSubtitle:(BOOL)arg4 showAllTitles:(BOOL)arg5 related:(BOOL)arg6;
- (float)shelfReflectionAmountForCollectionType:(id)arg1 featured:(BOOL)arg2 showTitleAndSubtitle:(BOOL)arg3 showAllTitles:(BOOL)arg4 related:(BOOL)arg5;
- (int)shelfColumnCountForCollectionType:(id)arg1 featured:(BOOL)arg2 related:(BOOL)arg3 moreInfoContent:(BOOL)arg4 showTitleAndSubtitle:(BOOL)arg5 showAllTitles:(BOOL)arg6;
- (BOOL)shelfScrollabilityForCollectionType:(id)arg1 featured:(BOOL)arg2 showTitleAndSubtitle:(BOOL)arg3 showAllTitles:(BOOL)arg4;
@end

