/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVAirTunesManager.h>

@interface ATVAirTunesManager (ConnectionMonitor)
- (void)_connectionStarted:(id)arg1;
- (void)_connectionFinished:(id)arg1;
- (void)_connectionFailedToAuth:(id)arg1;
- (void)_retryConnection:(id)arg1;
@end

