/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRController.h"

@class BRAirportNetwork, BRHeaderControl, BRTextControl, BRWaitSpinnerControl;

@interface ATVAPTestController : BRController
{
    BRWaitSpinnerControl *_spinner;
    BRAirportNetwork *_network;
    BOOL _testFailed;
    id _delegate;
    BRHeaderControl *_header;
    BRTextControl *_prompt;
}

- (id)initForNetwork:(id)arg1 notifying:(id)arg2;
- (void)dealloc;
- (void)setFrame:(struct CGRect)arg1;
- (void)wasPushed;
- (void)wasExhumed;

@end

