/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVAPNetworkMenuController.h>

#import "ATVAPPasswordEntryDelegate-Protocol.h"

@interface ATVAPNetworkMenuController (PasswordEntry) <ATVAPPasswordEntryDelegate>
- (void)passwordEntered:(id)arg1 forNetwork:(id)arg2;
@end

