/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

@interface ATVBSRManager : BRSingleton
{
    struct _CGDirectDisplayID *_lastValidDisplayID;
    BOOL _performingBSR;
    BOOL _enabled;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (void)dealloc;
- (BOOL)setSafeModeAndCheckIfDisplayNeedsBSR;
- (void)enableAutomaticMonitoring;
- (void)enterInitialDisplaySetup;
- (void)enterSelectingSafeMode;
- (void)enterWithModes:(id)arg1;

@end

