/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVBSRManager.h>

@interface ATVBSRManager (Private)
- (void)_showBSRScreenWithController:(id)arg1;
- (void)_displayChanged:(id)arg1;
@end

