/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRController.h"

@class BRControl, NSTimer;

@interface ATVCatalogApplianceController : BRController
{
    BRControl *_contentContainer;
    id _storeObject;
    BRControl *_catalogControl;
    BOOL _controllerToSwapOnActivate;
    long _state;
    NSTimer *_timer;
    BOOL _isDirty;
}

+ (void)initialize;
- (id)init;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (BOOL)isNetworkDependent;
- (void)setStoreObject:(id)arg1;
- (id)storeObject;
- (BOOL)recreateOnReselect;
- (void)markAsDirty;

@end

