/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRProvider-Protocol.h"

@class NSArray, NSMutableArray;

@interface ATVDotMacRecentAlbumsProvider : NSObject <BRProvider>
{
    NSMutableArray *_accountsBeingLoaded;
    NSArray *_mostRecentAlbums;
    NSMutableArray *_accountProviders;
    NSMutableArray *_collectionProviders;
    NSMutableArray *_collectionsBeingLoaded;
    id _controlFactory;
    BOOL _queryInProgress;
    double _lastQueryTime;
}

+ (id)standardProvider;
+ (id)mainMenuProvider;
- (id)controlFactory;
- (id)initForMainMenu:(BOOL)arg1;
- (void)dealloc;
- (long)dataCount;
- (id)dataAtIndex:(long)arg1;
- (id)hashForDataAtIndex:(long)arg1;
- (void)reload;

@end

