/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacParserDelegate.h>

@class NSArray, NSDate, NSString;

@interface ATVDotMacAlbumDelegate : ATVDotMacParserDelegate
{
    NSString *_keyImageID;
    NSArray *_imageOrder;
    NSDate *_modDate;
}

- (void)dealloc;
- (void)endDotmacKeyImagePath;
- (void)endDotmacUserorder;
- (void)endDotmacViewIdentifier;
- (void)endTitle;
- (void)endDotmacTitle;
- (void)endDotmacOriginalFilename;
- (void)endDotmacLargeImagePath;
- (void)endDotmacMaxLargeDimensions;
- (void)endDotmacWebImagePath;
- (void)endIphotoMaxWebDimensions;
- (void)endDotmacUserHidden;
- (void)endDotmacUseritemguid;
- (void)endIphotoPhotoDate;
- (void)endUpdated;
- (id)imageInfos;
- (id)sortedImageInfos;
- (id)keyImageInfo;
- (int)imageCount;
- (id)albumID;
- (id)modDate;
- (id)albumName;

@end

