/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

@class NSMutableArray;

@interface ATVDiskSpaceManager : BRSingleton
{
    NSMutableArray *_reservations;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)reserveBytes:(id)arg1;
- (BOOL)relinquishReservation:(id)arg1;
- (unsigned long long)mediaReservedBytes;
- (unsigned long long)mediaReservedStreamingBufferBytes;
- (unsigned long long)mediaCapacity;
- (id)mediaCapacityString;
- (unsigned long long)mediaFreeSpace;
- (id)mediaFreeSpaceString;

@end

