/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

@class BRDownloadManager;

@interface ATVDownloadsMonitor : BRSingleton
{
    BRDownloadManager *_downloadManager;
    id _currentAsset;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)_pauseAllDownloads;
- (void)_resumePausedDownloads;
- (void)setCurrentAsset:(id)arg1;

@end

