/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacRecentAlbumsProvider.h>

@interface ATVDotMacRecentAlbumsProvider (Private)
- (void)_collectionProviderUpdated:(id)arg1;
- (void)_collectionImageUpdated:(id)arg1;
- (id)_persistentAccountNames;
- (void)_loadAccounts;
- (void)_accountsInserted:(id)arg1;
- (void)_accountsRemoved:(id)arg1;
- (void)_networkChanged:(id)arg1;
- (BOOL)_okToFetchNewData;
- (void)_loadRSSFeedWithAccountName:(id)arg1;
- (void)_rssFeedRequestReady:(id)arg1;
- (void)_aggregateRecentAlbums:(id)arg1 forAccountName:(id)arg2;
- (void)_loadCollection:(id)arg1;
- (void)_sortCollectionsBeingLoaded;
- (void)_loadRecentAlbumsFromCache;
- (void)_saveRecentAlbumsToCache;
- (void)_removeRecentCachedAlbumsFromAccount:(id)arg1;
@end

