/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRPhotoImageProxy.h"

@interface ATVDotMacImageProxy : BRPhotoImageProxy
{
}

+ (id)imageProxyForAsset:(id)arg1;
+ (id)imageProxyForCollection:(id)arg1;
- (id)imageForImageSize:(int)arg1;
- (void)cancelImageRequestsForImageSizes:(int)arg1;

@end

