/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDiskSpaceManager.h>

@interface ATVDiskSpaceManager (Private)
- (id)_volumeSizeStringForSize:(unsigned long long)arg1;
@end

