/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVDotMacCollectionController.h>

@interface ATVDotMacCollectionController (Authentication)
- (void)_showUserNamePrompt;
- (void)_showInvalidUserNamePrompt;
- (void)_showPasswordPrompt;
- (void)_authFinished:(id)arg1;
@end

