/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@protocol ATVDotMacAuthentication
- (BOOL)isAuthenticated;
- (BOOL)requiresAuthentication;
- (void)setRequiresAuthentication:(BOOL)arg1;
- (id)secondaryAccount;
- (void)setSecondaryAccount:(id)arg1;
- (BOOL)initialAuthCheckComplete;
- (void)setInitialAuthCheckComplete:(BOOL)arg1;
@end

