/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVFlickrMonitor.h>

@interface ATVFlickrMonitor (Loads)
- (void)_performAccountLoad:(id)arg1;
- (void)_performAccountMediaLoad:(id)arg1;
- (void)_performAccountSubAccountsLoad:(id)arg1;
- (void)_performCollectionAssetsLoad:(id)arg1;
- (void)_performAssetThumbnailImageLoad:(id)arg1;
- (void)_performSearch:(id)arg1;
- (void)_performAssetCoverArtImageLoad:(id)arg1;
- (void)_performAssetFullSizeImageLoad:(id)arg1;
- (void)_performAccountIconImageLoad:(id)arg1;
- (void)_performAssetImageLoad:(id)arg1 sizeKey:(id)arg2;
- (id)_loadFlickrURL:(id)arg1;
- (id)_savedSearchesFilePath;
@end

