/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSDate, NSString;

@interface ATVFavorite : NSObject <NSCoding>
{
    int _version;
    NSDate *_dateAdded;
    NSString *_title;
    NSString *_itemID;
}

- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)title;
- (void)setItemID:(id)arg1;
- (id)itemID;
- (void)setDateAdded:(id)arg1;
- (id)dateAdded;
- (BOOL)removeUponAcquisition;
- (BOOL)isSaved;
- (void)save;
- (void)remove;

@end

