/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRImageProxy-Protocol.h"

@class BRPhotoMediaAsset;

@interface ATVFlickrImageProxy : NSObject <BRImageProxy>
{
    BRPhotoMediaAsset *_asset;
}

+ (id)imageProxyForAsset:(id)arg1;
- (id)initWithAsset:(id)arg1;
- (void)dealloc;
- (id)object;
- (id)imageIDForImageSize:(int)arg1;
- (id)imageForImageSize:(int)arg1;
- (BOOL)supportsImageForImageSize:(int)arg1;
- (id)defaultImageForImageSize:(int)arg1;
- (void)cancelImageRequestsForImageSizes:(int)arg1;

@end

