/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class ATVInternetPhotosCollection, NSArray, NSDate, NSString;

@interface ATVInternetPhotosAccount : NSObject
{
    NSString *_accountName;
    NSString *_accountID;
    NSString *_displayName;
    NSArray *_mediaAssets;
    NSArray *_subAccounts;
    NSArray *_mediaCollections;
    ATVInternetPhotosCollection *_lastModifiedCollection;
    NSDate *_modDate;
    NSDate *_lastCheckedDate;
    NSString *_accountIconPath;
}

+ (id)account;
- (void)dealloc;
- (id)accountName;
- (void)setAccountName:(id)arg1;
- (id)accountID;
- (void)setAccountID:(id)arg1;
- (id)displayName;
- (void)setDisplayName:(id)arg1;
- (id)lastModifiedCollection;
- (void)setLastModifiedCollection:(id)arg1;
- (id)subAccounts;
- (void)setSubAccounts:(id)arg1;
- (id)mediaCollections;
- (void)setMediaCollections:(id)arg1;
- (id)modDate;
- (void)setModDate:(id)arg1;
- (id)lastCheckedDate;
- (void)setLastCheckedDate:(id)arg1;
- (id)accountIconPath;
- (void)setAccountIconPath:(id)arg1;

@end

