/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVSWUpdateServerIPController.h>

@class NSString;

@interface ATVIPEntryDialog : ATVSWUpdateServerIPController
{
    NSString *_dialogID;
}

- (void)dealloc;
- (id)dialogID;
- (id)runModal;
- (BOOL)brEventAction:(id)arg1;

@end

