/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVFavorite.h>

@class NSString;

@interface ATVInternetRadioFavorite : ATVFavorite
{
    NSString *_stationID;
    NSString *_collectionTitle;
}

+ (void)initialize;
+ (void)_stationFoundInGenre:(id)arg1;
+ (id)favoriteFromAsset:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)genre;
- (void)setGenre:(id)arg1;
- (id)mediaAsset;
- (void)setStationID:(id)arg1;
- (id)stationID;

@end

