/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRMenuController.h"

#import "BRMenuListItemProvider-Protocol.h"

@class NSArray;

@interface ATVInitialBSRController : BRMenuController <BRMenuListItemProvider>
{
    NSArray *_listOfResolutionsToTry;
}

- (id)init;
- (void)dealloc;
- (void)controlWasActivated;
- (BOOL)brEventAction:(id)arg1;
- (void)itemSelected:(long)arg1;
- (long)defaultIndex;
- (id)itemForRow:(long)arg1;
- (long)itemCount;
- (id)titleForRow:(long)arg1;
- (float)heightForRow:(long)arg1;
- (BOOL)rowSelectable:(long)arg1;

@end

