/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVInternetPhotosMonitor.h>

@interface ATVInternetPhotosMonitor (DataMonitoring)
- (void)_registerObjectForDataMonitoring:(id)arg1;
- (void)_cancelDataMonitoringForObject:(id)arg1;
@end

