/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSingleton.h"

@interface ATVITunesLibraryDiskSpaceAccess : BRSingleton
{
    id _delegate;
}

+ (id)singleton;
+ (void)setSingleton:(id)arg1;
- (void)dealloc;
- (void)setITunesDiskSpaceDelegate:(id)arg1;
- (unsigned long long)iTunesReportedMediaCapacity;
- (unsigned long long)iTunesReportedMediaFreeSpace;
- (unsigned long long)iTunesReportedTotalSyncedDiskBytes;
- (long)iTunesRecomputeDiskFreeSpaceReserve;

@end

