/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVCatalogApplianceController.h>

@class BRControl, BRListControl, BRMediaShelfControl, NSDictionary;

@interface ATVMusicStoreMoreInfoController : ATVCatalogApplianceController
{
    NSDictionary *_catalogItem;
    BRListControl *_list;
    BRControl *_previousPosterControl;
    BOOL _localListContentSelected;
    BRMediaShelfControl *_actionShelfControl;
    long _lastSelectedIndex;
}

- (id)initWithCatalogItem:(id)arg1;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (id)focusedControlForEvent:(id)arg1 focusPoint:(struct CGPoint *)arg2;

@end

