/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreDownloadsController.h>

@interface ATVMusicStoreDownloadsController (ListManagement)
- (void)_buildHeaderList;
- (void)_refreshDownloadsList;
- (void)_checkForDownloadsItemSelected;
- (id)_checkForDownloadsPreview;
@end

