/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreCatalogItemController.h>

@interface ATVMusicStoreCatalogItemController (LoadRelatedContent)
- (void)fetchRelatedContent;
- (void)fetchRelatedContentFromURL:(id)arg1;
- (void)relatedContentReceived:(id)arg1;
- (id)augmentedRelatedContentItemsFromPage:(id)arg1;
@end

