/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreTransactionDialog.h>

@interface ATVMusicStoreTransactionDialog (Acquisition)
- (void)_acquireItem:(id)arg1;
- (void)_acquisitionSucceeded:(id)arg1;
- (void)_acquisitionCancelled:(id)arg1;
- (void)_acquisitionFailed:(id)arg1;
- (void)_displayDiskReservationFailedDialog;
- (void)_networkStatusChanged:(id)arg1;
@end

