/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreMovieMetadataProvider.h>

@interface ATVMusicStoreMovieMetadataProvider (Private)
- (void)_populateMetadataDetails:(id)arg1 withStoreOffer:(id)arg2;
- (void)_populateMovieDetails:(id)arg1 withStoreOffer:(id)arg2;
- (void)_populateActors:(id)arg1;
- (void)_populateDirector:(id)arg1;
- (void)_populateProducers:(id)arg1;
- (void)_populateSubtitles:(id)arg1;
- (void)_populateAudio:(id)arg1;
@end

