/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary;

@interface ATVMusicStoreCatalogItemProviderFactory : NSObject
{
    NSDictionary *_catalogItem;
    NSDictionary *_actionItems;
    NSDictionary *_dateItems;
}

+ (id)providerFactoryWithCatalogItem:(id)arg1;
- (id)initWithCatalogItem:(id)arg1;
- (void)dealloc;
- (id)actionItems;
- (id)imageProxy;
- (id)metadataProvider;
- (id)abbreviatedMetadataProvider;
- (id)moreInfoProvider;
- (id)storeOffersProvider;
- (id)dateAvailableProvider;
- (id)storeOffersSansPreviewsProvider;
- (id)actionProviders;
- (id)copyrightProvider;
- (id)relatedProvider;
- (id)listProviders;
- (id)previewBrowserProvider;

@end

