/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreSearchAgent.h>

@interface ATVMusicStoreSearchAgent (Private)
- (void)_loadSearchURL:(id)arg1 forSearchTerm:(id)arg2;
- (void)_searchRequestProcessed:(id)arg1;
- (void)_searchComplete:(id)arg1 forSearchTerm:(id)arg2;
@end

