/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreDownloadsController.h>

@interface ATVMusicStoreDownloadsController (DownloadDialogManagement)
- (BOOL)_downloadIsStorePurchase:(id)arg1;
- (void)_postManagementDialogForDownload:(id)arg1;
- (void)_dismissManagementDialog;
- (void)_setDownloadBeingManaged:(id)arg1;
- (void)_downloadWillBeRemoved:(id)arg1;
- (void)_managementDialogSelectionHandler;
- (void)_switchStateOfDownload:(id)arg1;
@end

