/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreTransactionDialog.h>

@interface ATVMusicStoreTransactionDialog (Util)
- (void)_stopListeningForNotifications:(id)arg1 object:(id)arg2;
@end

