/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRPosterControl.h"

@class NSTimer;

@interface ATVMoviesButtonControl : BRPosterControl
{
    id _asset;
    NSTimer *_expiryCheckTimer;
    BOOL _expirationTextInNonAlertState;
    NSTimer *_downloadDescriptionSwitchingTimer;
    BOOL _displayTimeUntilPlay;
}

+ (id)enhancedPosterButtonWithImage:(id)arg1 title:(id)arg2 subtitle:(id)arg3 badge:(id)arg4;
+ (id)buttonForAsset:(id)arg1;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)controlWasFocused;
- (void)controlWasUnfocused;

@end

