/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreXMLDocumentPreProcessor.h>

@interface ATVMusicStoreXMLDocumentPreProcessor (Private)
- (id)_processDocument:(id)arg1;
- (void)_processIncludes:(id)arg1;
- (void)_processConditionalGroups:(id)arg1;
- (id)_processIncludeElement:(id)arg1;
- (void)_processConditionalGroupElement:(id)arg1;
- (id)_processIncludeDictionary:(id)arg1 representingElement:(id)arg2;
- (BOOL)_processConditionalGroupDictionary:(id)arg1;
- (BOOL)_evaluateConditional:(id)arg1;
- (BOOL)_processConditionalResult:(BOOL)arg1 isAnd:(BOOL)arg2 isOr:(BOOL)arg3 isNot:(BOOL)arg4;
- (id)_dictionaryFromElement:(id)arg1;
- (void)_replaceElement:(id)arg1 withElement:(id)arg2;
- (BOOL)_evaluateKey:(id)arg1 operator:(id)arg2 value:(id)arg3;
- (void)_processIncludeRequests:(id)arg1;
- (void)_replaceElement:(id)arg1 withContainedElementNamed:(id)arg2;
- (void)_removeElement:(id)arg1;
@end

