/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreTransactionDialog.h>

@interface ATVMusicStoreTransactionDialog (Authentication)
- (id)_qualifyAccount:(id)arg1;
- (void)_initiateAuthenticationForAccount:(id)arg1;
- (void)_authenticateAccount:(id)arg1;
- (void)_authenticationSucceeded:(id)arg1;
- (void)_authenticationFailed:(id)arg1;
- (void)_authenticationCancelled:(id)arg1;
- (BOOL)_shouldAttemptAuthenticationAgain:(id)arg1;
- (void)_removeUnauthorizedAccount:(id)arg1;
@end

