/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreItemDetailController.h>

@interface ATVMusicStoreItemDetailController (Private)
- (void)_layoutControls;
- (void)_updateFocus;
- (void)_nextItemSelected:(id)arg1;
- (void)_previousItemSelected:(id)arg1;
- (id)_displayableItemAfter:(id)arg1;
- (id)_displayableItemBefore:(id)arg1;
- (id)_displayableItemAdjacentTo:(id)arg1 forward:(BOOL)arg2;
@end

