/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreControlPopulator.h>

@interface ATVMusicStoreControlPopulator (Heights)
- (float)_unscaledButtonHeightForData:(id)arg1;
- (float)_unscaledShelfHeightForData:(id)arg1;
@end

