/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreMusicVideoMetadataProvider.h>

@interface ATVMusicStoreMusicVideoMetadataProvider (Private)
+ (void)_initializeMappings:(id)arg1;
+ (void)_initializeDetailedTransformers;
+ (void)_initializeAbbreviatedTransformers;
- (void)_populateAbbreviatedMetadata:(id)arg1;
- (void)_populateDetailedMetadata:(id)arg1;
@end

