/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStorePresentsProvider.h>

@interface ATVMusicStorePresentsProvider (Private)
- (id)_initWithMediaType:(id)arg1 forID:(id)arg2;
- (void)_setTitle:(id)arg1;
@end

