/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRMediaMenuController.h"

#import "BRMenuListItemProvider-Protocol.h"

@class BRDownloadManager, BRImageAndSyncingPreviewController, BROptionDialog, BRTextMenuItemLayer, NSArray, NSString, NSTimer;

@interface ATVMusicStoreDownloadsController : BRMediaMenuController <BRMenuListItemProvider>
{
    BRDownloadManager *_rentalDownloadManager;
    NSArray *_cachedRentalDownloadsList;
    BOOL _isCheckingForPurchases;
    NSTimer *_periodicUpdatesTimer;
    int _timerCallbackAccumulator;
    NSArray *_headerList;
    BRTextMenuItemLayer *_checkForPurchasesMenuItem;
    BRImageAndSyncingPreviewController *_imageControl;
    BROptionDialog *_downloadDialog;
    NSString *_checkForPurchasesOverrideString;
    id _downloadBeingManaged;
}

- (id)init;
- (void)dealloc;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (id)previewControlForItem:(long)arg1;
- (BOOL)allowUnplayedMark;
- (long)itemCount;
- (id)titleForRow:(long)arg1;
- (id)itemForRow:(long)arg1;
- (float)heightForRow:(long)arg1;
- (BOOL)rowSelectable:(long)arg1;
- (void)itemSelected:(long)arg1;
- (long)defaultIndex;

@end

