/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreSingleItemPopulator.h>

@interface ATVMusicStoreSingleItemPopulator (Private)
- (id)_iconForItemType:(int)arg1 title:(id)arg2;
- (int)_trackCountForItem:(id)arg1;
@end

