/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreMoreInfoController.h>

@interface ATVMusicStoreMoreInfoController (LocalContent)
- (id)_summaryControl;
- (id)_summaryControlForItem:(id)arg1;
- (id)_coverArtControl;
- (id)_grid;
@end

