/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVMusicStoreTabbedPageController.h>

@interface ATVMusicStoreTabbedPageController (Private)
- (id)_scrollPlane;
- (void)_replaceScrollerContentBelowTabWithControls:(id)arg1;
- (void)_focusTabControl;
- (void)_focusFirstControlBelowTabControl;
- (id)_tabDictionary;
- (id)_tabName;
- (id)_preferredTabSegmentInTab;
@end

