/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVRemoteControlMessageHandler.h>

@interface ATVRemoteControlMessageHandler (SelectionChange)
- (struct CGPoint)_getSelectionPosition:(struct CGPoint)arg1;
- (void)_processSelectionChange:(int)arg1 delta:(int)arg2;
- (void)_sendDirectionEvent:(int)arg1 value:(int)arg2;
@end

