/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVRentedMoviesProvider.h>

@interface ATVRentedMoviesProvider (Private)
- (id)_rentedMovies;
- (void)_objectWillBeDeletedNotification:(id)arg1;
- (void)_dataUpdateNotification:(id)arg1;
- (void)_rentalStateUpdateNotification:(id)arg1;
- (void)_reloadMoviesSendingGeneralModifiedNotification:(BOOL)arg1 ignoringAsset:(id)arg2;
@end

