/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class ATVRCButtonPatternSet, NSArray, NSTimer;

@interface ATVRCPatternMatcher : NSObject
{
    int _matchState;
    int _buttonState;
    ATVRCButtonPatternSet *_patternSet;
    long _matchIndex;
    NSTimer *_discontinuityTrigger;
    NSTimer *_holdTrigger;
    double _lastEventTimestamp;
    unsigned int _pairingMask;
    unsigned int _payloadMask;
    unsigned int _pairingID;
    NSArray *_upEvents;
    NSArray *_holdEvents;
    NSArray *_downEvents;
    id _delegate;
}

+ (id)findRepeatPattern:(id)arg1 startIndex:(long)arg2;
+ (id)findFirstPattern:(id)arg1 startIndex:(long)arg2 minPatternLength:(long)arg3;
+ (BOOL)findEventInSet:(id)arg1 event:(id)arg2 startIndex:(long)arg3 numEventstoSearch:(long)arg4;
+ (BOOL)matchPattern:(id)arg1 pattern:(id)arg2 atIndex:(long)arg3;
+ (BOOL)matchEvent:(id)arg1 withEvent:(id)arg2;
+ (double)intervalBetweenLastEvents:(id)arg1;
+ (double)intervalBetweenFirstAndLastEvent:(id)arg1;
- (id)initWithPatternSet:(id)arg1 delegate:(id)arg2;
- (void)dealloc;
- (void)reset;
- (void)setPatternSet:(id)arg1;
- (void)setDelegate:(id)arg1;
- (id)patternSet;
- (void)setDownEvents:(id)arg1;
- (void)setHoldEvents:(id)arg1;
- (void)setUpEvents:(id)arg1;
- (id)downEvents;
- (id)holdEvents;
- (id)upEvents;
- (BOOL)processEvent:(id)arg1 uidMismatchStatus:(char *)arg2;
- (void)setPairingInfo:(unsigned long)arg1 pairingMask:(unsigned long)arg2 payloadMask:(unsigned long)arg3;
- (void)forceReleaseState;

@end

