/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class ATVDirectionalRemoteConnectionHandler, NSMutableArray, NSTimer;

@interface ATVRemoteControlMessageHandler : NSObject
{
    int _touchDirection;
    struct CGPoint _startPoint;
    double _lastTimeStamp;
    struct CGPoint _lastPoint;
    NSTimer *_swipeTimer;
    NSTimer *_easeOutTimer;
    double _easeOutInterval;
    double _easeOutDecelerationFactor;
    BOOL _easeOutRepeat;
    struct CGPoint _autoScrollStartPoint;
    double _autoScrollStartInterval;
    NSTimer *_autoScrollContinueTimer;
    BOOL _isReallyReallyAutoScrolling;
    double _autoScrollInterval;
    struct CGPoint _velocityAdjustOffset;
    struct CGPoint _lastVelocityRefPoint;
    struct CGPoint _velocityVector;
    NSMutableArray *_velocitySet;
    int _touchCount;
    NSMutableArray *_throttledEventQueue;
    NSTimer *_throttleEventTimer;
    BOOL _prohibitSelect;
    BOOL _activelyScrolling;
    struct CGSize _selectionChange;
    ATVDirectionalRemoteConnectionHandler *_connectionHandler;
    NSTimer *_connectionTimeoutTimer;
}

- (id)init;
- (void)dealloc;
- (void)invalidate;
- (BOOL)handleDirectionalRemoteMessage:(unsigned long)arg1 value:(unsigned long)arg2 eventDictionary:(id)arg3;

@end

