/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVRemoteControlMessageHandler.h>

@interface ATVRemoteControlMessageHandler (EventPosting)
- (void)_postEvent:(id)arg1;
- (void)_postThrottledEvent:(id)arg1;
- (void)_throttleEventTimerCallback;
- (void)_clearEventQueue;
@end

