/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRController.h"

@interface ATVReadMeController : BRController
{
    BOOL _loadSucceeded;
}

+ (id)readMeController;
- (id)init;
- (void)dealloc;
- (void)wasPushed;
- (void)wasPopped;
- (BOOL)brEventAction:(id)arg1;

@end

