/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVRCPatternMatcher.h>

@interface ATVRCPatternMatcher (Private)
- (id)_processPairingInfo:(id)arg1 uidMismatchStatus:(char *)arg2;
- (BOOL)_matchEvent:(id)arg1 against:(id)arg2;
- (void)_commandPatternMatched;
- (void)_resetDiscontinuityTrigger;
- (void)_clearDiscontinuityTrigger;
- (void)_resetHoldTrigger;
- (void)_clearHoldTrigger;
- (double)_discontinuityTriggerInterval;
- (void)_checkDiscontinuityTrigger:(id)arg1;
- (void)_discontinuityTriggered;
- (void)_holdTriggered;
- (void)_dispatchEvents:(id)arg1;
@end

