/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "ATVRCPatternMatcherDelegate-Protocol.h"

@class NSArray, NSString;

@interface ATVRemoteSet : NSObject <ATVRCPatternMatcherDelegate>
{
    NSArray *_remoteSet;
    NSString *_name;
    BOOL _custom;
}

- (id)init;
- (id)initWithDictionary:(id)arg1;
- (void)dealloc;
- (int)processEvent:(id)arg1;
- (id)getPatternSet:(int)arg1;
- (id)getPatternMatcher:(int)arg1;
- (void)matcherButtonDown:(id)arg1;
- (void)matcherButtonRelease:(id)arg1;
- (id)encodeToDictionary;
- (BOOL)hasExtendedSet;
- (void)resetMatchers;
- (id)name;
- (void)setName:(id)arg1;
- (BOOL)custom;
- (void)setCustom:(BOOL)arg1;
- (BOOL)isEqualTo:(id)arg1;
- (void)setPairingInfo:(unsigned long)arg1 pairingMask:(unsigned long)arg2 payloadMask:(unsigned long)arg3;
- (void)applyLearnedButtonsToSet:(id)arg1 buttons:(struct _NSRange)arg2;
- (int)findIdenticalButtonPattern:(id)arg1;

@end

