/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVRCManager.h>

@interface ATVRCManager (LEDBehavior)
- (void)_eventRecognized:(BOOL)arg1;
- (void)_resetLEDTimer;
- (void)_ledReset:(id)arg1;
@end

