/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRControl.h"

@class BRHeaderControl, BRScrollingTextBoxControl, BRTextControl;

@interface ATVReadMeControl : BRControl
{
    BRHeaderControl *_header;
    BRScrollingTextBoxControl *_textBox;
    BRTextControl *_informationTextControl;
}

- (id)init;
- (void)dealloc;
- (void)setTitle:(id)arg1;
- (void)setText:(id)arg1 withAttributes:(id)arg2;
- (void)setInformationText:(id)arg1 withAttributes:(id)arg2;

@end

