/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRMenuController.h"

#import "BRTextFieldDelegate-Protocol.h"

@class ATVSearchAgent, BRImageControl, BRMediatorProvider, BRTextEntryControl, NSString;

@interface ATVSearchController : BRMenuController <BRTextFieldDelegate>
{
    BRTextEntryControl *_editor;
    BRImageControl *_arrow;
    ATVSearchAgent *_agent;
    BRMediatorProvider *_recentSearchesProvider;
    NSString *_activeSearchRequest;
}

- (id)initWithSearchAgent:(id)arg1;
- (void)dealloc;
- (void)layoutSubcontrols;
- (BOOL)isNetworkDependent;
- (BOOL)isValidAfterDataUpdate;
- (id)searchAgent;
- (void)searchWithString:(id)arg1;
- (void)setKeyboardTextEntryStyle:(int)arg1;
- (BOOL)brEventAction:(id)arg1;
- (void)setSearchFieldLabel:(id)arg1;
- (void)setHeaderTitle:(id)arg1;
- (long)defaultIndex;
- (void)textDidChange:(id)arg1;
- (void)textDidEndEditing:(id)arg1;
- (id)providersForContextMenu;
- (id)controlToDim;

@end

