/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSString;

@interface ATVSWUpdateRecord : NSObject
{
    NSString *_currentOSVersion;
    NSString *_currentOSBuildVersion;
    NSString *_currentEFIVersion;
    NSString *_currentIRVersion;
    NSString *_currentSIMainVersion;
    NSString *_currentSIBootVersion;
    NSString *_newOSVersion;
    NSString *_newOSBuildVersion;
    NSString *_newEFIVersion;
    NSString *_newIRVersion;
    NSString *_newSIMainVersion;
    NSString *_newSIBootVersion;
    NSDictionary *_osUpdateURLs;
    NSDictionary *_efiUpdateURLs;
    NSDictionary *_irUpdateURLs;
    NSDictionary *_siUpdateURLs;
    NSString *_mediaUpdateURL;
    unsigned long long _totalDownloadSize;
    BOOL _autoUpdate;
    BOOL _SIImageValid;
}

- (id)initWithVersionData:(id)arg1 autoUpdate:(BOOL)arg2;
- (void)dealloc;
- (id)description;
- (BOOL)osUpdateAvailable;
- (BOOL)efiUpdateAvailable;
- (BOOL)irUpdateAvailable;
- (BOOL)siMainUpdateAvailable;
- (BOOL)siBootUpdateAvailable;
- (BOOL)anyUpdateAvailable;
- (BOOL)autoUpdate;
- (unsigned long long)totalDownloadSize;
- (id)newOSVersion;
- (id)newOSBuildVersion;
- (id)newEFIVersion;
- (id)newIRVersion;
- (id)newSIMainVersion;
- (id)newSIBootVersion;
- (id)payloadURLs;
- (id)licenseURLs;
- (id)readmeURLs;
- (id)mediaUpdateURL;

@end

