/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRSettingsFacade.h"

@interface ATVSettingsFacade : BRSettingsFacade
{
}

+ (void)initializePlatformFacade;
- (id)init;
- (void)dealloc;
- (void)resetAllSettings;
- (long)mediaSongCount;
- (long)mediaVideoCount;
- (long)mediaPhotoCount;
- (id)screenSaverPaths;
- (id)screenSaverSelectedPath;
- (void)setScreenSaverSelectedPath:(id)arg1;
- (id)providerIDForCurrentScreenSaver;
- (id)providerForScreenSaver;
- (id)screenSaverCollection;
- (void)setScreenSaverPhotoCollection:(id)arg1;
- (int)screenSaverTimeout;
- (void)setScreenSaverTimeout:(int)arg1;
- (int)screenSaverPhotoSpinFrequency;
- (id)slideshowScreensaverPlaybackOptions;
- (id)screenSaverInvocation;
- (int)screenSaverSecondsPerSlide;
- (void)setScreenSaverSecondsPerSlide:(int)arg1;
- (BOOL)screenSaverPanAndZoom;
- (void)setScreenSaverPanAndZoom:(BOOL)arg1;
- (BOOL)screenSaverShufflePhotos;
- (void)setScreenSaverShufflePhotos:(BOOL)arg1;
- (id)screenSaverTransition;
- (void)setScreenSaverTransition:(id)arg1;
- (BOOL)bootedFromRecoveryPartition;
- (BOOL)saveConfiguration:(id)arg1;
- (BOOL)syncIsSynced;
- (id)syncHostName;
- (BOOL)syncControlDisabled;
- (BOOL)musicUseSoundCheck;
- (void)setMusicUseSoundCheck:(BOOL)arg1;
- (id)hwDeviceName;
- (void)setHWDeviceName:(id)arg1;
- (id)hwSerialNumber;
- (id)hwMachineModel;
- (BOOL)hwSetSystemLanguage:(id)arg1;
- (void)remotePair;
- (void)remoteUnpair;
- (BOOL)remoteIsPaired;
- (id)versionOS;
- (id)versionEFI;
- (id)versionIR;
- (id)versionGF;
- (BOOL)setColorSpace:(int)arg1;
- (int)colorSpace;
- (BOOL)videoLimitHDMIRange;
- (void)setVideoLimitHDMIRange:(BOOL)arg1;
- (BOOL)airTunesIsEnabled;
- (void)setAirTunesIsEnabled:(BOOL)arg1;
- (BOOL)airTunesPasswordIsEnabled;
- (id)airTunesPassword;
- (void)setAirTunesPassword:(id)arg1;
- (BOOL)airTunesControlFromSpeakerIsEnabled;
- (void)setAirTunesControlFromSpeakerIsEnabled:(BOOL)arg1;
- (void)setCrashReportingEnabled:(BOOL)arg1;
- (BOOL)crashReportingEnabled;
- (BOOL)crashReportingPreferenceSet;

@end

