/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVSWUpdateManager.h>

@interface ATVSWUpdateManager (Downloading)
- (void)_postDialog:(id)arg1;
- (void)_startCheckTimer;
- (void)_checkForUpdatesAgainSoon;
- (void)_checkForUpdatesAgainAfter:(float)arg1;
- (void)_setNextCheckTime;
- (void)_checkForUpdates:(id)arg1;
- (void)_performUpdateCheck;
- (BOOL)_downloadAndVerifyUpdates:(id *)arg1 existingFilesValid:(BOOL)arg2;
- (id)_downloadFileForURL:(id)arg1 andVerify:(BOOL)arg2 error:(id *)arg3;
- (id)_localFileForURL:(id)arg1 error:(id *)arg2;
- (id)_localFileForURL:(id)arg1 destFileName:(id)arg2 error:(id *)arg3;
- (void)_sendProgressNotification;
- (void)_cleanUpFiles;
- (id)_localFilePathForUpdateURL:(id)arg1;
- (id)_downloadCombinedUpdatePayloadFromRecord:(id)arg1;
- (id)_downloadUpdatePayloadsFromRecord:(id)arg1;
- (id)_downloadLicensesFromRecord:(id)arg1;
- (BOOL)_shouldVerifyFile:(id)arg1;
- (void)_confirmUpdate;
- (BOOL)_existingUpdateFilesOnDiskAreValidAndCurrent:(id)arg1;
- (id)_filesDownloadedSentinelPath;
- (void)_createFilesDownloadedSentinelFile;
- (BOOL)_downloadedFilesAreComplete;
@end

