/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVSWUpdateManager.h>

@interface ATVSWUpdateManager (SeedUpdates)
- (BOOL)_constructUpdateURL:(BOOL)arg1;
- (id)_getRetailType;
- (id)_getUpdateIPAddress;
- (void)_setPassphrase;
@end

