/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVSettingsFacade.h>

@interface ATVSettingsFacade (Private)
- (void)_systemDateMismatch:(id)arg1;
- (void)_setScreenSaverCollection:(id)arg1;
- (long)_itemCountForMediaType:(id)arg1;
- (void)_createPrefDataForLegacyPreferences;
@end

