/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class ATVTCPControlReceiver, NSData, NSInputStream, NSMutableArray, NSMutableData, NSOutputStream;

@interface ATVTCPConnection : NSObject
{
    id _delegate;
    NSData *_peerAddress;
    ATVTCPControlReceiver *_server;
    NSMutableArray *_requests;
    NSInputStream *_istream;
    NSOutputStream *_ostream;
    NSMutableData *_ibuffer;
    NSMutableData *_obuffer;
    BOOL _isValid;
}

- (id)init;
- (id)initWithPeerAddress:(id)arg1 inputStream:(id)arg2 outputStream:(id)arg3 forServer:(id)arg4;
- (void)dealloc;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (id)peerAddress;
- (id)server;
- (BOOL)isValid;
- (void)invalidate;
- (BOOL)processIncomingBytes;
- (void)stream:(id)arg1 handleEvent:(int)arg2;

@end

