/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVTouchRemoteManager.h>

@interface ATVTouchRemoteManager (Private)
- (void)_userAction;
- (void)_startTrickSpeedAdvanceTimer;
- (void)_stopTrickSpeedAdvanceTimer;
- (void)_updateTrickSpeed:(id)arg1;
- (BOOL)_preparePlayback;
- (void)_startPlaybackWithPlayer:(id)arg1;
@end

