/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRMenuController.h"

#import "BRDottedQuadEntryDelegate-Protocol.h"
#import "BRMenuListItemProvider-Protocol.h"

@class BRDottedQuadEntryController, NSString;

@interface ATVTCPIPConfigController : BRMenuController <BRMenuListItemProvider, BRDottedQuadEntryDelegate>
{
    id _delegate;
    NSString *_address;
    NSString *_subnetMask;
    NSString *_router;
    NSString *_dns;
    BRDottedQuadEntryController *_ipController;
    BRDottedQuadEntryController *_maskController;
    BRDottedQuadEntryController *_routerController;
    BRDottedQuadEntryController *_dnsController;
    unsigned int _forWireless:1;
    unsigned int _useDHCP:1;
}

- (id)initWithWireless:(BOOL)arg1 notifying:(id)arg2;
- (void)dealloc;
- (void)itemSelected:(long)arg1;
- (id)itemForRow:(long)arg1;
- (long)itemCount;
- (id)titleForRow:(long)arg1;
- (float)heightForRow:(long)arg1;
- (BOOL)rowSelectable:(long)arg1;
- (void)entryComplete:(id)arg1;

@end

