/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <AppleTV/ATVUpdateVerifier.h>

@interface ATVUpdateVerifier (Private)
- (BOOL)privateVerifyFile:(id)arg1 withSignatureFile:(id)arg2 withKey:(struct cssm_key *)arg3;
- (struct cssm_key *)_publicKey;
- (long)_verifyDataInFile:(id)arg1 usingContext:(unsigned long long)arg2;
- (long)_verifySignatureInFile:(id)arg1 usingContext:(unsigned long long)arg2;
- (id)_stringFromCSSMResult:(long)arg1;
@end

