/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface ATVVersionInfo : NSObject
{
}

+ (id)currentOSVersion;
+ (id)currentOSBuildVersion;
+ (int)compareOSVersion:(id)arg1 andBuild:(id)arg2 withOSVersion:(id)arg3 andBuild:(id)arg4;
+ (id)currentEFIVersion;
+ (int)compareEFIVersion:(id)arg1 withEFIVersion:(id)arg2;
+ (id)currentIRVersion;
+ (int)compareIRVersion:(id)arg1 withIRVersion:(id)arg2;
+ (id)currentSIMainVersion;
+ (id)currentSIBootVersion;
+ (BOOL)isSIFirmwareValid;
+ (int)compareSIVersion:(id)arg1 withSIVersion:(id)arg2;

@end

