/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "BRControl.h"

@interface BRControl (DataMapping)
- (void)mapDataObject:(id)arg1 withMappings:(id)arg2;
@end

