/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BRImageProxy <NSObject>
- (id)imageIDForImageSize:(int)arg1;
- (id)imageForImageSize:(int)arg1;
- (id)defaultImageForImageSize:(int)arg1;
- (BOOL)supportsImageForImageSize:(int)arg1;
- (void)cancelImageRequestsForImageSizes:(int)arg1;
- (id)object;
@end

